import type { SiteLanguage } from "@/lib/routeLanguage";

export const SERVICE_UI = {
  en: {
    back: "All services", consultation: "Get a free consultation", pricing: "Explore packages & care", why: "The thinking behind it", whyTitle: "Made to work for your visitors.", deliver: "What we work on", deliverTitle: "The details make the difference.", scope: "Your package and agreed scope define the pages, features and revisions. We confirm these before starting, and quote additional work separately.", process: "From direction to delivery", processTitle: "A clear way forward.", processLink: "See the full process", questions: "Good questions.", related: "Bring it all together.", closing: "What would you like your website to do?", closingCopy: "Tell us about your business or ask us anything. We’ll help you find a sensible next step. Your first consultation is free, with no obligation.", study: "A visual direction, across the details", studyNote: "Brand concept · design study",
    demoTitle: "One message. Every screen.", demoNote: "An illustrative layout. Switch the view to see the same content adapt.", views: ["Phone", "Tablet", "Desktop"], demoLabel: "Your business", demoHeading: "A story worth sharing.", demoBody: "What you do. Why it matters.", demoAction: "Let’s talk", demoCaption: "The same story, on every screen.",
    experience: "How a good experience feels", metrics: [["Load", "Reach the main content."], ["Respond", "Act without unnecessary delay."], ["Stay steady", "Read without unexpected shifts."]], metricNote: "Loading, interaction and visual stability.",
  },
  el: {
    back: "Όλες οι υπηρεσίες",
    consultation: "Δωρεάν συμβουλευτική",
    pricing: "Πακέτα και συντήρηση",
    why: "Γιατί το κάνουμε έτσι",
    whyTitle: "Σκεφτόμαστε πρώτα τον επισκέπτη σας.",
    deliver: "Τι περιλαμβάνει",
    deliverTitle: "Οι λεπτομέρειες κάνουν τη διαφορά.",
    scope: "Οι σελίδες, οι λειτουργίες και οι γύροι διορθώσεων εξαρτώνται από το πακέτο σας και από ό,τι συμφωνήσουμε. Τα επιβεβαιώνουμε πριν ξεκινήσουμε, και ό,τι παραπάνω το κοστολογούμε ξεχωριστά.",
    process: "Πώς δουλεύουμε",
    processTitle: "Βήμα βήμα, χωρίς πολλά-πολλά.",
    processLink: "Δείτε όλη τη διαδικασία",
    questions: "Όσα μας ρωτάτε συχνά.",
    related: "Δείτε επίσης.",
    closing: "Τι θέλετε να πετύχει η ιστοσελίδα σας;",
    closingCopy: "Πείτε μας για την επιχείρησή σας ή ρωτήστε ό,τι θέλετε, και θα βρούμε μαζί ποιο είναι το λογικό επόμενο βήμα. Η πρώτη συμβουλευτική είναι δωρεάν και χωρίς δέσμευση.",
    study: "Το ίδιο ύφος, μέχρι την τελευταία λεπτομέρεια",
    studyNote: "Οπτική ταυτότητα · σχεδιαστική μελέτη",
    demoTitle: "Το ίδιο περιεχόμενο, σε κάθε οθόνη.",
    demoNote: "Ενδεικτικό παράδειγμα. Αλλάξτε οθόνη και δείτε πώς το ίδιο περιεχόμενο προσαρμόζεται.",
    views: ["Κινητό", "Tablet", "Υπολογιστής"],
    demoLabel: "Η επιχείρησή σας",
    demoHeading: "Μια υπηρεσία που μπορείτε να εμπιστευτείτε.",
    demoBody: "Λίγα λόγια για το τι κάνετε.",
    demoAction: "Ας τα πούμε",
    demoCaption: "Ίδια ιστοσελίδα, από το κινητό ως τον υπολογιστή.",
    experience: "Πώς καταλαβαίνετε ότι μια ιστοσελίδα είναι γρήγορη",
    metrics: [
      ["Φόρτωση", "Το κύριο περιεχόμενο εμφανίζεται γρήγορα."],
      ["Απόκριση", "Πατάτε και γίνεται, χωρίς άσκοπη αναμονή."],
      ["Σταθερότητα", "Διαβάζετε χωρίς να μετακινείται η σελίδα."],
    ],
    metricNote: "Φόρτωση, απόκριση και σταθερότητα.",
  },
  he: {
    back: "כל השירותים",
    consultation: "לשיחת ייעוץ בחינם",
    pricing: "לחבילות ולתחזוקה",
    why: "למה ככה",
    whyTitle: "חושבים קודם כול על הלקוחות שלכם.",
    deliver: "מה כלול",
    deliverTitle: "הפרטים עושים את ההבדל.",
    scope: "העמודים, היכולות וסבבי התיקונים נקבעים לפי החבילה שלכם ולפי מה שסיכמנו. אנחנו מאשרים אותם לפני שמתחילים, וכל עבודה נוספת מתומחרת בנפרד.",
    process: "איך זה עובד",
    processTitle: "צעד אחרי צעד, בלי כאב ראש.",
    processLink: "לתהליך המלא",
    questions: "מה ששואלים אותנו הכי הרבה.",
    related: "עוד שירותים שכדאי להכיר.",
    closing: "מה תרצו שהאתר שלכם יעשה?",
    closingCopy: "ספרו לנו על העסק או שאלו כל מה שבא לכם, ונמצא יחד מה הצעד הבא. שיחת הייעוץ הראשונה בחינם וללא התחייבות.",
    study: "אותו סגנון, עד הפרט האחרון",
    studyNote: "קונספט מותג · המחשת עיצוב",
    demoTitle: "אותו תוכן, בכל מסך.",
    demoNote: "דוגמה להמחשה. בחרו מסך ותראו איך אותו תוכן מסתדר מחדש.",
    views: ["מובייל", "טאבלט", "מחשב"],
    demoLabel: "העסק שלכם",
    demoHeading: "שירות שאפשר לסמוך עליו.",
    demoBody: "כמה מילים על מה שאתם עושים.",
    demoAction: "בואו נדבר",
    demoCaption: "אותו אתר, מהמובייל ועד המחשב.",
    experience: "איך יודעים שאתר מהיר",
    metrics: [
      ["טעינה", "התוכן המרכזי מופיע מהר."],
      ["תגובה", "לוחצים וזה קורה, בלי לחכות סתם."],
      ["יציבות", "קוראים בלי שהעמוד קופץ."],
    ],
    metricNote: "טעינה, תגובה ויציבות.",
  },
} satisfies Record<SiteLanguage, unknown>;
