import type { SiteLanguage } from "@/lib/routeLanguage";

export const SERVICE_VISUAL_COPY = {
  en: {
    explore: "Explore the details", story: "A closer look", scope: "View the full scope",
    design: ["First impression", "Brand language", "Clear direction"], mobile: ["Reading order", "Every screen", "Made for touch"], performance: ["Load", "Respond", "Stay steady"],
    type: "Type with character.", colour: "A palette with purpose.", layout: "Your story, clearly told.",
    concept: "Illustrative website concept", project: "FORM / STUDIO", siteEyebrow: "Design in focus", siteTitle: "A different perspective.", siteBody: "Considered details. Lasting impressions.", siteAction: "Explore the collection", siteNav: "Work / About / Contact", siteBottom: "Thoughtful by design", siteCollection: "The collection", siteNote: "Design · Craft · Detail",
    filmTitle: ["From a first idea", "to something that feels like you."], mobileTitle: ["Same story.", "A considered view, every time."], performanceTitle: ["A lighter page.", "A clearer path forward."],
    filmCaption: "Design study · illustrative imagery", flowNote: "An illustration of the experience, not a measured speed result.", flowAction: "Try the interaction", flowResult: "Ready to explore", before: "Your idea", after: "Your website", scopeShort: "The right details, agreed together.",
  },
  el: {
    explore: "Δείτε τις λεπτομέρειες",
    story: "Από κοντά",
    scope: "Δείτε τι περιλαμβάνει",
    design: ["Πρώτη εντύπωση", "Το brand σας", "Ξεκάθαρη δομή"],
    mobile: ["Σειρά ανάγνωσης", "Κάθε οθόνη", "Εύκολο στο άγγιγμα"],
    performance: ["Φόρτωση", "Απόκριση", "Σταθερότητα"],
    type: "Γραμματοσειρά που ταιριάζει στην επιχείρηση.",
    colour: "Χρώματα που ταιριάζουν στο brand.",
    layout: "Όλα στη σωστή θέση.",
    concept: "Ενδεικτική σχεδιαστική πρόταση",
    project: "FORM / STUDIO",
    siteEyebrow: "Στούντιο σχεδιασμού",
    siteTitle: "Μια διαφορετική ματιά.",
    siteBody: "Μικρές λεπτομέρειες, μεγάλη διαφορά.",
    siteAction: "Δείτε τη συλλογή",
    siteNav: "Έργα / Σχετικά / Επικοινωνία",
    siteBottom: "Μέχρι την τελευταία λεπτομέρεια",
    siteCollection: "Η συλλογή",
    siteNote: "Σχεδιασμός · Δημιουργία · Λεπτομέρεια",
    filmTitle: ["Από την πρώτη ιδέα", "στην ιστοσελίδα που σας αξίζει."],
    mobileTitle: ["Η ίδια ιστοσελίδα,", "άψογη σε κάθε οθόνη."],
    performanceTitle: ["Πιο ελαφριά σελίδα,", "πιο γρήγορα στο ζουμί."],
    filmCaption: "Σχεδιαστική μελέτη · ενδεικτικές εικόνες",
    flowNote: "Απεικόνιση της εμπειρίας, όχι μέτρηση ταχύτητας.",
    flowAction: "Δοκιμάστε το",
    flowResult: "Έτοιμο. Πάμε!",
    before: "Η ιδέα σας",
    after: "Η ιστοσελίδα σας",
    scopeShort: "Οι λεπτομέρειες που συμφωνούμε μαζί.",
  },
  he: {
    explore: "לפרטים",
    story: "מבט מקרוב",
    scope: "לכל פרטי העבודה",
    design: ["הרושם הראשון", "המותג שלכם", "מבנה ברור"],
    mobile: ["מה רואים קודם", "בכל מסך", "נוח לאצבע"],
    performance: ["טעינה", "תגובה", "יציבות"],
    type: "פונט שמתאים לעסק.",
    colour: "צבעים שמתאימים למותג.",
    layout: "כל דבר במקום הנכון.",
    concept: "קונספט אתר להמחשה",
    project: "FORM / STUDIO",
    siteEyebrow: "סטודיו לעיצוב",
    siteTitle: "נקודת מבט אחרת.",
    siteBody: "פרטים קטנים, רושם גדול.",
    siteAction: "לקולקציה",
    siteNav: "עבודות / אודות / צרו קשר",
    siteBottom: "עיצוב עד הפרט האחרון",
    siteCollection: "הקולקציה",
    siteNote: "עיצוב · יצירה · פרטים",
    filmTitle: ["מהרעיון הראשון", "לאתר שמציג את העסק במיטבו."],
    mobileTitle: ["אותו אתר,", "נראה טוב בכל מסך."],
    performanceTitle: ["עמוד קל יותר,", "ישר לעניין."],
    filmCaption: "המחשת עיצוב · תמונות להמחשה",
    flowNote: "המחשה בלבד, לא מדידת מהירות אמיתית.",
    flowAction: "נסו בעצמכם",
    flowResult: "מוכן, אפשר להתחיל",
    before: "הרעיון שלכם",
    after: "האתר שלכם",
    scopeShort: "הפרטים שמסכמים יחד.",
  },
} satisfies Record<SiteLanguage, unknown>;
