import type { SiteLanguage } from "@/lib/routeLanguage";

export const SERVICE_VISUAL_COPY = {
  en: {
    explore: "Explore the details", story: "A closer look", scope: "View the full scope",
    design: ["First impression", "Brand language", "Clear direction"], mobile: ["Reading order", "Every screen", "Made for touch"], performance: ["Load", "Respond", "Stay steady"],
    type: "Type with character.", colour: "A palette with purpose.", layout: "Your story, clearly told.",
    concept: "Illustrative website concept", project: "FORM / STUDIO", siteEyebrow: "Design in focus", siteTitle: "A different perspective.", siteBody: "Considered details. Lasting impressions.", siteAction: "Explore the collection", siteNav: "Work / About / Contact", siteBottom: "Thoughtful by design", siteCollection: "The collection", siteNote: "Design · Craft · Detail",
    filmTitle: ["From a first idea", "to something that feels like you."], mobileTitle: ["Same story.", "A considered view, every time."], performanceTitle: ["A lighter page.", "A clearer path forward."],
    filmCaption: "Design study · illustrative imagery", flowNote: "An illustration of the experience, not a measured speed result.", flowAction: "Try the interaction", flowResult: "Ready to explore", before: "Your idea", after: "Your website", scopeShort: "The right details, agreed together.",
  },
  el: {
    explore: "Δείτε τις λεπτομέρειες",
    story: "Από κοντά",
    scope: "Δείτε τι περιλαμβάνει",
    design: ["Πρώτη εντύπωση", "Το ύφος του brand", "Ξεκάθαρη κατεύθυνση"],
    mobile: ["Σειρά ανάγνωσης", "Κάθε οθόνη", "Εύκολο στο άγγιγμα"],
    performance: ["Φόρτωση", "Απόκριση", "Σταθερότητα"],
    type: "Γράμματα με χαρακτήρα.",
    colour: "Κάθε χρώμα έχει λόγο.",
    layout: "Η ιστορία σας, χωρίς μπερδέματα.",
    concept: "Ενδεικτική σχεδιαστική πρόταση",
    project: "FORM / STUDIO",
    siteEyebrow: "Ο σχεδιασμός στο επίκεντρο",
    siteTitle: "Μια διαφορετική ματιά.",
    siteBody: "Προσεγμένες λεπτομέρειες. Εντυπώσεις που μένουν.",
    siteAction: "Δείτε τη συλλογή",
    siteNav: "Έργα / Σχετικά / Επικοινωνία",
    siteBottom: "Σχεδιασμός με σκέψη",
    siteCollection: "Η συλλογή",
    siteNote: "Σχεδιασμός · Δημιουργία · Λεπτομέρεια",
    filmTitle: ["Από την πρώτη ιδέα", "σε κάτι που σας μοιάζει."],
    mobileTitle: ["Η ίδια ιστορία,", "προσεγμένη σε κάθε οθόνη."],
    performanceTitle: ["Πιο ελαφριά σελίδα,", "πιο γρήγορα στο ζουμί."],
    filmCaption: "Σχεδιαστική μελέτη · ενδεικτικές εικόνες",
    flowNote: "Απεικόνιση της εμπειρίας, όχι μέτρηση ταχύτητας.",
    flowAction: "Δοκιμάστε το",
    flowResult: "Έτοιμο. Πάμε!",
    before: "Η ιδέα σας",
    after: "Η ιστοσελίδα σας",
    scopeShort: "Οι λεπτομέρειες που συμφωνούμε μαζί.",
  },
  he: {
    explore: "מבט מקרוב",
    story: "נכנסים לפרטים",
    scope: "לכל פרטי העבודה",
    design: ["רושם ראשון", "השפה של המותג", "כיוון ברור"],
    mobile: ["סדר הקריאה", "בכל מסך", "נוח למגע"],
    performance: ["טעינה", "תגובה", "יציבות"],
    type: "אותיות עם אופי.",
    colour: "לכל צבע יש סיבה.",
    layout: "הסיפור שלכם, בלי בלבול.",
    concept: "קונספט אתר להמחשה",
    project: "FORM / STUDIO",
    siteEyebrow: "עיצוב במוקד",
    siteTitle: "נקודת מבט אחרת.",
    siteBody: "פרטים עם מחשבה. רושם שנשאר.",
    siteAction: "לגלות את הקולקציה",
    siteNav: "עבודות / אודות / קשר",
    siteBottom: "מעוצב עם מחשבה",
    siteCollection: "הקולקציה",
    siteNote: "עיצוב · יצירה · פרטים",
    filmTitle: ["מהרעיון הראשון", "למשהו שמרגיש כמוכם."],
    mobileTitle: ["אותו סיפור,", "בכל גודל מסך."],
    performanceTitle: ["עמוד קל יותר,", "ישר לעניין."],
    filmCaption: "המחשת עיצוב · תמונות להמחשה",
    flowNote: "המחשה של החוויה, לא תוצאת מדידת מהירות.",
    flowAction: "נסו בעצמכם",
    flowResult: "מוכן, אפשר להתחיל",
    before: "הרעיון שלכם",
    after: "האתר שלכם",
    scopeShort: "הפרטים שמסכמים יחד.",
  },
} satisfies Record<SiteLanguage, unknown>;
