import type { SiteLanguage } from "@/lib/routeLanguage";
import type { FoundationService, ServiceFeature } from "./serviceFeatureContent";

export const FOUNDATION_FEATURES: Record<SiteLanguage, Record<FoundationService, ServiceFeature>> = {
  en: {
    seo: {
      name: "Search Foundations", title: ["A clearer path", "to being found."], lead: "Help the right people understand what you offer, from their first search to your next conversation.",
      intro: "Useful content and a well-organised website give search a stronger starting point. We build the foundations into your agreed pages, with the depth of work defined by your package.",
      principles: [
        ["Start with a real question.", "Understand what your audience is looking for. Clear service descriptions and useful answers connect their questions to your business."],
        ["Make the page easy to understand.", "Descriptive titles, headings and links give readers a clear route through your content. Relevant local information helps explain where you work."],
        ["Give search engines a clear route.", "Review crawlability, page information and the mobile experience. Search tools help us spot issues and decide what to improve next."],
      ],
      deliverables: ["Descriptive page titles and clear URLs", "Meta descriptions for the agreed pages", "A meaningful heading hierarchy and internal links", "Relevant structured data where included and appropriate", "Useful image descriptions and considered file names", "Sitemap and robots settings checked for launch", "Search Console and Analytics setup in Growth; Pro setup confirmed in your proposal", "Mobile experience and Core Web Vitals reviewed within scope", "Accurate service and location information for the areas you actually serve"],
      faqs: [
        { q: "Can you guarantee a position on Google?", a: "No. Search engines decide what to index and how to rank it. Changes take time and results depend on your content, competition and other factors. We focus on clear foundations and useful improvements." },
        { q: "What does my package include?", a: "Launch includes SEO foundations, Growth adds Search Console and Analytics setup, and Pro provides a fuller SEO structure. We confirm the exact setup in your proposal. Ongoing SEO campaigns, content production and link building are scoped separately; they are not automatically included in a care plan." },
        { q: "Will my search result look exactly like this example?", a: "The visual is an illustration. Google can choose different titles and snippets, and structured data does not guarantee an enhanced result. Submitting a sitemap also does not guarantee indexing." },
      ],
    },
    security: {
      name: "Security & Website Care", title: ["Care behind", "every visit."], lead: "A considered setup. Ongoing attention. A clear plan for the moments that need it.",
      intro: "A website needs care beyond launch. We combine a considered hosting setup with the monitoring, backups and support included in your active care plan.",
      principles: [
        ["Protect the connection.", "HTTPS encrypts information as it travels between the visitor and the website. It is one important layer of security, alongside careful configuration and access management."],
        ["Keep giving the site attention.", "Managed hosting, uptime checks and maintenance help identify issues. The tools and response arrangements depend on the site and your care agreement."],
        ["Prepare a way back.", "Backups need a clear scope and recovery approach. We confirm what is covered, how copies are retained and the practical steps for restoring your site."],
      ],
      deliverables: ["HTTPS certificate setup for the managed site", "Managed hosting within your active care plan", "Backup scope, schedule and retention agreed for your website", "Uptime monitoring and a clear route to report issues", "Relevant security headers and access settings reviewed", "Dependency updates and maintenance within the agreed setup", "Consent controls and placement of your approved privacy content where scoped", "Bug fixing and support within your care plan’s terms"],
      faqs: [
        { q: "Does HTTPS mean a website is completely secure?", a: "HTTPS protects the connection. It does not guarantee that a website is free from vulnerabilities. Security also depends on access, configuration, software and ongoing care. We do not promise uninterrupted uptime or absolute protection." },
        { q: "What happens if something goes wrong?", a: "Contact us through your care support channel. We assess the issue and the available recovery options. Backups and bug fixing are included in Basic Care; Complete Care adds priority WhatsApp support. Recovery depends on the incident and the available copies, without a universal recovery-time promise." },
        { q: "Do you provide privacy compliance?", a: "We can implement agreed consent controls and publish your approved privacy information. Those features alone do not establish legal compliance. Your policies and data practices need to suit your business, with specialist advice where needed." },
      ],
    },
    turnaround: {
      name: "Website Delivery", title: ["A clear plan.", "A confident launch."], lead: "See what happens next, give feedback at the right moments and launch when the details are ready.",
      intro: "A smooth project starts with the right materials and a shared plan. We agree the scope, set review points and keep you involved from the first direction to your launch approval.",
      principles: [
        ["Get ready together.", "Gather your content, branding and images, and arrange the access the project needs. We confirm the schedule once payment and the required materials are in place."],
        ["See the work take shape.", "Explore a working preview and bring your feedback together. Your package includes a defined number of revision rounds so the next step stays clear."],
        ["Launch with a final check.", "Review the agreed pages, links and enquiries before approving publication. Domain setup and the handover follow the launch plan we agree with you."],
      ],
      deliverables: ["A kickoff and schedule agreed around content readiness", "A working preview to review before launch", "2 revision rounds for Launch, 3 for Growth and 4 for Pro", "Indicative delivery: Launch 5–7 and Growth 7–10 business days; Pro confirmed per project", "Domain and DNS connection within the agreed scope", "30-day bug fixing for faults in our work, subject to the service terms", "WhatsApp coordination and ongoing support through your care plan"],
      faqs: [
        { q: "How long will my website take?", a: "Launch is typically 5–7 business days and Growth 7–10, once payment and required materials are ready. Pro is scheduled per project; the 10–14 day planning guide on our process page is indicative, with the proposal confirming your timing. Extra scope and delayed materials or feedback can move the schedule." },
        { q: "What do you need from me?", a: "Your logo and brand guidelines, page content, images you have permission to use, and the necessary account access. Use account invitations or delegated access where available. We confirm missing materials and any content support before setting the schedule." },
        { q: "Can you work to an urgent deadline?", a: "Tell us the date and what needs to be ready. We will check availability and scope before confirming whether an accelerated schedule is possible, with any additional cost agreed first." },
        { q: "What happens after launch?", a: "Faults in work we built are covered for 30 days after launch under the service terms, and while you hold an active care plan. Hosting, ongoing support and eligible updates follow your care plan. New pages, features and other additional work are quoted separately." },
      ],
    },
  },
  el: {
    seo: {
      name: "Βάσεις SEO", title: ["Πιο ξεκάθαρα.", "Πιο εύκολα να σας βρουν."], lead: "Βοηθήστε το σωστό κοινό να καταλάβει τι προσφέρετε, από την πρώτη αναζήτηση μέχρι την επικοινωνία μαζί σας.",
      intro: "Χρήσιμο περιεχόμενο και σωστή οργάνωση δίνουν στην αναζήτηση μια καλύτερη αφετηρία. Χτίζουμε τις βάσεις στις συμφωνημένες σελίδες, με βάθος εργασίας ανάλογο του πακέτου σας.",
      principles: [["Ξεκινάμε από μια πραγματική ερώτηση.", "Κατανοούμε τι αναζητά το κοινό σας. Σαφείς περιγραφές υπηρεσιών και χρήσιμες απαντήσεις συνδέουν τις ανάγκες του με την επιχείρησή σας."], ["Κάνουμε τη σελίδα κατανοητή.", "Περιγραφικοί τίτλοι, επικεφαλίδες και σύνδεσμοι καθοδηγούν τον αναγνώστη. Οι σχετικές τοπικές πληροφορίες εξηγούν πού δραστηριοποιείστε."], ["Δίνουμε στην αναζήτηση καθαρή δομή.", "Ελέγχουμε την πρόσβαση των μηχανών αναζήτησης, τις πληροφορίες σελίδας και την εμπειρία στο κινητό. Τα εργαλεία αναζήτησης βοηθούν να εντοπίσουμε θέματα και επόμενες βελτιώσεις."]],
      deliverables: ["Περιγραφικοί τίτλοι σελίδων και καθαρά URL", "Meta descriptions για τις συμφωνημένες σελίδες", "Λογική ιεραρχία επικεφαλίδων και εσωτερικοί σύνδεσμοι", "Σχετικά δομημένα δεδομένα, όπου περιλαμβάνονται και είναι κατάλληλα", "Χρήσιμες περιγραφές εικόνων και προσεγμένα ονόματα αρχείων", "Έλεγχος sitemap και ρυθμίσεων robots πριν τη δημοσίευση", "Search Console και Analytics στο Growth· η ρύθμιση του Pro επιβεβαιώνεται στην προσφορά", "Έλεγχος εμπειρίας στο κινητό και Core Web Vitals εντός του εύρους εργασίας", "Ακριβείς πληροφορίες για υπηρεσίες και περιοχές που εξυπηρετείτε"],
      faqs: [{ q: "Εγγυάστε θέση στη Google;", a: "Όχι. Οι μηχανές αναζήτησης αποφασίζουν τι ευρετηριάζουν και πώς το κατατάσσουν. Οι αλλαγές χρειάζονται χρόνο και τα αποτελέσματα εξαρτώνται από το περιεχόμενο, τον ανταγωνισμό και άλλους παράγοντες. Εστιάζουμε σε σωστές βάσεις και χρήσιμες βελτιώσεις." }, { q: "Τι περιλαμβάνει το πακέτο μου;", a: "Το Launch περιλαμβάνει βάσεις SEO, το Growth προσθέτει Search Console και Analytics και το Pro πιο πλήρη δομή SEO. Η ακριβής ρύθμιση επιβεβαιώνεται στην προσφορά. Συνεχείς καμπάνιες SEO, παραγωγή περιεχομένου και δημιουργία συνδέσμων συμφωνούνται ξεχωριστά· δεν περιλαμβάνονται αυτόματα σε πλάνο φροντίδας." }, { q: "Το αποτέλεσμα αναζήτησης θα μοιάζει ακριβώς με το παράδειγμα;", a: "Η σύνθεση είναι ενδεικτική. Η Google μπορεί να επιλέξει διαφορετικούς τίτλους και αποσπάσματα, ενώ τα δομημένα δεδομένα δεν εγγυώνται εμπλουτισμένο αποτέλεσμα. Ούτε η υποβολή sitemap εγγυάται ευρετηρίαση." }],
    },
    security: {
      name: "Ασφάλεια & Φροντίδα", title: ["Φροντίδα πίσω", "από κάθε επίσκεψη."], lead: "Προσεγμένη αρχική ρύθμιση. Συνεχής προσοχή. Ένα σαφές πλάνο όταν χρειάζεται.",
      intro: "Η ιστοσελίδα χρειάζεται φροντίδα και μετά τη δημοσίευση. Συνδυάζουμε προσεγμένη φιλοξενία με την παρακολούθηση, τα αντίγραφα ασφαλείας και την υποστήριξη του ενεργού πλάνου σας.",
      principles: [["Προστατεύουμε τη σύνδεση.", "Το HTTPS κρυπτογραφεί τις πληροφορίες κατά τη μεταφορά ανάμεσα στον επισκέπτη και την ιστοσελίδα. Είναι ένα σημαντικό επίπεδο ασφάλειας, μαζί με σωστές ρυθμίσεις και διαχείριση πρόσβασης."], ["Συνεχίζουμε να προσέχουμε το site.", "Η διαχειριζόμενη φιλοξενία, οι έλεγχοι διαθεσιμότητας και η συντήρηση βοηθούν στον εντοπισμό προβλημάτων. Εργαλεία και όροι ανταπόκρισης εξαρτώνται από το site και τη συμφωνία φροντίδας."], ["Προετοιμάζουμε την επαναφορά.", "Τα αντίγραφα ασφαλείας χρειάζονται σαφές εύρος και τρόπο επαναφοράς. Συμφωνούμε τι καλύπτεται, πόσο διατηρούνται τα αντίγραφα και τα πρακτικά βήματα ανάκτησης."]],
      deliverables: ["Ρύθμιση πιστοποιητικού HTTPS για το διαχειριζόμενο site", "Διαχειριζόμενη φιλοξενία με ενεργό πλάνο φροντίδας", "Συμφωνημένο εύρος, συχνότητα και διατήρηση αντιγράφων ασφαλείας", "Παρακολούθηση διαθεσιμότητας και σαφής τρόπος αναφοράς προβλημάτων", "Έλεγχος σχετικών κεφαλίδων ασφαλείας και ρυθμίσεων πρόσβασης", "Ενημερώσεις εξαρτήσεων και συντήρηση εντός της συμφωνημένης υποδομής", "Μηχανισμοί συγκατάθεσης και εγκεκριμένο περιεχόμενο απορρήτου, όπου έχει συμφωνηθεί", "Διόρθωση σφαλμάτων και υποστήριξη σύμφωνα με το πλάνο σας"],
      faqs: [{ q: "Το HTTPS σημαίνει απόλυτη ασφάλεια;", a: "Το HTTPS προστατεύει τη σύνδεση. Δεν εγγυάται ότι το site δεν έχει ευπάθειες. Η ασφάλεια εξαρτάται επίσης από πρόσβαση, ρυθμίσεις, λογισμικό και συνεχή φροντίδα. Δεν υποσχόμαστε αδιάλειπτη διαθεσιμότητα ή απόλυτη προστασία." }, { q: "Τι γίνεται αν προκύψει πρόβλημα;", a: "Επικοινωνήστε μέσω του καναλιού υποστήριξης του πλάνου σας. Αξιολογούμε το θέμα και τις διαθέσιμες επιλογές ανάκτησης. Το Basic Care περιλαμβάνει αντίγραφα ασφαλείας και διόρθωση σφαλμάτων· το Complete Care προσθέτει προτεραιότητα στο WhatsApp. Η επαναφορά εξαρτάται από το περιστατικό και τα διαθέσιμα αντίγραφα, χωρίς ενιαία υπόσχεση χρόνου." }, { q: "Παρέχετε συμμόρφωση απορρήτου;", a: "Υλοποιούμε συμφωνημένους μηχανισμούς συγκατάθεσης και δημοσιεύουμε εγκεκριμένες πληροφορίες απορρήτου. Αυτά από μόνα τους δεν εξασφαλίζουν νομική συμμόρφωση. Οι πολιτικές και πρακτικές δεδομένων πρέπει να ταιριάζουν στην επιχείρησή σας, με συμβουλή ειδικού όπου χρειάζεται." }],
    },
    turnaround: {
      name: "Παράδοση Ιστοσελίδας", title: ["Ξεκάθαρο πλάνο.", "Σίγουρο ξεκίνημα."], lead: "Ξέρετε τι ακολουθεί, δίνετε σχόλια την κατάλληλη στιγμή και δημοσιεύετε όταν όλα είναι έτοιμα.",
      intro: "Η ομαλή συνεργασία ξεκινά με τα σωστά υλικά και ένα κοινό πλάνο. Συμφωνούμε το εύρος, ορίζουμε σημεία ελέγχου και σας κρατάμε μέσα στη διαδικασία μέχρι την έγκριση δημοσίευσης.",
      principles: [["Ετοιμαζόμαστε μαζί.", "Συγκεντρώνουμε περιεχόμενο, branding και εικόνες και οργανώνουμε την απαραίτητη πρόσβαση. Επιβεβαιώνουμε το πρόγραμμα όταν έχουν ολοκληρωθεί η πληρωμή και τα απαιτούμενα υλικά."], ["Βλέπετε τη δουλειά να προχωρά.", "Εξερευνάτε λειτουργική προεπισκόπηση και συγκεντρώνετε τα σχόλιά σας. Το πακέτο περιλαμβάνει συγκεκριμένους γύρους αναθεωρήσεων, ώστε το επόμενο βήμα να παραμένει σαφές."], ["Δημοσιεύουμε με τελικό έλεγχο.", "Ελέγχουμε τις συμφωνημένες σελίδες, συνδέσμους και φόρμες πριν εγκρίνετε τη δημοσίευση. Η σύνδεση domain και η παράδοση ακολουθούν το κοινό πλάνο."]],
      deliverables: ["Έναρξη και πρόγραμμα με βάση την ετοιμότητα του περιεχομένου", "Λειτουργική προεπισκόπηση πριν τη δημοσίευση", "2 γύροι αναθεωρήσεων στο Launch, 3 στο Growth και 4 στο Pro", "Ενδεικτικά: Launch 5–7 και Growth 7–10 εργάσιμες ημέρες· Pro ανά έργο", "Σύνδεση domain και DNS εντός του συμφωνημένου εύρους", "Διόρθωση σφαλμάτων της δουλειάς μας για 30 ημέρες, βάσει των όρων υπηρεσίας", "Συνεννόηση μέσω WhatsApp και συνεχιζόμενη υποστήριξη με πλάνο φροντίδας"],
      faqs: [{ q: "Πόσο χρόνο χρειάζεται η ιστοσελίδα μου;", a: "Το Launch συνήθως χρειάζεται 5–7 εργάσιμες ημέρες και το Growth 7–10, αφού είναι έτοιμα η πληρωμή και τα απαιτούμενα υλικά. Το Pro προγραμματίζεται ανά έργο· οι 10–14 ημέρες στη σελίδα διαδικασίας είναι ενδεικτικές και η προσφορά επιβεβαιώνει τον χρόνο. Επιπλέον εργασίες ή καθυστερημένα υλικά και σχόλια μετακινούν το πρόγραμμα." }, { q: "Τι χρειάζεστε από εμένα;", a: "Λογότυπο και οδηγίες brand, κείμενα, εικόνες με δικαίωμα χρήσης και την αναγκαία πρόσβαση. Προτιμήστε προσκλήσεις λογαριασμού ή ανάθεση πρόσβασης όπου διατίθενται. Επιβεβαιώνουμε τυχόν ελλείψεις και υποστήριξη περιεχομένου πριν ορίσουμε το πρόγραμμα." }, { q: "Μπορείτε να καλύψετε μια επείγουσα προθεσμία;", a: "Πείτε μας την ημερομηνία και τι χρειάζεται να είναι έτοιμο. Ελέγχουμε διαθεσιμότητα και εύρος πριν επιβεβαιώσουμε ταχύτερη παράδοση, με τυχόν επιπλέον κόστος συμφωνημένο εκ των προτέρων." }, { q: "Τι γίνεται μετά τη δημοσίευση;", a: "Σφάλματα σε δική μας εργασία καλύπτονται για 30 ημέρες μετά τη δημοσίευση βάσει των όρων υπηρεσίας και όσο έχετε ενεργό πλάνο φροντίδας. Φιλοξενία, υποστήριξη και επιλέξιμες ενημερώσεις ακολουθούν το πλάνο σας. Νέες σελίδες, λειτουργίες και πρόσθετες εργασίες κοστολογούνται ξεχωριστά." }],
    },
  },
  he: {
    seo: {
      name: "יסודות SEO", title: ["דרך ברורה יותר", "למצוא אתכם."], lead: "עוזרים לאנשים הנכונים להבין מה אתם מציעים, מהחיפוש הראשון ועד לשיחה הבאה.",
      intro: "תוכן שימושי ואתר מאורגן נותנים לחיפוש נקודת פתיחה טובה יותר. בונים את היסודות בעמודים שסוכמו, עם עומק עבודה בהתאם לחבילה שלכם.",
      principles: [["מתחילים משאלה אמיתית.", "מבינים מה הקהל שלכם מחפש. תיאורי שירות ברורים ותשובות מועילות מחברים בין הצרכים שלו לעסק שלכם."], ["עוזרים להבין את העמוד.", "כותרות תיאוריות וקישורים ברורים מובילים את הקוראים דרך התוכן. מידע מקומי רלוונטי מסביר היכן אתם פועלים."], ["נותנים לחיפוש מסלול ברור.", "בודקים נגישות לסריקה, מידע על העמוד וחוויית מובייל. כלי חיפוש עוזרים לזהות בעיות ולהחליט מה לשפר בהמשך."]],
      deliverables: ["כותרות עמוד תיאוריות וכתובות ברורות", "תיאורי מטא לעמודים שסוכמו", "היררכיית כותרות הגיונית וקישורים פנימיים", "נתונים מובנים רלוונטיים, כשכלולים ומתאימים", "תיאורי תמונות מועילים ושמות קבצים מתאימים", "בדיקת מפת אתר והגדרות robots לקראת ההשקה", "Search Console ו-Analytics בחבילת Growth; ההגדרה ב-Pro מאושרת בהצעה", "בדיקת חוויית מובייל ו-Core Web Vitals במסגרת ההיקף", "מידע מדויק על השירותים והאזורים שאתם באמת משרתים"],
      faqs: [{ q: "אפשר להבטיח מיקום בגוגל?", a: "לא. מנועי החיפוש מחליטים מה להוסיף לאינדקס ואיך לדרג אותו. שינויים לוקחים זמן והתוצאות תלויות בתוכן, בתחרות ובגורמים נוספים. אנחנו מתמקדים ביסודות ברורים ובשיפורים מועילים." }, { q: "מה כלול בחבילה שלי?", a: "Launch כוללת יסודות SEO, חבילת Growth מוסיפה Search Console ו-Analytics, וחבילת Pro כוללת מבנה SEO רחב יותר. ההגדרה המדויקת מאושרת בהצעה. קמפיינים מתמשכים של SEO, יצירת תוכן ובניית קישורים מתומחרים בנפרד ואינם כלולים אוטומטית בחבילת תחזוקה." }, { q: "תוצאת החיפוש תיראה בדיוק כמו בדוגמה?", a: "העיצוב הוא המחשה. גוגל עשויה לבחור כותרות ותיאורים אחרים, ונתונים מובנים אינם מבטיחים תוצאה עשירה. גם הגשת מפת אתר אינה מבטיחה אינדוקס." }],
    },
    security: {
      name: "אבטחה ותחזוקת אתר", title: ["תשומת לב", "מאחורי כל ביקור."], lead: "הקמה מחושבת. טיפול שוטף. תוכנית ברורה לרגעים שצריכים אותה.",
      intro: "אתר זקוק לטיפול גם אחרי ההשקה. משלבים סביבת אירוח מתאימה עם הניטור, הגיבויים והתמיכה שכלולים בחבילת התחזוקה הפעילה שלכם.",
      principles: [["מגינים על החיבור.", "HTTPS מצפין מידע בזמן המעבר בין המבקרים לאתר. זו שכבת אבטחה חשובה, לצד הגדרות מתאימות וניהול הרשאות גישה."], ["ממשיכים לשים לב לאתר.", "אירוח מנוהל, בדיקות זמינות ותחזוקה עוזרים לזהות בעיות. הכלים ואופן המענה תלויים באתר ובהסכם התחזוקה."], ["מתכוננים לשחזור.", "גיבויים צריכים היקף ברור ודרך לשחזור. מאשרים מה מכוסה, כמה זמן נשמרים העותקים ומהם הצעדים להחזרת האתר."]],
      deliverables: ["הגדרת תעודת HTTPS לאתר המנוהל", "אירוח מנוהל במסגרת חבילת תחזוקה פעילה", "היקף, תדירות ומשך שמירת גיבויים שסוכמו לאתר", "ניטור זמינות ודרך ברורה לדיווח על תקלות", "בדיקת כותרות אבטחה והגדרות גישה רלוונטיות", "עדכוני רכיבי תוכנה ותחזוקה במסגרת התשתית שסוכמה", "מנגנוני הסכמה ושילוב תוכן פרטיות מאושר, בהתאם להיקף", "תיקון תקלות ותמיכה לפי תנאי חבילת התחזוקה"],
      faqs: [{ q: "האם HTTPS אומר שהאתר בטוח לגמרי?", a: "HTTPS מגן על החיבור. הוא אינו מבטיח שהאתר נקי מחולשות. האבטחה תלויה גם בגישה, בהגדרות, בתוכנה ובטיפול שוטף. אין הבטחה לזמינות רציפה או להגנה מוחלטת." }, { q: "מה קורה אם יש תקלה?", a: "פנו דרך ערוץ התמיכה של חבילת התחזוקה. נבחן את התקלה ואת אפשרויות השחזור. Basic Care כוללת גיבויים ותיקון תקלות; Complete Care מוסיפה תמיכת WhatsApp בעדיפות. השחזור תלוי באירוע ובעותקים הזמינים, ללא הבטחת זמן אחידה." }, { q: "האם אתם מספקים עמידה בדרישות פרטיות?", a: "אפשר ליישם מנגנוני הסכמה שסוכמו ולפרסם מידע פרטיות שאישרתם. היכולות האלה לבדן אינן מבטיחות עמידה בדרישות החוק. המדיניות ואופן הטיפול במידע צריכים להתאים לעסק שלכם, עם ייעוץ מקצועי לפי הצורך." }],
    },
    turnaround: {
      name: "מסירת האתר", title: ["תוכנית ברורה.", "השקה בטוחה."], lead: "יודעים מה מגיע בהמשך, נותנים משוב בזמן הנכון ומשיקים כשהפרטים מוכנים.",
      intro: "פרויקט נעים מתחיל בחומרים הנכונים ובתוכנית משותפת. מסכימים על ההיקף, קובעים נקודות בדיקה ומשאירים אתכם מעורבים מהכיוון הראשון ועד לאישור ההשקה.",
      principles: [["מתכוננים יחד.", "אוספים תוכן, מיתוג ותמונות ומסדרים את הגישה הנדרשת. מאשרים את לוח הזמנים כשהתשלום והחומרים הדרושים מוכנים."], ["רואים את העבודה מתקדמת.", "נכנסים לתצוגה עובדת ומרכזים את המשוב. החבילה כוללת מספר מוגדר של סבבי תיקונים, כך שהצעד הבא נשאר ברור."], ["משיקים אחרי בדיקה אחרונה.", "עוברים על העמודים, הקישורים ואפשרויות הפנייה שסוכמו לפני אישור הפרסום. חיבור הדומיין והמסירה ממשיכים לפי תוכנית ההשקה המשותפת."]],
      deliverables: ["פגישת פתיחה ולוח זמנים בהתאם למוכנות התוכן", "תצוגה עובדת לבדיקה לפני ההשקה", "2 סבבי תיקונים ב-Launch, שלושה ב-Growth וארבעה ב-Pro", "זמן משוער: Launch ‏5–7 ו-Growth ‏7–10 ימי עבודה; Pro בהתאם לפרויקט", "חיבור דומיין ו-DNS במסגרת ההיקף שסוכם", "30 ימי תיקון תקלות בעבודה שביצענו, בכפוף לתנאי השירות", "תיאום ב-WhatsApp ותמיכה שוטפת דרך חבילת התחזוקה"],
      faqs: [{ q: "כמה זמן לוקח לבנות את האתר?", a: "Launch אורכת בדרך כלל 5–7 ימי עבודה ו-Growth ‏7–10, לאחר שהתשלום והחומרים הדרושים מוכנים. Pro מתוכננת לפי הפרויקט; טווח 10–14 הימים בעמוד התהליך הוא להמחשה, וההצעה מאשרת את הזמנים. תוספת היקף או עיכוב בחומרים ובמשוב יכולים להזיז את לוח הזמנים." }, { q: "מה צריך ממני?", a: "לוגו והנחיות מותג, תוכן לעמודים, תמונות שיש לכם הרשאה להשתמש בהן והגישה הדרושה לחשבונות. השתמשו בהזמנות לחשבון או בהרשאות גישה ייעודיות כשאפשר. מבררים חומרים חסרים ועזרה בתוכן לפני קביעת לוח הזמנים." }, { q: "אפשר לעמוד בדדליין דחוף?", a: "ספרו לנו מה התאריך ומה חייב להיות מוכן. נבדוק זמינות והיקף לפני שנאשר אם אפשר לקצר את הזמנים, עם סיכום מראש על כל עלות נוספת." }, { q: "מה קורה אחרי ההשקה?", a: "תקלות בעבודה שביצענו מכוסות ל-30 יום אחרי ההשקה לפי תנאי השירות, ובהמשך כל עוד יש חבילת תחזוקה פעילה. אירוח, תמיכה ועדכונים מתאימים ממשיכים לפי החבילה. עמודים, יכולות ועבודה נוספת מתומחרים בנפרד." }],
    },
  },
};
