import type { SiteLanguage } from "@/lib/routeLanguage";

export const SERVICE_UI = {
  en: {
    back: "All services", consultation: "Get a free consultation", pricing: "Explore packages & care", why: "The thinking behind it", whyTitle: "Made to work for your visitors.", deliver: "What we work on", deliverTitle: "The details make the difference.", scope: "Your package and agreed scope define the pages, features and revisions. We confirm these before starting, and quote additional work separately.", process: "From direction to delivery", processTitle: "A clear way forward.", processLink: "See the full process", questions: "Good questions.", related: "Bring it all together.", closing: "What would you like your website to do?", closingCopy: "Tell us about your business or ask us anything. We’ll help you find a sensible next step. Your first consultation is free, with no obligation.", study: "A visual direction, across the details", studyNote: "Brand concept · design study",
    demoTitle: "One message. Every screen.", demoNote: "An illustrative layout. Switch the view to see the same content adapt.", views: ["Phone", "Tablet", "Desktop"], demoLabel: "Your business", demoHeading: "A story worth sharing.", demoBody: "What you do. Why it matters.", demoAction: "Let’s talk", demoCaption: "The same story, on every screen.",
    experience: "How a good experience feels", metrics: [["Load", "Reach the main content."], ["Respond", "Act without unnecessary delay."], ["Stay steady", "Read without unexpected shifts."]], metricNote: "Loading, interaction and visual stability.",
  },
  el: {
    back: "Όλες οι υπηρεσίες", consultation: "Δωρεάν συμβουλευτική", pricing: "Πακέτα και φροντίδα", why: "Η σκέψη πίσω από τη δουλειά", whyTitle: "Για τους ανθρώπους που σας επισκέπτονται.", deliver: "Τι δουλεύουμε", deliverTitle: "Οι λεπτομέρειες κάνουν τη διαφορά.", scope: "Το πακέτο και το συμφωνημένο εύρος ορίζουν τις σελίδες, τις λειτουργίες και τις αναθεωρήσεις. Τα επιβεβαιώνουμε πριν ξεκινήσουμε και κοστολογούμε ξεχωριστά την επιπλέον εργασία.", process: "Από την κατεύθυνση στην παράδοση", processTitle: "Μια ξεκάθαρη πορεία.", processLink: "Δείτε όλη τη διαδικασία", questions: "Χρήσιμες ερωτήσεις.", related: "Όλα συνδέονται.", closing: "Τι θέλετε να πετύχει η ιστοσελίδα σας;", closingCopy: "Πείτε μας για την επιχείρησή σας ή ρωτήστε μας οτιδήποτε. Θα βρούμε μαζί ένα λογικό επόμενο βήμα. Η πρώτη συμβουλευτική είναι δωρεάν, χωρίς δέσμευση.", study: "Μια οπτική κατεύθυνση, σε κάθε λεπτομέρεια", studyNote: "Οπτική ταυτότητα · σχεδιαστική μελέτη",
    demoTitle: "Ένα μήνυμα. Κάθε οθόνη.", demoNote: "Ενδεικτική διάταξη: αλλάξτε προβολή και δείτε το ίδιο περιεχόμενο να προσαρμόζεται.", views: ["Κινητό", "Tablet", "Υπολογιστής"], demoLabel: "Η επιχείρησή σας", demoHeading: "Μια ιστορία που αξίζει.", demoBody: "Τι κάνετε. Γιατί έχει σημασία.", demoAction: "Ας μιλήσουμε", demoCaption: "Η ίδια ιστορία, σε κάθε οθόνη.",
    experience: "Πώς νιώθει μια καλή εμπειρία", metrics: [["Φόρτωση", "Πρόσβαση στο κύριο περιεχόμενο."], ["Απόκριση", "Ενέργειες χωρίς περιττή καθυστέρηση."], ["Σταθερότητα", "Ανάγνωση χωρίς απρόσμενες μετακινήσεις."]], metricNote: "Φόρτωση, αλληλεπίδραση και οπτική σταθερότητα.",
  },
  he: {
    back: "כל השירותים", consultation: "לשיחת ייעוץ בחינם", pricing: "לחבילות ולתחזוקה", why: "המחשבה מאחורי העבודה", whyTitle: "בשביל האנשים שמגיעים אליכם.", deliver: "על מה עובדים", deliverTitle: "הפרטים עושים את ההבדל.", scope: "החבילה וההיקף המוסכם מגדירים את העמודים, היכולות וסבבי התיקונים. מאשרים אותם לפני שמתחילים, ומתמחרים עבודה נוספת בנפרד.", process: "מהכיוון למסירה", processTitle: "דרך ברורה קדימה.", processLink: "לתהליך המלא", questions: "שאלות טובות.", related: "הכול מתחבר.", closing: "מה תרצו שהאתר שלכם יעשה?", closingCopy: "ספרו לנו על העסק או שאלו אותנו כל דבר. נעזור לכם למצוא צעד הבא הגיוני. שיחת הייעוץ הראשונה בחינם וללא התחייבות.", study: "כיוון ויזואלי שניכר בכל פרט", studyNote: "קונספט מותגי · המחשת עיצוב",
    demoTitle: "מסר אחד. בכל מסך.", demoNote: "פריסה להמחשה. בחרו תצוגה וראו איך אותו תוכן מתאים את עצמו.", views: ["טלפון", "טאבלט", "מחשב"], demoLabel: "העסק שלכם", demoHeading: "סיפור ששווה לשתף.", demoBody: "מה אתם עושים. למה זה חשוב.", demoAction: "בואו נדבר", demoCaption: "אותו סיפור, בכל מסך.",
    experience: "איך מרגישה חוויה טובה", metrics: [["טעינה", "מגיעים לתוכן המרכזי."], ["תגובה", "פועלים בלי עיכוב מיותר."] , ["יציבות", "קוראים בלי תזוזות מפתיעות."]], metricNote: "טעינה, תגובתיות ויציבות ויזואלית.",
  },
} satisfies Record<SiteLanguage, unknown>;
