import type { SiteLanguage } from "@/lib/routeLanguage";

export const FAQ_TOPICS = [
  { id: "getting-started", questions: ["start", "prepare", "timeline", "technical", "remote", "design", "extend"] },
  { id: "packages-payment", questions: ["price", "extra-costs", "payment", "methods", "ownership"] },
  { id: "features-seo", questions: ["examples", "mobile", "seo", "integrations", "hosting"] },
  { id: "website-care", questions: ["after-launch", "updates", "care-plans", "care-exclusions", "cancel"] },
] as const;
export type TopicId = typeof FAQ_TOPICS[number]["id"];
export type QuestionId = typeof FAQ_TOPICS[number]["questions"][number];
type Answer = { q: string; a: string; link?: { path: string; label: string } };

export const FAQ_CONTENT: Record<SiteLanguage, Record<QuestionId, Answer>> = {
  en: {
    start: { q: "How do we get started?", a: "Tell us about your business, your idea or the question on your mind. Use the contact form or WhatsApp for a free consultation. We’ll work out what you need and agree the next step together.", link: { path: "contact", label: "Get a free consultation" } },
    prepare: { q: "What should I have ready?", a: "A little about your business and what you want the website to achieve is enough for the first conversation. Share any logo, photos, text or examples you already have. Before work begins, we’ll confirm the content we need and who will provide it." },
    timeline: { q: "How long will my website take?", a: "The schedule depends on the number of pages, the features and how ready your content is. We agree a realistic timeline before starting. Content delivery, feedback and changes to the scope can affect the dates.", link: { path: "process", label: "See how the process works" } },
    technical: { q: "Do I need technical knowledge?", a: "No. We explain the decisions in plain language and handle the technical work. You bring your knowledge of the business and approve the direction and content." },
    remote: { q: "Can we work together remotely?", a: "Yes. We work with businesses worldwide through WhatsApp, email and video calls. We agree how we’ll communicate and review progress before the project starts." },
    design: { q: "Will I see the design before development?", a: "Yes. We share a design direction for your approval before development proceeds, then review progress at the agreed stages. Scope, revision rounds and payment arrangements are agreed before work begins." },
    extend: { q: "Can we add pages or features later?", a: "Yes. Your website can grow with your business. We’ll explain the work involved and quote for the additional scope before making changes." },
    price: { q: "How much does a website cost?", a: "The one-time build prices start at €299 for Launch Website, €749 for Growth Website and €1,499 for Pro Website. Enterprise / Custom is quoted to your scope. Hosting and care starts at €69 per month and is required while we host and manage your site. Prices exclude applicable taxes.", link: { path: "pricing", label: "Compare website and care plans" } },
    "extra-costs": { q: "What other costs should I allow for?", a: "We agree the scope and price before work starts. Domain registration, paid tools, licences and other third-party costs are agreed separately. New pages, extra revisions or additional features are quoted before we proceed." },
    payment: { q: "When do I pay?", a: "Website builds are paid in full before work begins. Larger projects may use staged payments by prior written agreement. Your invoice sets out the payment arrangement and the billing frequency for ongoing care.", link: { path: "terms", label: "Read the payment terms" } },
    methods: { q: "Which payment methods do you accept?", a: "Payment is by bank transfer against the invoice we send you. We’ll provide the payment details and confirm the agreed arrangement before the project starts." },
    ownership: { q: "Will the website belong to me?", a: "Once paid in full, you keep the website as delivered in its static form, your content and any add-ons purchased outright. Third-party licences and ongoing services have their own conditions. If a care plan ends, the plan’s services and dependent features may stop; the terms explain ownership and handover.", link: { path: "terms", label: "See ownership and handover details" } },
    examples: { q: "Can I see examples first?", a: "Yes. Explore our example websites to get a feel for different layouts and industries. They are demonstration projects to help you discuss a direction, rather than a promise that your website must follow a template.", link: { path: "templates", label: "Explore the example websites" } },
    mobile: { q: "Will my website work on phones?", a: "Yes. Every website package includes a responsive build for phones, tablets and desktop screens. We consider the reading order, navigation and touch controls as part of the design.", link: { path: "services/mobile-first", label: "More about mobile-first design" } },
    seo: { q: "Is SEO included?", a: "Every package includes basic SEO foundations. Pro Website includes a fuller SEO structure. Advanced or ongoing SEO, extra copywriting and wider content work are scoped separately. Search rankings are not guaranteed.", link: { path: "services/seo", label: "See the SEO foundations" } },
    integrations: { q: "Can you add bookings, a CRM, a chatbot or more languages?", a: "Yes. These are usually part of an Enterprise / Custom project. We’ll look at the platforms, content and integrations you need, then agree the scope and any third-party costs." },
    hosting: { q: "How do hosting and domains work?", a: "An active hosting and care plan is required while we host and manage your website. Basic Care starts at €69 per month. Domain registration and relevant third-party services are agreed separately; they are not automatically included in the build price.", link: { path: "pricing", label: "View hosting and care" } },
    "after-launch": { q: "What happens after launch?", a: "Your agreed hosting and care plan keeps the site supported after launch. We manage hosting, monitor availability and handle the maintenance covered by your plan. We’ll explain how to request an update and what is included." },
    updates: { q: "Can I change the content after launch?", a: "Yes. Send us the changes you need. Basic Care includes up to 3 small content updates each month. Complete Care includes content updates when you need them, such as text, images and links. Larger changes are quoted separately." },
    "care-plans": { q: "What is included in each care plan?", a: "Basic Care is €69 per month: managed hosting, uptime monitoring, website assets and database management where applicable, backups, bug fixing, WhatsApp support and up to 3 small content updates monthly. Complete Care is €129 per month and adds content updates when you need them, priority WhatsApp support, a monthly performance check and one simple banner or section update per month. Yearly billing is also available.", link: { path: "pricing", label: "Compare the care plans" } },
    "care-exclusions": { q: "What is outside the care-plan scope?", a: "New pages, copywriting, extra revision rounds, new integrations, redesigns, advanced SEO and complex content migration are quoted separately. We agree the additional work and cost with you before going ahead." },
    cancel: { q: "Can I change or cancel my care plan?", a: "Contact us to discuss a change. Cancellation requires 30 days’ written notice, and the end date depends on your billing period. Prepayments, plan-dependent features and handover are covered in the terms. We’ll clarify what applies to your plan before making the change.", link: { path: "terms", label: "Read the care-plan terms" } },
  },
  el: {
    start: { q: "Πώς ξεκινάμε;", a: "Πείτε μας για την επιχείρηση, την ιδέα ή την απορία σας, μέσω της φόρμας ή στο WhatsApp. Η πρώτη κουβέντα είναι δωρεάν: βλέπουμε τι χρειάζεστε και συμφωνούμε μαζί το επόμενο βήμα.", link: { path: "contact", label: "Ζητήστε δωρεάν συμβουλευτική" } },
    prepare: { q: "Τι χρειάζεται να έχω έτοιμο;", a: "Για την πρώτη κουβέντα αρκούν λίγα λόγια για την επιχείρησή σας και για το τι θέλετε να κάνει η ιστοσελίδα. Αν έχετε ήδη λογότυπο, φωτογραφίες, κείμενα ή παραδείγματα που σας αρέσουν, στείλτε τα. Πριν ξεκινήσουμε, συμφωνούμε τι περιεχόμενο χρειάζεται και ποιος θα το φέρει." },
    timeline: { q: "Σε πόσο καιρό θα είναι έτοιμη η ιστοσελίδα μου;", a: "Εξαρτάται από τις σελίδες, τις λειτουργίες και από το πότε θα είναι έτοιμο το υλικό σας. Πριν ξεκινήσουμε, κλείνουμε μαζί ένα ρεαλιστικό χρονοδιάγραμμα. Οι ημερομηνίες μπορεί να μετακινηθούν αν αργήσει το υλικό ή τα σχόλιά σας, ή αν αλλάξει αυτό που φτιάχνουμε.", link: { path: "process", label: "Δείτε τη διαδικασία" } },
    technical: { q: "Χρειάζομαι τεχνικές γνώσεις;", a: "Καθόλου. Σας εξηγούμε τα πάντα με απλά λόγια και αναλαμβάνουμε όλη την τεχνική δουλειά. Εσείς ξέρετε την επιχείρησή σας καλύτερα από τον καθένα, οπότε εσείς εγκρίνετε την κατεύθυνση και το περιεχόμενο." },
    remote: { q: "Μπορούμε να συνεργαστούμε χωρίς να συναντηθούμε από κοντά;", a: "Φυσικά. Δουλεύουμε με επιχειρήσεις σε όλο τον κόσμο μέσω WhatsApp, email και βιντεοκλήσεων. Πριν ξεκινήσουμε, συμφωνούμε πώς θα τα λέμε και πώς θα βλέπετε την πρόοδο." },
    design: { q: "Θα δω τον σχεδιασμό πριν αρχίσετε να χτίζετε την ιστοσελίδα;", a: "Ναι. Σας δείχνουμε την κατεύθυνση του σχεδιασμού για έγκριση πριν προχωρήσουμε στην κατασκευή, και βλέπουμε μαζί την πρόοδο στα στάδια που έχουμε συμφωνήσει. Τι θα φτιάξουμε, πόσοι γύροι διορθώσεων περιλαμβάνονται και πώς θα γίνει η πληρωμή, τα συμφωνούμε πριν πιάσουμε δουλειά." },
    extend: { q: "Μπορούμε να προσθέσουμε σελίδες ή λειτουργίες αργότερα;", a: "Ναι, η ιστοσελίδα μεγαλώνει μαζί με την επιχείρησή σας. Σας εξηγούμε τι δουλειά χρειάζεται και σας δίνουμε προσφορά για τα έξτρα πριν αλλάξουμε οτιδήποτε." },
    price: { q: "Πόσο κοστίζει μια ιστοσελίδα;", a: "Η κατασκευή πληρώνεται μία φορά, με τιμές από €299 για το Launch Website, €749 για το Growth Website και €1,499 για το Pro Website. Για το Enterprise / Custom δίνουμε προσφορά ανάλογα με το έργο. Η φιλοξενία και συντήρηση ξεκινά από €69 τον μήνα και χρειάζεται όσο φιλοξενούμε και διαχειριζόμαστε την ιστοσελίδα. Οι τιμές δεν περιλαμβάνουν τυχόν φόρους.", link: { path: "pricing", label: "Συγκρίνετε πακέτα και συντήρηση" } },
    "extra-costs": { q: "Υπάρχουν άλλα κόστη που πρέπει να υπολογίσω;", a: "Χωρίς εκπλήξεις: τι θα φτιάξουμε και πόσο κοστίζει, τα συμφωνούμε πριν ξεκινήσει η δουλειά. Το domain, εργαλεία επί πληρωμή, άδειες χρήσης και άλλες υπηρεσίες τρίτων συμφωνούνται ξεχωριστά. Αν θελήσετε νέες σελίδες, επιπλέον διορθώσεις ή λειτουργίες, σας λέμε το κόστος πριν προχωρήσουμε." },
    payment: { q: "Πότε πληρώνω;", a: "Η κατασκευή εξοφλείται πριν ξεκινήσει η δουλειά. Σε μεγαλύτερα έργα μπορούμε να συμφωνήσουμε πληρωμή σε στάδια, γραπτώς και από πριν. Στο τιμολόγιο αναγράφονται οι όροι πληρωμής και κάθε πότε χρεώνεται η συντήρηση.", link: { path: "terms", label: "Διαβάστε τους όρους πληρωμής" } },
    methods: { q: "Ποιους τρόπους πληρωμής δέχεστε;", a: "Με τραπεζική μεταφορά, με βάση το τιμολόγιο που σας στέλνουμε. Σας δίνουμε τα στοιχεία πληρωμής και επιβεβαιώνουμε τη συμφωνία πριν ξεκινήσει το έργο." },
    ownership: { q: "Η ιστοσελίδα θα είναι δική μου;", a: "Ναι. Μόλις εξοφληθεί πλήρως, κρατάτε την ιστοσελίδα όπως παραδόθηκε, στη στατική της μορφή, μαζί με το περιεχόμενό σας και όσα πρόσθετα αγοράσατε οριστικά. Οι άδειες τρίτων και οι συνεχείς υπηρεσίες έχουν τους δικούς τους όρους. Αν λήξει ένα πακέτο συντήρησης, μπορεί να σταματήσουν οι υπηρεσίες και οι λειτουργίες που εξαρτώνται από αυτό. Όλα για την ιδιοκτησία και την παράδοση αρχείων θα τα βρείτε στους όρους.", link: { path: "terms", label: "Δείτε τους όρους ιδιοκτησίας και παράδοσης" } },
    examples: { q: "Μπορώ να δω παραδείγματα πρώτα;", a: "Φυσικά. Ρίξτε μια ματιά στις ενδεικτικές ιστοσελίδες μας για διαφορετικούς κλάδους και στυλ. Είναι δείγματα που μας βοηθούν να συζητήσουμε μια κατεύθυνση, όχι έτοιμα πρότυπα: η δική σας θα φτιαχτεί από το μηδέν.", link: { path: "templates", label: "Δείτε τα παραδείγματα" } },
    mobile: { q: "Η ιστοσελίδα μου θα δουλεύει σωστά στο κινητό;", a: "Ναι, σε κάθε πακέτο. Η ιστοσελίδα προσαρμόζεται σε κινητά, tablet και υπολογιστές, και από την αρχή σχεδιάζουμε πώς θα διαβάζεται και πώς θα πατιούνται τα κουμπιά με το δάχτυλο.", link: { path: "services/mobile-first", label: "Περισσότερα για την προσαρμογή σε κινητά" } },
    seo: { q: "Περιλαμβάνεται SEO;", a: "Ναι, κάθε πακέτο έχει τις βάσεις για το SEO, και το Pro Website ακόμα πληρέστερη δομή. Προχωρημένο ή συνεχές SEO, επιπλέον κείμενα και περισσότερο περιεχόμενο συμφωνούνται ξεχωριστά. Και για να είμαστε ειλικρινείς: κανείς δεν μπορεί να εγγυηθεί θέση στο Google, ούτε κι εμείς.", link: { path: "services/seo", label: "Δείτε τις βάσεις SEO" } },
    integrations: { q: "Μπορείτε να προσθέσετε κρατήσεις, CRM, chatbot ή γλώσσες;", a: "Ναι. Συνήθως αυτά ανήκουν σε ένα έργο Enterprise / Custom. Βλέπουμε μαζί ποιες πλατφόρμες, ποιο περιεχόμενο και ποιες συνδέσεις χρειάζεστε, και συμφωνούμε τι θα γίνει και τυχόν κόστη τρίτων." },
    hosting: { q: "Πώς δουλεύουν η φιλοξενία και το domain;", a: "Όσο φιλοξενούμε και διαχειριζόμαστε την ιστοσελίδα σας, χρειάζεται ενεργό πακέτο φιλοξενίας και συντήρησης. Το Basic Care ξεκινά από €69 τον μήνα. Η καταχώρηση του domain και οι σχετικές υπηρεσίες τρίτων συμφωνούνται ξεχωριστά και δεν περιλαμβάνονται αυτόματα στην τιμή κατασκευής.", link: { path: "pricing", label: "Δείτε τη φιλοξενία και συντήρηση" } },
    "after-launch": { q: "Τι γίνεται μετά τη δημοσίευση;", a: "Δεν σας αφήνουμε μόνους. Το πακέτο φιλοξενίας και συντήρησης που έχουμε συμφωνήσει κρατάει την ιστοσελίδα σε καλά χέρια: διαχειριζόμαστε τη φιλοξενία, προσέχουμε να είναι πάντα online και κάνουμε τη συντήρηση που καλύπτει το πακέτο σας. Σας εξηγούμε επίσης πώς ζητάτε αλλαγές και τι περιλαμβάνεται." },
    updates: { q: "Μπορώ να αλλάξω το περιεχόμενο μετά τη δημοσίευση;", a: "Ναι, απλώς στείλτε μας τι θέλετε να αλλάξει. Το Basic Care περιλαμβάνει έως 3 μικρές ενημερώσεις περιεχομένου τον μήνα, ενώ το Complete Care περιλαμβάνει ενημερώσεις όποτε τις χρειάζεστε, όπως κείμενα, εικόνες και συνδέσμους. Μεγαλύτερες αλλαγές χρεώνονται ξεχωριστά." },
    "care-plans": { q: "Τι περιλαμβάνει κάθε πακέτο συντήρησης;", a: "Το Basic Care κοστίζει €69 τον μήνα: διαχειριζόμενη φιλοξενία, παρακολούθηση διαθεσιμότητας, διαχείριση αρχείων και βάσης δεδομένων όπου υπάρχει, αντίγραφα ασφαλείας, διορθώσεις σφαλμάτων, υποστήριξη στο WhatsApp και έως 3 μικρές ενημερώσεις περιεχομένου τον μήνα. Το Complete Care κοστίζει €129 τον μήνα και προσθέτει ενημερώσεις περιεχομένου όποτε τις χρειάζεστε, υποστήριξη στο WhatsApp με προτεραιότητα, μηνιαίο έλεγχο απόδοσης και μία απλή ενημέρωση banner ή ενότητας τον μήνα. Μπορείτε να πληρώνετε και ετήσια.", link: { path: "pricing", label: "Συγκρίνετε τα πακέτα συντήρησης" } },
    "care-exclusions": { q: "Τι δεν καλύπτει η συντήρηση;", a: "Νέες σελίδες, συγγραφή κειμένων, επιπλέον γύροι διορθώσεων, νέες συνδέσεις υπηρεσιών, επανασχεδιασμός, προχωρημένο SEO και σύνθετη μεταφορά περιεχομένου χρεώνονται ξεχωριστά. Πριν κάνουμε οτιδήποτε έξτρα, συμφωνούμε μαζί σας τη δουλειά και το κόστος." },
    cancel: { q: "Μπορώ να αλλάξω ή να ακυρώσω το πακέτο μου;", a: "Ναι, πείτε μας τι θέλετε να αλλάξει και το συζητάμε. Για ακύρωση χρειάζεται γραπτή ειδοποίηση 30 ημερών, και η ημερομηνία λήξης εξαρτάται από την περίοδο χρέωσης. Για προπληρωμές, λειτουργίες που εξαρτώνται από το πακέτο και παράδοση αρχείων ισχύουν οι όροι, και πριν από κάθε αλλαγή σας εξηγούμε τι ισχύει για το δικό σας πακέτο.", link: { path: "terms", label: "Διαβάστε τους όρους συντήρησης" } },
  },
  he: {
    start: { q: "איך מתחילים?", a: "פשוט ספרו לנו על העסק, על הרעיון או על השאלה שמעסיקה אתכם, בטופס או ב-WhatsApp. שיחת הייעוץ הראשונה בחינם: נבין מה אתם צריכים ונסכם יחד את הצעד הבא.", link: { path: "contact", label: "לשיחת ייעוץ בחינם" } },
    prepare: { q: "מה כדאי להכין מראש?", a: "לשיחה הראשונה לא צריך כמעט כלום, רק לספר קצת על העסק ומה אתם רוצים מהאתר. אם יש לכם כבר לוגו, תמונות, טקסטים או אתרים שאהבתם, תשלחו. לפני שמתחילים לעבוד נסגור יחד איזה תוכן צריך ומי מביא אותו." },
    timeline: { q: "כמה זמן לוקח לבנות את האתר?", a: "זה תלוי בכמה עמודים, באילו תכונות ומתי התוכן שלכם מוכן. לפני שמתחילים נסגור יחד לוח זמנים מציאותי. אם התוכן או המשוב מתעכבים, או שההיקף משתנה, גם המועדים יכולים לזוז.", link: { path: "process", label: "כך נראה התהליך" } },
    technical: { q: "צריך ידע טכני?", a: "ממש לא. אנחנו מסבירים הכול בשפה פשוטה ולוקחים על עצמנו את כל העבודה הטכנית. אתם מכירים את העסק הכי טוב, אז אתם אלה שמאשרים את הכיוון ואת התוכן." },
    remote: { q: "אפשר לעבוד יחד מרחוק?", a: "בטח. אנחנו עובדים עם עסקים מכל העולם דרך WhatsApp, מייל ושיחות וידאו. לפני שמתחילים נסכם איך מדברים ואיך תוכלו לעקוב אחרי ההתקדמות." },
    design: { q: "אפשר לראות את העיצוב לפני שמתחילים לבנות?", a: "כן. נראה לכם את הכיוון העיצובי לאישור לפני שמתחילים לבנות, ונעבור יחד על ההתקדמות בשלבים שסיכמנו. מה בונים, כמה סבבי תיקונים כלולים ואיך משלמים, את כל זה סוגרים לפני שמתחילים." },
    extend: { q: "אפשר להוסיף עמודים או תכונות בהמשך?", a: "בטח, האתר יכול לגדול יחד עם העסק. נסביר מה צריך לעשות וניתן הצעת מחיר על התוספת לפני שמשנים משהו." },
    price: { q: "כמה עולה אתר?", a: "על הבנייה משלמים פעם אחת, והמחירים מתחילים ב־€299 לחבילת Launch Website, ב־€749 ל־Growth Website וב־€1,499 ל־Pro Website. פרויקט Enterprise / Custom מתומחר לפי ההיקף שלו. אחסון ותחזוקה מתחילים ב־€69 לחודש, והם חובה כל עוד אנחנו מאחסנים ומנהלים את האתר. המחירים לא כוללים מיסים, אם חלים.", link: { path: "pricing", label: "להשוואת חבילות ותוכניות תחזוקה" } },
    "extra-costs": { q: "אילו עלויות נוספות כדאי להביא בחשבון?", a: "בלי הפתעות: את היקף העבודה והמחיר סוגרים לפני שמתחילים. רישום דומיין, כלים בתשלום, רישיונות ושירותי צד שלישי מסוכמים בנפרד. ואם תרצו עמודים, תיקונים או תכונות נוספים, נגיד לכם כמה זה עולה לפני שמתקדמים." },
    payment: { q: "מתי משלמים?", a: "על בניית האתר משלמים במלואה לפני שמתחילים לעבוד. בפרויקטים גדולים יותר אפשר לסכם מראש ובכתב על תשלום בשלבים. בחשבונית מפורטים תנאי התשלום וכל כמה זמן מחויבת התחזוקה.", link: { path: "terms", label: "לתנאי התשלום" } },
    methods: { q: "אילו אמצעי תשלום אתם מקבלים?", a: "בהעברה בנקאית, לפי החשבונית שנשלח לכם. לפני תחילת הפרויקט נעביר לכם את פרטי התשלום ונאשר את מה שסיכמנו." },
    ownership: { q: "האתר יהיה שלי?", a: "כן. אחרי תשלום מלא, האתר כפי שנמסר (בגרסה הסטטית שלו), התוכן שלכם והתוספות שקניתם באופן קבוע נשארים שלכם. לרישיונות של צד שלישי ולשירותים שוטפים יש תנאים משלהם. כשתוכנית תחזוקה מסתיימת, שירותים ותכונות שתלויים בה עלולים להפסיק לעבוד. כל הפרטים על בעלות והעברת קבצים מופיעים בתנאי השירות.", link: { path: "terms", label: "לפרטי הבעלות והעברת האתר" } },
    examples: { q: "אפשר לראות דוגמאות קודם?", a: "בטח. בדוגמאות שלנו תראו סגנונות ומבנים לתחומים שונים. אלה אתרי הדגמה שעוזרים לנו לדבר על כיוון, לא תבניות מוכנות: את האתר שלכם נבנה מאפס.", link: { path: "templates", label: "לצפייה בדוגמאות" } },
    mobile: { q: "האתר יעבוד בטלפון?", a: "כן, בכל חבילה. האתר מותאם לטלפון, לטאבלט ולמחשב, וכבר בשלב העיצוב אנחנו חושבים איך הוא נקרא, איך מנווטים בו ואיך לוחצים על הכפתורים עם האצבע.", link: { path: "services/mobile-first", label: "עוד על התאמה למובייל" } },
    seo: { q: "SEO כלול?", a: "כן, כל חבילה כוללת יסודות SEO, וב־Pro Website יש מבנה SEO רחב יותר. SEO מתקדם או שוטף, כתיבה נוספת ועבודת תוכן גדולה מתומחרים בנפרד. ובכנות: אף אחד לא יכול להבטיח מקום מסוים בגוגל, גם לא אנחנו.", link: { path: "services/seo", label: "לפרטים על יסודות SEO" } },
    integrations: { q: "אפשר להוסיף הזמנות, CRM, צ׳אטבוט או שפות?", a: "כן. בדרך כלל זה כבר פרויקט Enterprise / Custom. נבדוק יחד אילו מערכות, תכנים וחיבורים אתם צריכים, ונסכם את ההיקף ואת העלויות של שירותי צד שלישי." },
    hosting: { q: "איך עובדים האחסון והדומיין?", a: "כל עוד אנחנו מאחסנים ומנהלים את האתר שלכם, צריך תוכנית אחסון ותחזוקה פעילה. Basic Care מתחילה ב־€69 לחודש. רישום הדומיין ושירותי צד שלישי קשורים מסוכמים בנפרד, ולא נכללים אוטומטית במחיר הבנייה.", link: { path: "pricing", label: "לאחסון ולתחזוקה" } },
    "after-launch": { q: "מה קורה אחרי ההשקה?", a: "אנחנו ממשיכים איתכם. תוכנית האחסון והתחזוקה שסיכמנו שומרת על האתר גם אחרי ההשקה: אנחנו מנהלים את האחסון, בודקים שהאתר תמיד באוויר ומטפלים בתחזוקה שכלולה בתוכנית. נסביר לכם גם איך מבקשים עדכון ומה כלול." },
    updates: { q: "אפשר לשנות את התוכן אחרי ההשקה?", a: "כן, פשוט שלחו לנו מה לשנות. Basic Care כוללת עד 3 עדכוני תוכן קטנים בחודש, ו־Complete Care כוללת עדכוני תוכן כשצריך, כמו טקסטים, תמונות וקישורים. שינויים גדולים יותר מתומחרים בנפרד." },
    "care-plans": { q: "מה כוללת כל תוכנית תחזוקה?", a: "Basic Care עולה €69 לחודש וכוללת אחסון מנוהל, ניטור זמינות, ניהול קבצי האתר ומסד הנתונים כשישנו, גיבויים, תיקוני תקלות, תמיכת WhatsApp ועד 3 עדכוני תוכן קטנים בחודש. Complete Care עולה €129 לחודש ומוסיפה עדכוני תוכן כשצריך, תמיכת WhatsApp בעדיפות, בדיקת ביצועים חודשית ועדכון של באנר או אזור פשוט אחד בחודש. אפשר לבחור גם חיוב שנתי.", link: { path: "pricing", label: "להשוואת תוכניות התחזוקה" } },
    "care-exclusions": { q: "מה לא כלול בתוכנית התחזוקה?", a: "עמודים חדשים, כתיבת תוכן, סבבי תיקונים נוספים, חיבורים חדשים, עיצוב מחדש, SEO מתקדם והעברת תוכן מורכבת מתומחרים בנפרד. ולפני כל עבודה נוספת, נסכם איתכם מה עושים וכמה זה עולה." },
    cancel: { q: "אפשר לשנות או לבטל את תוכנית התחזוקה?", a: "כן, דברו איתנו ונראה יחד מה מתאים. ביטול דורש הודעה בכתב 30 יום מראש, ומועד הסיום תלוי בתקופת החיוב. תשלומים מראש, תכונות שתלויות בתוכנית והעברת האתר מפורטים בתנאי השירות, ולפני כל שינוי נסביר לכם בדיוק מה חל על התוכנית שלכם.", link: { path: "terms", label: "לתנאי תוכניות התחזוקה" } },
  },
};

export function faqRoute(locale: SiteLanguage, path: string) {
  return `${locale === "en" ? "" : `/${locale}`}/${path}/`;
}
export function faqSchema(locale: SiteLanguage) {
  return { "@context": "https://schema.org", "@type": "FAQPage", inLanguage: locale,
    mainEntity: FAQ_TOPICS.flatMap(topic => topic.questions.map(id => {
      const { q, a } = FAQ_CONTENT[locale][id];
      return { "@type": "Question", name: q, acceptedAnswer: { "@type": "Answer", text: a } };
    })),
  };
}
