import type { SiteLanguage } from "@/lib/routeLanguage";

export const FAQ_TOPICS = [
  { id: "getting-started", questions: ["start", "prepare", "timeline", "technical", "remote", "design", "extend"] },
  { id: "packages-payment", questions: ["price", "extra-costs", "payment", "methods", "ownership"] },
  { id: "features-seo", questions: ["examples", "mobile", "seo", "integrations", "hosting"] },
  { id: "website-care", questions: ["after-launch", "updates", "care-plans", "care-exclusions", "cancel"] },
] as const;
export type TopicId = typeof FAQ_TOPICS[number]["id"];
export type QuestionId = typeof FAQ_TOPICS[number]["questions"][number];
type Answer = { q: string; a: string; link?: { path: string; label: string } };

export const FAQ_CONTENT: Record<SiteLanguage, Record<QuestionId, Answer>> = {
  en: {
    start: { q: "How do we get started?", a: "Tell us about your business, your idea or the question on your mind. Use the contact form or WhatsApp for a free consultation. We’ll work out what you need and agree the next step together.", link: { path: "contact", label: "Get a free consultation" } },
    prepare: { q: "What should I have ready?", a: "A little about your business and what you want the website to achieve is enough for the first conversation. Share any logo, photos, text or examples you already have. Before work begins, we’ll confirm the content we need and who will provide it." },
    timeline: { q: "How long will my website take?", a: "The schedule depends on the number of pages, the features and how ready your content is. We agree a realistic timeline before starting. Content delivery, feedback and changes to the scope can affect the dates.", link: { path: "process", label: "See how the process works" } },
    technical: { q: "Do I need technical knowledge?", a: "No. We explain the decisions in plain language and handle the technical work. You bring your knowledge of the business and approve the direction and content." },
    remote: { q: "Can we work together remotely?", a: "Yes. We work with businesses worldwide through WhatsApp, email and video calls. We agree how we’ll communicate and review progress before the project starts." },
    design: { q: "Will I see the design before development?", a: "Yes. We share a design direction for your approval before development proceeds, then review progress at the agreed stages. Scope, revision rounds and payment arrangements are agreed before work begins." },
    extend: { q: "Can we add pages or features later?", a: "Yes. Your website can grow with your business. We’ll explain the work involved and quote for the additional scope before making changes." },
    price: { q: "How much does a website cost?", a: "The one-time build prices start at €299 for Launch Website, €749 for Growth Website and €1,499 for Pro Website. Enterprise / Custom is quoted to your scope. Hosting and care starts at €69 per month and is required while we host and manage your site. Prices exclude applicable taxes.", link: { path: "pricing", label: "Compare website and care plans" } },
    "extra-costs": { q: "What other costs should I allow for?", a: "We agree the scope and price before work starts. Domain registration, paid tools, licences and other third-party costs are agreed separately. New pages, extra revisions or additional features are quoted before we proceed." },
    payment: { q: "When do I pay?", a: "Website builds are paid in full before work begins. Larger projects may use staged payments by prior written agreement. Your invoice sets out the payment arrangement and the billing frequency for ongoing care.", link: { path: "terms", label: "Read the payment terms" } },
    methods: { q: "Which payment methods do you accept?", a: "Payment is by bank transfer against the invoice we send you. We’ll provide the payment details and confirm the agreed arrangement before the project starts." },
    ownership: { q: "Will the website belong to me?", a: "Once paid in full, you keep the website as delivered in its static form, your content and any add-ons purchased outright. Third-party licences and ongoing services have their own conditions. If a care plan ends, the plan’s services and dependent features may stop; the terms explain ownership and handover.", link: { path: "terms", label: "See ownership and handover details" } },
    examples: { q: "Can I see examples first?", a: "Yes. Explore our example websites to get a feel for different layouts and industries. They are demonstration projects to help you discuss a direction, rather than a promise that your website must follow a template.", link: { path: "templates", label: "Explore the example websites" } },
    mobile: { q: "Will my website work on phones?", a: "Yes. Every website package includes a responsive build for phones, tablets and desktop screens. We consider the reading order, navigation and touch controls as part of the design.", link: { path: "services/mobile-first", label: "More about mobile-first design" } },
    seo: { q: "Is SEO included?", a: "Every package includes basic SEO foundations. Pro Website includes a fuller SEO structure. Advanced or ongoing SEO, extra copywriting and wider content work are scoped separately. Search rankings are not guaranteed.", link: { path: "services/seo", label: "See the SEO foundations" } },
    integrations: { q: "Can you add bookings, a CRM, a chatbot or more languages?", a: "Yes. These are usually part of an Enterprise / Custom project. We’ll look at the platforms, content and integrations you need, then agree the scope and any third-party costs." },
    hosting: { q: "How do hosting and domains work?", a: "An active hosting and care plan is required while we host and manage your website. Basic Care starts at €69 per month. Domain registration and relevant third-party services are agreed separately; they are not automatically included in the build price.", link: { path: "pricing", label: "View hosting and care" } },
    "after-launch": { q: "What happens after launch?", a: "Your agreed hosting and care plan keeps the site supported after launch. We manage hosting, monitor availability and handle the maintenance covered by your plan. We’ll explain how to request an update and what is included." },
    updates: { q: "Can I change the content after launch?", a: "Yes. Send us the changes you need. Basic Care includes up to 3 small content updates each month. Complete Care includes content updates when you need them, such as text, images and links. Larger changes are quoted separately." },
    "care-plans": { q: "What is included in each care plan?", a: "Basic Care is €69 per month: managed hosting, uptime monitoring, website assets and database management where applicable, backups, bug fixing, WhatsApp support and up to 3 small content updates monthly. Complete Care is €129 per month and adds content updates when you need them, priority WhatsApp support, a monthly performance check and one simple banner or section update per month. Yearly billing is also available.", link: { path: "pricing", label: "Compare the care plans" } },
    "care-exclusions": { q: "What is outside the care-plan scope?", a: "New pages, copywriting, extra revision rounds, new integrations, redesigns, advanced SEO and complex content migration are quoted separately. We agree the additional work and cost with you before going ahead." },
    cancel: { q: "Can I change or cancel my care plan?", a: "Contact us to discuss a change. Cancellation requires 30 days’ written notice, and the end date depends on your billing period. Prepayments, plan-dependent features and handover are covered in the terms. We’ll clarify what applies to your plan before making the change.", link: { path: "terms", label: "Read the care-plan terms" } },
  },
  el: {
    start: { q: "Πώς ξεκινάμε;", a: "Πείτε μας για την επιχείρηση, την ιδέα ή την απορία σας. Επικοινωνήστε μέσω της φόρμας ή του WhatsApp για μια δωρεάν συμβουλευτική συζήτηση. Θα δούμε τι χρειάζεστε και θα συμφωνήσουμε μαζί το επόμενο βήμα.", link: { path: "contact", label: "Ζητήστε δωρεάν συμβουλευτική" } },
    prepare: { q: "Τι χρειάζεται να έχω έτοιμο;", a: "Για την πρώτη συζήτηση αρκούν λίγα λόγια για την επιχείρησή σας και τι θέλετε να πετύχει η ιστοσελίδα. Μοιραστείτε λογότυπο, φωτογραφίες, κείμενα ή παραδείγματα που έχετε ήδη. Πριν ξεκινήσουμε, θα συμφωνήσουμε ποιο περιεχόμενο χρειάζεται και ποιος το παρέχει." },
    timeline: { q: "Πόσο χρόνο χρειάζεται η ιστοσελίδα μου;", a: "Το χρονοδιάγραμμα εξαρτάται από τις σελίδες, τις λειτουργίες και την ετοιμότητα του περιεχομένου. Συμφωνούμε έναν ρεαλιστικό χρόνο παράδοσης πριν ξεκινήσουμε. Η παράδοση υλικού, τα σχόλιά σας και οι αλλαγές στο εύρος μπορούν να επηρεάσουν τις ημερομηνίες.", link: { path: "process", label: "Δείτε τη διαδικασία" } },
    technical: { q: "Χρειάζομαι τεχνικές γνώσεις;", a: "Όχι. Εξηγούμε τις αποφάσεις με απλά λόγια και αναλαμβάνουμε την τεχνική δουλειά. Εσείς γνωρίζετε την επιχείρησή σας και εγκρίνετε την κατεύθυνση και το περιεχόμενο." },
    remote: { q: "Μπορούμε να συνεργαστούμε εξ αποστάσεως;", a: "Ναι. Συνεργαζόμαστε με επιχειρήσεις παγκοσμίως μέσω WhatsApp, email και βιντεοκλήσεων. Συμφωνούμε πώς θα επικοινωνούμε και θα ελέγχουμε την πρόοδο πριν ξεκινήσει το έργο." },
    design: { q: "Θα δω τον σχεδιασμό πριν την ανάπτυξη;", a: "Ναι. Μοιραζόμαστε μια σχεδιαστική κατεύθυνση για έγκριση πριν προχωρήσει η ανάπτυξη και ελέγχουμε την πρόοδο στα συμφωνημένα στάδια. Το εύρος, οι γύροι διορθώσεων και οι όροι πληρωμής συμφωνούνται πριν ξεκινήσει η δουλειά." },
    extend: { q: "Μπορούμε να προσθέσουμε σελίδες ή λειτουργίες αργότερα;", a: "Ναι. Η ιστοσελίδα μπορεί να εξελίσσεται μαζί με την επιχείρησή σας. Θα εξηγήσουμε τη δουλειά που απαιτείται και θα δώσουμε προσφορά για το επιπλέον εύρος πριν κάνουμε αλλαγές." },
    price: { q: "Πόσο κοστίζει μια ιστοσελίδα;", a: "Οι εφάπαξ τιμές κατασκευής ξεκινούν από €299 για το Launch Website, €749 για το Growth Website και €1,499 για το Pro Website. Το Enterprise / Custom κοστολογείται ανάλογα με το εύρος. Η φιλοξενία και φροντίδα ξεκινά από €69 τον μήνα και απαιτείται όσο φιλοξενούμε και διαχειριζόμαστε την ιστοσελίδα. Οι τιμές δεν περιλαμβάνουν τυχόν φόρους.", link: { path: "pricing", label: "Συγκρίνετε πακέτα και πλάνα φροντίδας" } },
    "extra-costs": { q: "Ποια άλλα κόστη πρέπει να υπολογίσω;", a: "Συμφωνούμε το εύρος και την τιμή πριν ξεκινήσει η δουλειά. Η καταχώρηση domain, τα εργαλεία επί πληρωμή, οι άδειες και άλλες υπηρεσίες τρίτων συμφωνούνται ξεχωριστά. Νέες σελίδες, επιπλέον διορθώσεις ή λειτουργίες κοστολογούνται πριν προχωρήσουμε." },
    payment: { q: "Πότε πληρώνω;", a: "Η κατασκευή της ιστοσελίδας εξοφλείται πριν ξεκινήσει η δουλειά. Σε μεγαλύτερα έργα μπορεί να συμφωνηθεί σταδιακή πληρωμή, γραπτώς και εκ των προτέρων. Το τιμολόγιο αναφέρει τους όρους πληρωμής και τη συχνότητα χρέωσης της συνεχούς φροντίδας.", link: { path: "terms", label: "Διαβάστε τους όρους πληρωμής" } },
    methods: { q: "Ποιους τρόπους πληρωμής δέχεστε;", a: "Η πληρωμή γίνεται με τραπεζική μεταφορά βάσει του τιμολογίου που σας στέλνουμε. Θα δώσουμε τα στοιχεία πληρωμής και θα επιβεβαιώσουμε τη συμφωνία πριν ξεκινήσει το έργο." },
    ownership: { q: "Θα μου ανήκει η ιστοσελίδα;", a: "Μετά την πλήρη εξόφληση, κρατάτε την ιστοσελίδα όπως παραδόθηκε στη στατική της μορφή, το περιεχόμενό σας και όσα πρόσθετα αγοράσατε οριστικά. Οι άδειες τρίτων και οι συνεχείς υπηρεσίες έχουν δικούς τους όρους. Όταν λήξει ένα πλάνο φροντίδας, μπορεί να σταματήσουν οι υπηρεσίες και οι λειτουργίες που εξαρτώνται από αυτό. Οι όροι εξηγούν την ιδιοκτησία και την παράδοση αρχείων.", link: { path: "terms", label: "Δείτε τους όρους ιδιοκτησίας και παράδοσης" } },
    examples: { q: "Μπορώ να δω παραδείγματα πρώτα;", a: "Ναι. Εξερευνήστε τις ενδεικτικές ιστοσελίδες μας για να δείτε διαφορετικές διατάξεις και κλάδους. Είναι έργα επίδειξης που βοηθούν να συζητήσουμε μια κατεύθυνση, χωρίς να περιορίζουν τη δική σας ιστοσελίδα σε ένα έτοιμο πρότυπο.", link: { path: "templates", label: "Εξερευνήστε τα παραδείγματα" } },
    mobile: { q: "Θα λειτουργεί η ιστοσελίδα μου σε κινητά;", a: "Ναι. Κάθε πακέτο περιλαμβάνει κατασκευή που προσαρμόζεται σε κινητά, tablet και υπολογιστές. Η σειρά ανάγνωσης, η πλοήγηση και τα χειριστήρια αφής αποτελούν μέρος του σχεδιασμού.", link: { path: "services/mobile-first", label: "Περισσότερα για τον σχεδιασμό σε κινητά" } },
    seo: { q: "Περιλαμβάνεται SEO;", a: "Κάθε πακέτο περιλαμβάνει βασικές υποδομές SEO. Το Pro Website περιλαμβάνει πληρέστερη δομή SEO. Το προχωρημένο ή συνεχές SEO, η επιπλέον συγγραφή και το ευρύτερο περιεχόμενο συμφωνούνται ξεχωριστά. Δεν εγγυόμαστε θέσεις στα αποτελέσματα αναζήτησης.", link: { path: "services/seo", label: "Δείτε τις βάσεις SEO" } },
    integrations: { q: "Μπορείτε να προσθέσετε κρατήσεις, CRM, chatbot ή γλώσσες;", a: "Ναι. Συνήθως εντάσσονται σε έργο Enterprise / Custom. Εξετάζουμε τις πλατφόρμες, το περιεχόμενο και τις συνδέσεις που χρειάζεστε και συμφωνούμε το εύρος και τυχόν κόστη τρίτων." },
    hosting: { q: "Πώς λειτουργούν η φιλοξενία και το domain;", a: "Απαιτείται ενεργό πλάνο φιλοξενίας και φροντίδας όσο φιλοξενούμε και διαχειριζόμαστε την ιστοσελίδα σας. Το Basic Care ξεκινά από €69 τον μήνα. Η καταχώρηση domain και οι σχετικές υπηρεσίες τρίτων συμφωνούνται ξεχωριστά και δεν περιλαμβάνονται αυτόματα στην τιμή κατασκευής.", link: { path: "pricing", label: "Δείτε τη φιλοξενία και φροντίδα" } },
    "after-launch": { q: "Τι γίνεται μετά τη δημοσίευση;", a: "Το συμφωνημένο πλάνο φιλοξενίας και φροντίδας στηρίζει την ιστοσελίδα μετά τη δημοσίευση. Διαχειριζόμαστε τη φιλοξενία, παρακολουθούμε τη διαθεσιμότητα και αναλαμβάνουμε τη συντήρηση που καλύπτει το πλάνο σας. Θα εξηγήσουμε πώς ζητάτε αλλαγές και τι περιλαμβάνεται." },
    updates: { q: "Μπορώ να αλλάξω το περιεχόμενο μετά τη δημοσίευση;", a: "Ναι. Στείλτε μας τις αλλαγές που χρειάζεστε. Το Basic Care περιλαμβάνει έως 3 μικρές ενημερώσεις περιεχομένου τον μήνα. Το Complete Care περιλαμβάνει ενημερώσεις περιεχομένου όταν τις χρειάζεστε, όπως κείμενα, εικόνες και σύνδεσμοι. Μεγαλύτερες αλλαγές κοστολογούνται ξεχωριστά." },
    "care-plans": { q: "Τι περιλαμβάνει κάθε πλάνο φροντίδας;", a: "Το Basic Care κοστίζει €69 τον μήνα: διαχειριζόμενη φιλοξενία, παρακολούθηση διαθεσιμότητας, διαχείριση αρχείων και βάσης δεδομένων όπου υπάρχει, αντίγραφα ασφαλείας, διορθώσεις σφαλμάτων, υποστήριξη WhatsApp και έως 3 μικρές ενημερώσεις περιεχομένου τον μήνα. Το Complete Care κοστίζει €129 τον μήνα και προσθέτει ενημερώσεις περιεχομένου όταν τις χρειάζεστε, προτεραιότητα υποστήριξης WhatsApp, μηνιαίο έλεγχο απόδοσης και μία απλή ενημέρωση banner ή ενότητας τον μήνα. Διατίθεται και ετήσια χρέωση.", link: { path: "pricing", label: "Συγκρίνετε τα πλάνα φροντίδας" } },
    "care-exclusions": { q: "Τι δεν καλύπτει το πλάνο φροντίδας;", a: "Νέες σελίδες, συγγραφή κειμένων, επιπλέον γύροι διορθώσεων, νέες συνδέσεις υπηρεσιών, επανασχεδιασμός, προχωρημένο SEO και σύνθετη μεταφορά περιεχομένου κοστολογούνται ξεχωριστά. Συμφωνούμε την επιπλέον δουλειά και το κόστος μαζί σας πριν προχωρήσουμε." },
    cancel: { q: "Μπορώ να αλλάξω ή να ακυρώσω το πλάνο μου;", a: "Επικοινωνήστε μαζί μας για να συζητήσουμε μια αλλαγή. Η ακύρωση απαιτεί γραπτή ειδοποίηση 30 ημερών και η ημερομηνία λήξης εξαρτάται από την περίοδο χρέωσης. Οι προπληρωμές, οι λειτουργίες που εξαρτώνται από το πλάνο και η παράδοση αρχείων καλύπτονται στους όρους. Θα διευκρινίσουμε τι ισχύει για το δικό σας πλάνο πριν την αλλαγή.", link: { path: "terms", label: "Διαβάστε τους όρους φροντίδας" } },
  },
  he: {
    start: { q: "איך מתחילים?", a: "ספרו לנו על העסק, הרעיון או השאלה שמעסיקה אתכם. אפשר לפנות בטופס או בוואטסאפ לשיחת ייעוץ ללא עלות. נבין מה אתם צריכים ונסכם יחד את הצעד הבא.", link: { path: "contact", label: "לשיחת ייעוץ ללא עלות" } },
    prepare: { q: "מה כדאי להכין מראש?", a: "לשיחה הראשונה מספיק לספר קצת על העסק ומה הייתם רוצים שהאתר ישיג. שתפו לוגו, תמונות, טקסטים או דוגמאות שכבר יש לכם. לפני תחילת העבודה נוודא מה התוכן הדרוש ומי מספק אותו." },
    timeline: { q: "כמה זמן לוקח לבנות את האתר?", a: "לוח הזמנים תלוי במספר העמודים, בתכונות ובמוכנות התוכן. נסכם לוח זמנים מציאותי לפני שמתחילים. מסירת התוכן, המשוב שלכם ושינויים בהיקף העבודה עשויים להשפיע על המועדים.", link: { path: "process", label: "כך נראה התהליך" } },
    technical: { q: "צריך ידע טכני?", a: "לא. נסביר את ההחלטות בשפה פשוטה ונטפל בעבודה הטכנית. אתם מביאים את ההיכרות עם העסק ומאשרים את הכיוון והתוכן." },
    remote: { q: "אפשר לעבוד יחד מרחוק?", a: "כן. אנחנו עובדים עם עסקים בכל העולם באמצעות וואטסאפ, אימייל ושיחות וידאו. נסכם איך נתקשר ואיך נבדוק את ההתקדמות לפני תחילת הפרויקט." },
    design: { q: "נראה את העיצוב לפני הפיתוח?", a: "כן. נשתף כיוון עיצובי לאישור לפני שהפיתוח מתקדם, ונבדוק יחד את ההתקדמות בשלבים שסוכמו. היקף העבודה, סבבי התיקונים והסדרי התשלום נקבעים לפני שמתחילים." },
    extend: { q: "אפשר להוסיף עמודים או תכונות בהמשך?", a: "כן. האתר יכול להתפתח יחד עם העסק שלכם. נסביר מה העבודה הנדרשת ונציע מחיר להיקף הנוסף לפני ביצוע השינויים." },
    price: { q: "כמה עולה אתר?", a: "מחירי הבנייה החד־פעמיים מתחילים ב־€299 לחבילת Launch Website, ב־€749 ל־Growth Website וב־€1,499 ל־Pro Website. פרויקט Enterprise / Custom מתומחר לפי היקפו. אירוח ותחזוקה מתחילים ב־€69 לחודש ונדרשים כל עוד אנחנו מארחים ומנהלים את האתר. המחירים אינם כוללים מיסים ככל שחלים.", link: { path: "pricing", label: "להשוואת חבילות ותוכניות תחזוקה" } },
    "extra-costs": { q: "אילו עלויות נוספות כדאי להביא בחשבון?", a: "נסכם את היקף העבודה והמחיר לפני שמתחילים. רישום דומיין, כלים בתשלום, רישיונות ושירותי צד שלישי מוסכמים בנפרד. עמודים חדשים, תיקונים נוספים או תכונות נוספות מתומחרים לפני שמתקדמים." },
    payment: { q: "מתי משלמים?", a: "בניית האתר משולמת במלואה לפני תחילת העבודה. בפרויקטים גדולים יותר ניתן להסכים מראש ובכתב על תשלום בשלבים. החשבונית מפרטת את הסדר התשלום ואת תדירות החיוב עבור התחזוקה השוטפת.", link: { path: "terms", label: "לתנאי התשלום" } },
    methods: { q: "אילו אמצעי תשלום אתם מקבלים?", a: "התשלום מתבצע בהעברה בנקאית כנגד החשבונית שנשלח. נמסור את פרטי התשלום ונאשר את ההסדר שסוכם לפני תחילת הפרויקט." },
    ownership: { q: "האתר יהיה בבעלותי?", a: "לאחר תשלום מלא, האתר כפי שנמסר בצורתו הסטטית, התוכן שלכם והתוספות שנרכשו באופן קבוע נשארים שלכם. לרישיונות צד שלישי ולשירותים שוטפים יש תנאים משלהם. עם סיום תוכנית תחזוקה, השירותים והתכונות שתלויים בה עשויים להיפסק. תנאי השירות מסבירים את הבעלות ואת העברת הקבצים.", link: { path: "terms", label: "לפרטי הבעלות והעברת האתר" } },
    examples: { q: "אפשר לראות דוגמאות קודם?", a: "כן. בדוגמאות האתרים שלנו תוכלו להכיר מבנים וסגנונות שמתאימים לתחומים שונים. אלה פרויקטי הדגמה שנועדו לעזור לנו לדבר על כיוון, ולא להגביל את האתר שלכם לתבנית מוכנה.", link: { path: "templates", label: "לצפייה בדוגמאות" } },
    mobile: { q: "האתר יעבוד בטלפון?", a: "כן. כל חבילה כוללת אתר שמותאם לטלפונים, לטאבלטים ולמחשבים. סדר הקריאה, הניווט וכפתורי המגע הם חלק מתהליך העיצוב.", link: { path: "services/mobile-first", label: "עוד על עיצוב למובייל" } },
    seo: { q: "האם SEO כלול?", a: "כל חבילה כוללת יסודות SEO. חבילת Pro Website כוללת מבנה SEO רחב יותר. SEO מתקדם או שוטף, כתיבה נוספת ועבודת תוכן רחבה מתומחרים בנפרד. אין התחייבות למיקום בתוצאות החיפוש.", link: { path: "services/seo", label: "לפרטים על יסודות SEO" } },
    integrations: { q: "אפשר להוסיף הזמנות, CRM, צ׳אטבוט או שפות?", a: "כן. בדרך כלל מדובר בפרויקט Enterprise / Custom. נבחן אילו פלטפורמות, תכנים וחיבורים דרושים לכם, ונסכם את ההיקף ואת העלויות של שירותי צד שלישי." },
    hosting: { q: "איך עובדים האירוח והדומיין?", a: "נדרשת תוכנית אירוח ותחזוקה פעילה כל עוד אנחנו מארחים ומנהלים את האתר שלכם. Basic Care מתחילה ב־€69 לחודש. רישום דומיין ושירותי צד שלישי רלוונטיים מוסכמים בנפרד ואינם נכללים אוטומטית במחיר הבנייה.", link: { path: "pricing", label: "לאירוח ולתחזוקה" } },
    "after-launch": { q: "מה קורה אחרי ההשקה?", a: "תוכנית האירוח והתחזוקה שסוכמה ממשיכה לתמוך באתר אחרי ההשקה. אנחנו מנהלים את האירוח, מנטרים זמינות ומטפלים בתחזוקה שכלולה בתוכנית שלכם. נסביר איך מבקשים עדכון ומה כלול." },
    updates: { q: "אפשר לשנות את התוכן אחרי ההשקה?", a: "כן. שלחו לנו את השינויים הדרושים. Basic Care כוללת עד 3 עדכוני תוכן קטנים בחודש. Complete Care כוללת עדכוני תוכן כשצריך, כמו טקסטים, תמונות וקישורים. שינויים גדולים יותר מתומחרים בנפרד." },
    "care-plans": { q: "מה כוללת כל תוכנית תחזוקה?", a: "Basic Care עולה €69 לחודש וכוללת אירוח מנוהל, ניטור זמינות, ניהול קבצי האתר ומסד הנתונים כשישנו, גיבויים, תיקוני תקלות, תמיכת WhatsApp ועד 3 עדכוני תוכן קטנים בחודש. Complete Care עולה €129 לחודש ומוסיפה עדכוני תוכן כשצריך, תמיכת WhatsApp בעדיפות, בדיקת ביצועים חודשית ועדכון באנר או אזור פשוט אחד בחודש. אפשר לבחור גם חיוב שנתי.", link: { path: "pricing", label: "להשוואת תוכניות התחזוקה" } },
    "care-exclusions": { q: "מה לא כלול בתוכנית התחזוקה?", a: "עמודים חדשים, כתיבת תוכן, סבבי תיקונים נוספים, חיבורים חדשים, עיצוב מחדש, SEO מתקדם והעברת תוכן מורכבת מתומחרים בנפרד. נסכם איתכם את העבודה הנוספת ואת המחיר לפני שמתקדמים." },
    cancel: { q: "אפשר לשנות או לבטל את תוכנית התחזוקה?", a: "פנו אלינו כדי לדבר על שינוי. ביטול דורש הודעה בכתב של 30 יום, ומועד הסיום תלוי בתקופת החיוב. תשלומים מראש, תכונות שתלויות בתוכנית והעברת האתר מפורטים בתנאי השירות. נבהיר מה חל על התוכנית שלכם לפני השינוי.", link: { path: "terms", label: "לתנאי תוכניות התחזוקה" } },
  },
};

export function faqRoute(locale: SiteLanguage, path: string) {
  return `${locale === "en" ? "" : `/${locale}`}/${path}/`;
}
export function faqSchema(locale: SiteLanguage) {
  return { "@context": "https://schema.org", "@type": "FAQPage", inLanguage: locale,
    mainEntity: FAQ_TOPICS.flatMap(topic => topic.questions.map(id => {
      const { q, a } = FAQ_CONTENT[locale][id];
      return { "@type": "Question", name: q, acceptedAnswer: { "@type": "Answer", text: a } };
    })),
  };
}
