import { Link } from "wouter";
import { ArrowLeft, Clock, Tag } from "lucide-react";
import { useSEO } from "@/hooks/useSEO";

const articles = [
  { slug: "website-cost-cyprus-2026-guide", title: "כמה עולה אתר אינטרנט בקפריסין? מדריך כן ל-2026", excerpt: "פירוט ישיר של מה באמת מקבלים בכל טווח מחיר כאשר בונים אתר לעסק.", date: "21 במרץ 2026", time: "6 דקות קריאה", category: "עיצוב אתרים", cover: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1200&q=80", alt: "מדריך למחירי אתרים בקפריסין" },
  { slug: "web-design-nail-salon-beauty-studio-cyprus", title: "אתר למניקור ולסטודיו יופי בקפריסין: מה באמת צריך", excerpt: "Instagram לא מספיק. אלו הדברים שאתר של עסק יופי צריך כדי להביא לקוחות חדשים.", date: "21 במרץ 2026", time: "5 דקות קריאה", category: "יופי ובריאות", cover: "https://images.unsplash.com/photo-1604654894610-df63bc536371?w=1200&q=80", alt: "אתר לסטודיו יופי בקפריסין" },
  { slug: "yoga-pilates-studio-website-cyprus", title: "למה סטודיו יוגה או פילאטיס בקפריסין צריך אתר", excerpt: "איך אתר הופך חיפוש מקומי לתלמיד חדש, גם כשיש כבר קהילה ב-Instagram.", date: "21 במרץ 2026", time: "5 דקות קריאה", category: "בריאות וכושר", cover: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=1200&q=80", alt: "סטודיו יוגה ופילאטיס" },
  { slug: "how-to-get-found-on-google-cyprus", title: "איך לגרום לעסק להופיע ב-Google בקפריסין", excerpt: "מדריך פשוט ל-Google Maps, ביקורות, אתר מהיר ו-SEO מקומי.", date: "21 במרץ 2026", time: "7 דקות קריאה", category: "SEO וצמיחה", cover: "https://images.unsplash.com/photo-1432888622747-4eb9a8efeb07?w=1200&q=80", alt: "נראות עסקית ב-Google" },
  { slug: "restaurant-website-design-cyprus", title: "למה כל מסעדה בקפריסין צריכה אתר", excerpt: "מה Facebook לא יכול לעשות, ואיך אתר טוב מביא סועדים, הזמנות ונראות ב-Google.", date: "6 באפריל 2026", time: "6 דקות קריאה", category: "עיצוב אתרים", cover: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=1200&q=80", alt: "אתר למסעדה בקפריסין" },
  { slug: "wix-vs-professional-web-designer-cyprus", title: "Wix או מעצב אתרים מקצועי: מה עדיף לעסק?", excerpt: "השוואה ישירה בין Wix, WordPress ואתר מקצועי, כדי לבחור נכון לעסק בקפריסין.", date: "23 באפריל 2026", time: "7 דקות קריאה", category: "עיצוב אתרים", cover: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1200&q=80", alt: "Wix מול אתר מקצועי לעסק" },
];

export default function BlogHe() {
  useSEO({ title: "בלוג | מדריכים ותובנות לעסקים | DM-Labs.io", description: "מדריכים פרקטיים ותובנות על אתרים שעוזרים לעסקים לצמוח.", canonicalPath: "/he/blog/", noindex: true, ogLocale: "he_IL" });
  return <main className="hebrew-home blog-editorial" dir="rtl"><section className="relative overflow-hidden blog-editorial-hero py-20"><div className="container text-center"><p className="text-sm text-[#5B8CFF] mb-3">משאבים ותובנות</p><h1 className="text-4xl sm:text-5xl font-bold mb-5">הבלוג של <em>DM-Labs.io</em></h1><p className="text-lg text-[#5B6472] max-w-2xl mx-auto">מדריכים פרקטיים ותובנות על אתרים שעוזרים לעסקים לצמוח.</p></div></section><section className="section-spacing bg-white"><div className="container"><div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">{articles.map(article=><Link key={article.slug} href={`/he/blog/${article.slug}/`} className="group block dm-card overflow-hidden"><div className="h-52 overflow-hidden"><img src={article.cover} alt={article.alt} className="w-full h-full object-cover" /></div><div className="p-6"><span className="text-xs font-semibold text-[#5B8CFF] flex gap-1"><Tag size={11}/>{article.category}</span><div className="text-xs text-[#9BA3AF] flex gap-3 my-3"><span>{article.date}</span><span className="flex gap-1"><Clock size={11}/>{article.time}</span></div><h2 className="font-bold text-lg mb-3">{article.title}</h2><p className="text-sm text-[#5B6472] mb-4">{article.excerpt}</p><span className="text-sm font-semibold text-[#5B8CFF] inline-flex gap-1">לקריאת המאמר <ArrowLeft size={14}/></span></div></Link>)}</div></div></section></main>;
}
