import "@/styles/legal.css";
import { Link } from "wouter";

import { useSEO } from "@/hooks/useSEO";

const heading = "text-xl font-semibold text-[#111315] mb-3";
const list = "list-disc pr-5 space-y-2";
const strong = "text-[#111315]";

export default function CookiePolicyHe() {
  useSEO({ title: "מדיניות עוגיות | DM-Labs.io", description: "באילו עוגיות האתר משתמש, למה, ואיך אפשר לשנות את ההגדרות בכל רגע.", canonicalPath: "/he/cookies/", ogLocale: "he_IL", noindex: true });
  return <div className="legal-document">
    <section className="relative overflow-hidden" style={{ paddingTop: "clamp(4rem, 8vh, 6rem)", paddingBottom: "clamp(2rem, 4vh, 3rem)" }}><div className="container relative z-10">
      <Link href="/he/" className="inline-flex items-center gap-1.5 text-sm text-[#5B6472] hover:text-[#5B8CFF] transition-colors mb-8"> חזרה לדף הבית</Link>
      <div className="text-center"><p className="text-sm font-medium text-[#8B7355] mb-3 tracking-wide uppercase">משפטי</p><h1 className="text-4xl sm:text-5xl font-bold text-[#111315] mb-5">מדיניות עוגיות</h1><p className="text-sm text-[#5B6472]">עודכנה לאחרונה: 30 בספטמבר 2026</p></div>
    </div></section>
    <section className="section-spacing bg-white"><div className="container max-w-3xl"><div className="space-y-8 text-[#5B6472] text-sm leading-relaxed">
      <div><h2 className={heading}>1. מהן עוגיות</h2><p>עוגיות הן קובצי טקסט קטנים המוצבים במכשיר שלכם, כגון מחשב, טאבלט או טלפון נייד, בעת ביקור באתר. הן משמשות להפעלת אתרים ביעילות ולמסירת מידע לבעלי האתר. עוגיות מאפשרות לאתר לזהות את המכשיר שלכם ולזכור מידע מסוים על הביקור, כגון העדפותיכם.</p></div>
      <div><h2 className={heading}>2. כיצד אנו משתמשים בעוגיות</h2><p>DM-Labs.io משתמשת בעוגיות למטרות הבאות:</p><ul className={`${list} mt-3`}><li><strong className={strong}>פונקציונליות חיונית:</strong> כדי להבטיח שהאתר פועל כראוי, לרבות שמירת העדפות ההסכמה שלכם לעוגיות.</li><li><strong className={strong}>אנליטיקה:</strong> בהסכמתכם המפורשת, כדי להבין איך מבקרים משתמשים באתר ולשפר את התוכן ואת חוויית הגלישה.</li></ul><p className="mt-3">הצגת המטבע האוטומטית משתמשת במדינה המשוערת שמספק ספק האחסון שלנו. היא אינה מגדירה או קוראת עוגיות מטבע, אינה שומרת העדפת מטבע באחסון המקומי (local storage) או באחסון הזמני של הדפדפן (session storage) ואינה מפעילה אנליטיקה. דחיית אנליטיקה אינה משביתה תכונה זו. מדיניות הפרטיות מסבירה את זיהוי המדינה ואת זכויותיכם בנוגע להגנת מידע.</p></div>
      <div><h2 className={heading}>3. סוגי העוגיות שבהן אנו משתמשים</h2><div className="overflow-x-auto mt-4" role="region" aria-label="פרטי עוגיות" tabIndex={0}><table className="w-full text-right border-collapse"><thead><tr className="border-b border-[#E2E5EA]"><th className="py-3 pl-4 text-[#111315] font-semibold text-sm">שם העוגייה</th><th className="py-3 pl-4 text-[#111315] font-semibold text-sm">סוג</th><th className="py-3 pl-4 text-[#111315] font-semibold text-sm">מטרה</th><th className="py-3 text-[#111315] font-semibold text-sm">משך</th></tr></thead><tbody><tr className="border-b border-[#E2E5EA]/50"><td className="py-3 pl-4 font-mono text-xs" dir="ltr">dm_cookie_consent</td><td className="py-3 pl-4">חיונית</td><td className="py-3 pl-4">שמירת הבחירה באחסון המקומי של הדפדפן</td><td className="py-3">קבועה</td></tr><tr className="border-b border-[#E2E5EA]/50"><td className="py-3 pl-4 font-mono text-xs" dir="ltr">ph_*</td><td className="py-3 pl-4">אנליטיקה</td><td className="py-3 pl-4">PostHog לאנליטיקה, לתיעוד ביקורים ולמעקב שגיאות (נטען רק בהסכמה)</td><td className="py-3">12 חודשים</td></tr></tbody></table></div></div>
      <div><h2 className={heading}>4. עוגיות חיוניות</h2><p>עוגיות חיוניות נחוצות בהחלט לתפקוד האתר. הן מאפשרות תכונות ליבה כגון זכירת בחירת ההסכמה שלכם. עוגיות אלה אינן אוספות מידע אישי ואי אפשר להשבית אותן בלי לפגוע בפונקציונליות האתר. לפי GDPR, עוגיות חיוניות אינן דורשות הסכמה משום שהן נחוצות לשירות שביקשתם.</p></div>
      <div><h2 className={heading}>5. עוגיות אנליטיקה</h2><p>עוגיות אנליטיקה מוצבות במכשירכם רק אם נתתם הסכמה מפורשת דרך באנר העוגיות. אנו משתמשים בכלי אנליטיקה ששומרים על הפרטיות, אשר:</p><ul className={`${list} mt-3`}><li>אינם עוקבים אחריכם באתרים אחרים</li><li>אינם יוצרים פרופילי פרסום</li><li>פועלים כשאיסוף כתובות IP ב־PostHog מושבת בהגדרות האתר</li><li>אינם משתפים נתונים עם מפרסמים חיצוניים</li></ul><p className="mt-3">אפשר לבטל את ההסכמה בכל עת: פתחו את "הגדרות עוגיות" בתחתית העמוד ובחרו "לא, תודה". כך נפסקים מכאן והלאה איסוף האנליטיקה ותיעוד הביקורים. כדי למחוק גם מידע שכבר נאסף, פנו אלינו.</p></div>
      <div><h2 className={heading}>6. עוגיות של צד שלישי</h2><p>איננו משתמשים בעוגיות פרסום של צד שלישי. השירותים החיצוניים המשמשים באתר כוללים:</p><ul className={`${list} mt-3`}><li><strong className={strong}>PostHog (EU):</strong> הספק שלנו לאנליטיקה, לתיעוד ביקורים ולמעקב שגיאות. הוא נטען רק לאחר הסכמה לעוגיות אנליטיקה.</li><li><strong className={strong}>Vercel Web Analytics:</strong> אנליטיקה של השימוש באתר ללא עוגיות, שמופעלת כאן רק בהסכמה לאנליטיקה.</li><li><strong className={strong}>Google Maps ומדיה חיצונית:</strong> הספקים של מפות וקבצים שנטענים ממקורות חיצוניים עשויים לקבל נתוני חיבור טכניים בעת הטעינה.</li><li><strong className={strong}>Web3Forms:</strong> ספק טופס יצירת הקשר שלנו, שמקבל את הפרטים שאתם מזינים כשאתם שולחים פנייה.</li><li><strong className={strong}>WhatsApp:</strong> כפתור ה-WhatsApp הצף מקשר לעמוד WhatsApp חיצוני ואינו מגדיר עוגיות באתר שלנו.</li></ul></div>
      <div><h2 className={heading}>7. ניהול העדפות העוגיות שלכם</h2><p className="mb-3">ניתן לנהל עוגיות בדרכים הבאות:</p><ul className={list}><li><strong className={strong}>באנר העוגיות:</strong> בביקור הראשון באתר, הבאנר מאפשר לאשר את כל העוגיות, לדחות עוגיות שאינן חיוניות או להגדיר את ההעדפות שלכם.</li><li><strong className={strong}>הגדרות הדפדפן:</strong> רוב הדפדפנים מאפשרים לצפות, לנהל ולמחוק עוגיות. השבתת עוגיות חיוניות עשויה להשפיע על תפקוד האתר.</li><li><strong className={strong}>איפוס העדפות:</strong> פתחו את "הגדרות עוגיות" בתחתית העמוד כדי לראות או לשנות את הבחירה. ההעדפה נשמרת באחסון המקומי של הדפדפן, ולכן מחיקת עוגיות בלבד לא בהכרח מאפסת אותה.</li></ul></div>
      <div><h2 className={heading}>8. הזכויות שלכם</h2><p>לפי GDPR עומדת לכם הזכות:</p><ul className={`${list} mt-3`}><li>לדעת אילו עוגיות נמצאות בשימוש ומדוע</li><li>להסכים או לסרב לעוגיות שאינן חיוניות</li><li>לבטל את הסכמתכם בכל עת</li><li>לבקש מחיקה של נתונים שנאספו דרך עוגיות</li></ul><p className="mt-3">למידע נוסף על זכויות הגנת המידע שלכם, ראו את <Link href="/he/privacy/" className="text-[#5B8CFF] hover:underline">מדיניות הפרטיות</Link>.</p></div>
      <div><h2 className={heading}>9. שינויים במדיניות זו</h2><p>אנו עשויים לעדכן מדיניות עוגיות זו מעת לעת כדי לשקף שינויים בנהלים שלנו או מטעמים משפטיים, תפעוליים או רגולטוריים. הגרסה המעודכנת תפורסם בדף זה עם תאריך עדכון חדש.</p></div>
      <div><h2 className={heading}>10. יצירת קשר</h2><p>אם יש לכם שאלות על השימוש שלנו בעוגיות, צרו איתנו קשר בכתובת <a href="mailto:info@dm-labs.io" className="text-[#5B8CFF] hover:underline" dir="ltr">info@dm-labs.io</a>.</p></div>
    </div><div className="mt-10 pt-8 border-t border-[#E2E5EA] flex gap-4"><Link href="/he/privacy/" className="text-sm text-[#5B8CFF] hover:underline">מדיניות פרטיות</Link><Link href="/he/terms/" className="text-sm text-[#5B8CFF] hover:underline">תנאי שירות</Link></div></div></section>
  </div>;
}
