import { useEffect, useState } from "react";
import { ChevronDown, MessageCircle } from "lucide-react";
import AnimateIn from "@/components/AnimateIn";
import { useSEO } from "@/hooks/useSEO";

const WA="https://wa.me/35797472847?text=%D7%A9%D7%9C%D7%95%D7%9D%20DM-Labs.io%2C%20%D7%99%D7%A9%20%D7%9C%D7%99%20%D7%A9%D7%90%D7%9C%D7%94.";
const groups: Array<[string, Array<[string, string]>]> = [
  ["מתחילים",[["איך מתחילים?","שלחו לנו הודעה ב-WhatsApp או השתמשו בטופס. נשאל על העסק, הקהל, התוכן והמטרות, ואז נמליץ על היקף האתר המתאים."],["איזה מידע צריך לספק?","שם העסק, תיאור קצר של הפעילות, וכל לוגו, תמונות, טקסט או דוגמאות שכבר יש לכם. אנחנו מאשרים את דרישות התוכן המעשיות לפני תחילת העבודה."],["האם צריך ידע טכני?","לא. אנחנו מדריכים את תהליך האתר ומסבירים החלטות בשפה ברורה. אתם מתמקדים בעסק ומאשרים את הכיוון והתוכן."],["האם אתם עובדים עם לקוחות מחוץ לפאפוס?","כן. DM-Labs.io עובדת עם עסקים ברחבי קפריסין ויכולה לעבוד מרחוק גם עם לקוחות ביוון ובמקומות נוספים, בהתאם להיקף שסוכם."],["אפשר לראות כיוון עיצובי לפני פיתוח?","כן. אנו משתפים כיוון עיצובי לאישור לפני שהפיתוח מתקדם ומעדכנים אתכם בכל שלב שסוכם."],["אפשר להוסיף עמודים או תכונות בהמשך?","כן. עמודים, פונקציונליות או תוכן נוספים מתומחרים לפי העבודה הנדרשת, ונבהיר את ההיקף לפני ביצוע השינוי."]]],
  ["חבילות ותשלום",[["כמה עולה אתר?","חבילת Launch Website מתחילה ב-€299, Growth Website ב-€749 ו-Pro Website ב-€1,499. פרויקטי Enterprise / Custom מתחילים ב-€1,499 ומתומחרים לפי היקף."],["יש עלויות נסתרות?","לא. מסכימים מראש על ההיקף והמחיר. עלויות דומיין, אירוח ושירותי צד שלישי, אם רלוונטיות, מוסברות בנפרד."],["איך עובד התשלום?","מסכימים על שלבי התשלום לפני תחילת העבודה. היתרה הסופית משולמת במסירה, אחרי שבחנתם את התוצאה שסוכמה."],["אילו אמצעי תשלום אתם מקבלים?","אנו מקבלים העברה בנקאית ואמצעי תשלום מרכזיים. נמסור פרטי תשלום כשתהיו מוכנים להתקדם."],["האם האתר בבעלותי אחרי הבנייה?","לאחר תשלום מלא, האתר והתוכן שלו שייכים לכם, בכפוף לרישיונות או שירותי צד שלישי המשמשים בפרויקט."]]],
  ["תכונות ו-SEO",[["האם האתר יעבוד בטלפון?","כן. כל חבילת אתר נבנית באופן רספונסיבי לטלפונים, טאבלטים ומחשבים."],["האם SEO כלול?","כל חבילה כוללת יסודות SEO. חבילת Pro Website כוללת מבנה SEO רחב יותר. SEO מתקדם, כתיבה נוספת ותוכניות תוכן רחבות מתומחרים בנפרד."],["אפשר להוסיף מערכת הזמנות, CRM, צ׳אטבוט או שפות?","כן. אלו בדרך כלל חלק מפרויקט Enterprise / Custom, מפני שההיקף תלוי בפלטפורמה, תוכן, אינטגרציות ודרישות."],["אפשר לספק אירוח?","נוכל לסייע בהתקנה הטכנית ולהסביר מראש עלויות רלוונטיות של אירוח, דומיין, SSL או שירותי צד שלישי."]]],
  ["אחרי ההשקה ותחזוקת האתר",[["אילו תוכניות תחזוקה אתם מציעים?","Basic Care עולה €69 לחודש וכוללת ניטור אירוח, גיבויים ותיקוני תקלות, תמיכת WhatsApp ועד 3 עדכוני תוכן קטנים בחודש. Complete Care עולה €129 לחודש ומוסיפה עדכונים סבירים ללא הגבלה, תמיכת WhatsApp בעדיפות, בדיקת ביצועים חודשית ועדכון באנר או אזור פשוט אחד בחודש."],["מה לא כלול בתחזוקת האתר?","עמודים חדשים, כתיבה, סבבי תיקונים נוספים מעבר להקצאה, אינטגרציות חדשות, עיצובים מחדש, מבנה SEO מתקדם או מלא והעברת תוכן מורכבת אינם כלולים ומתומחרים בנפרד."],["אפשר לשנות או לבטל תוכנית תחזוקה?","הסדרי התחזוקה מאושרים לפני תחילת העבודה. פנו אלינו כדי לדון בשינוי או ביטול, כולל מועדי עבודה מתוזמנים והעברת גישה."]]],
];
function Item({q,a}:{q:string;a:string}){const [open,setOpen]=useState(false);return <div className="border-b border-[#E2E5EA] last:border-0 faq-editorial-item"><button onClick={()=>setOpen(!open)} className="w-full flex items-center justify-between py-5 text-right group" aria-expanded={open}><span className="text-base font-medium text-[#111315] pl-4 group-hover:text-[#5B8CFF]">{q}</span><ChevronDown size={20} className={`text-[#5B6472] shrink-0 transition-transform ${open?"rotate-180 text-[#5B8CFF]":""}`}/></button><div className="overflow-hidden transition-all duration-300" style={{maxHeight:open?"600px":"0",opacity:open?1:0}}><p className="text-sm text-[#5B6472] leading-relaxed pb-5">{a}</p></div></div>}
export default function FAQHe(){useSEO({title:"שאלות נפוצות על עיצוב אתרים | DM-Labs.io",description:"תשובות לשאלות נפוצות על חבילות DM-Labs.io, מחירים, יסודות SEO, תחזוקת אתרים והיקף פרויקט.",ogLocale:"he_IL",noindex:true});useEffect(()=>{const id="faq-jsonld-schema",items=groups.flatMap(([,v])=>v);const el=document.createElement("script");el.id=id;el.type="application/ld+json";el.textContent=JSON.stringify({"@context":"https://schema.org","@type":"FAQPage",mainEntity:items.map(([q,a])=>({"@type":"Question",name:q,acceptedAnswer:{"@type":"Answer",text:a}}))});document.head.appendChild(el);return()=>el.remove()},[]);return <div className="faq-editorial hebrew-home" dir="rtl"><section className="relative overflow-hidden faq-editorial-hero"><div className="container relative z-10 text-center"><AnimateIn><p className="faq-editorial-label">שאלות נפוצות</p><h1 className="faq-editorial-title"><span>כל מה שצריך</span><span>לדעת <em>על העבודה איתנו</em></span></h1><p className="faq-editorial-lead">כאן תמצאו תשובות על התהליך, חבילות, SEO ותחזוקה. אם חסרה תשובה, כתבו לנו.</p></AnimateIn></div></section><section className="section-spacing bg-white"><div className="container max-w-3xl">{groups.map(([category,items],i)=><AnimateIn key={category} delay={i*.1} className="mb-12 last:mb-0"><h2 className="text-xl font-semibold text-[#111315] mb-4 flex items-center gap-2"><span className="w-1.5 h-6 brand-gradient rounded-full"/><span>{category}</span></h2><div className="dm-card !p-0 overflow-hidden"><div className="px-6">{items.map(([q,a])=><Item key={q} q={q} a={a}/>)}</div></div></AnimateIn>)}</div></section><section className="section-spacing dark-section text-center"><div className="container"><AnimateIn><h2 className="faq-editorial-cta-heading"><span>עדיין יש</span><span><em>שאלות?</em></span></h2><p className="faq-editorial-cta-copy">נשמח לעזור. שלחו לנו הודעה ונחזור אליכם במהירות.</p><a href={WA} target="_blank" rel="noopener noreferrer" className="btn-primary"><MessageCircle size={18}/>צרו קשר</a></AnimateIn></div></section></div>}
