import { Link } from "wouter";
import { useSEO } from "@/hooks/useSEO";
import { ArrowLeft, CheckCircle2, ChevronLeft, Zap } from "lucide-react";

const why = [["מהירות משפיעה על המרות", "מחקר של Google מצא שעיכוב של שנייה אחת בטעינת מובייל יכול להפחית המרות בעד 20%. אתר שעולה בפחות משתי שניות שומר מבקרים מעורבים, ואתר שלוקח חמש שניות מאבד רבים עוד לפני שהעמוד מופיע."], ["Core Web Vitals ודירוג ב-Google", "Google משתמשת במדדי Core Web Vitals של מהירות וחוויית משתמש בדירוג. אתר מהיר מדורג טוב יותר, ואתר איטי נפגע גם כשהתוכן שלו מצוין."], ["חוויה טובה יותר לכולם", "אתר מהיר מרגיש מקצועי. אתר איטי מרגיש שבור. ביצועים הם חלק מחוויית המותג, וכך אנחנו מתייחסים אליהם."]];
const deliver = ["תמונות דחוסות ומותאמות בפורמט WebP", "טעינה עצלה לתמונות ולרכיבים כבדים", "חבילות CSS ו-JavaScript ממוזערות", "פיצול קוד יעיל והסרת קוד מיותר", "הגשת נכסים סטטיים דרך CDN", "ציון Lighthouse של 90 ומעלה בביצועים", "עמידה במדדי LCP, FID ו-CLS", "זמן תגובה ראשוני מהיר: TTFB"];
const steps = [["אופטימיזציית נכסים", "כל תמונה נדחסת ומומרת לפורמטים מודרניים כמו WebP. סרטונים מוזרמים במקום להיות מוטמעים."], ["יעילות קוד", "אנחנו כותבים קוד קל ויעיל ומסירים ספריות ותלויות שלא נעשה בהן שימוש."], ["Caching ו-CDN", "נכסים סטטיים מוגשים דרך CDN עם מטמון אגרסיבי כדי למזער זמני טעינה בכל העולם."], ["בדיקת ביצועים", "לפני ההשקה אנחנו מריצים בדיקת Lighthouse מלאה ומתקנים בעיות עד שהציונים ירוקים."]];
const faqs = [["לאילו ציוני Lighthouse אתם מכוונים?", "אנחנו מכוונים ל-90 ומעלה בביצועים, נגישות, שיטות עבודה מומלצות ו-SEO. רוב האתרים שלנו מגיעים למעל 95 במחשב."], ["האם הביצועים יורדים עם הזמן?", "זה יכול לקרות כשמוסיפים תוכן בלי תשומת לב. תוכניות התחזוקה שלנו כוללות בדיקות ביצועים חודשיות כדי שהאתר יישאר מהיר."], ["מה לגבי סקריפטים חיצוניים כמו צ׳אט?", "סקריפטים חיצוניים לצ׳אט, אנליטיקה או הזמנות עלולים להאט אתר. אנחנו טוענים אותם באופן אסינכרוני ודוחים סקריפטים לא קריטיים."]];

export default function PerformanceHe() {
  useSEO({ title: "ביצועי אתר מהירים | DM-Labs.io", description: "אופטימיזציית ביצועי אתר עם טעינה מהירה, Core Web Vitals ותשתית טכנית יעילה.", canonicalPath: "/he/services/performance/", ogLocale: "he_IL", noindex: true });
  return <main className="hebrew-home" dir="rtl"><section className="section-spacing bg-white"><div className="container max-w-4xl"><Link href="/he/services/" className="inline-flex gap-1 text-sm text-[#5B6472] mb-8"><ChevronLeft size={16}/>חזרה לשירותים</Link><div className="w-16 h-16 rounded-2xl grid place-items-center bg-violet-100 mb-6"><Zap className="text-violet-600" size={32}/></div><h1 className="text-4xl sm:text-5xl font-bold mb-4">ביצועים מהירים</h1><p className="text-xl text-[#5B6472] mb-6">כל שנייה של טעינה עולה לכם בלקוחות. אנחנו הופכים את האתר למהיר במיוחד.</p><p className="text-[#5B6472] leading-relaxed">מהירות אתר אינה רק מדד טכני. היא משפיעה ישירות על כמה מבקרים נשארים, כמה מהם הופכים ללקוחות ועל הדירוג שלכם ב-Google. אנחנו מקפידים על ביצועים בכל שלב, מדחיסת תמונות ועד טעינת JavaScript.</p></div></section><section className="section-spacing"><div className="container"><p className="text-sm text-[#8B7355] mb-3">למה זה חשוב</p><h2 className="text-3xl font-bold mb-10">כך עושים את זה נכון</h2><div className="grid md:grid-cols-3 gap-6">{why.map(([h,p],i)=><article className="dm-card" key={h}><b className="text-violet-600">0{i+1}</b><h3 className="font-semibold text-lg my-3">{h}</h3><p className="text-sm text-[#5B6472] leading-relaxed">{p}</p></article>)}</div></div></section><section className="section-spacing bg-white"><div className="container grid lg:grid-cols-2 gap-12"><div><p className="text-sm text-[#8B7355] mb-3">מה מקבלים</p><h2 className="text-3xl font-bold mb-5">כל מה שנכלל, בלי תוספות נסתרות</h2><Link className="btn-primary" href="/he/contact/"><ArrowLeft size={16}/>מתחילים את הפרויקט</Link></div><ul className="space-y-3">{deliver.map(x=><li className="flex gap-3" key={x}><CheckCircle2 className="text-violet-600 shrink-0" size={18}/><span>{x}</span></li>)}</ul></div></section><section className="section-spacing"><div className="container"><p className="text-sm text-[#8B7355] mb-3">התהליך</p><h2 className="text-3xl font-bold mb-10">כך אנחנו מספקים את השירות</h2><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-6">{steps.map(([h,p],i)=><div key={h}><b className="text-violet-600">0{i+1}</b><h3 className="font-semibold my-3">{h}</h3><p className="text-sm text-[#5B6472]">{p}</p></div>)}</div></div></section><section className="section-spacing bg-white"><div className="container max-w-3xl"><p className="text-sm text-[#8B7355] mb-3">שאלות נפוצות</p><h2 className="text-3xl font-bold mb-8">מה כדאי לדעת</h2>{faqs.map(([h,p])=><article className="dm-card mb-4" key={h}><h3 className="font-semibold mb-2">{h}</h3><p className="text-sm text-[#5B6472]">{p}</p></article>)}</div></section></main>;
}
