import { ArrowLeft, CheckCircle2, Code, CreditCard, MessageCircle, Palette, Rocket } from "lucide-react";
import type { CSSProperties } from "react";
import { useSEO } from "@/hooks/useSEO";
import AnimateIn from "@/components/AnimateIn";

const TRIANGLE_GEO = "/media/cloudfront/triangle-geometry-Rf9Cpg8ynqtbpdNzPsSccU.webp";
const WHATSAPP_HEBREW = "https://wa.me/35797472847?text=%D7%A9%D7%9C%D7%95%D7%9D%20DM-Labs.io%2C%20%D7%90%D7%A9%D7%9E%D7%97%20%D7%9C%D7%A9%D7%9E%D7%95%D7%A2%20%D7%A2%D7%9C%20%D7%94%D7%AA%D7%94%D7%9C%D7%99%D7%9A%20%D7%9C%D7%91%D7%A0%D7%99%D7%99%D7%AA%20%D7%94%D7%90%D7%AA%D7%A8.";
const steps = [
  { step: "01", icon: MessageCircle, title: "שיחת היכרות", time: "כיום אחד", desc: "מתחילים בשיחה קצרה ב-WhatsApp. ספרו לנו על העסק, מה אתם צריכים ומה היעדים שלכם. בלי ז׳רגון טכני, רק שיחה נעימה וברורה.", details: ["שיחת WhatsApp של 15 עד 20 דקות", "לומדים על העסק שלכם", "אתם מספרים מה אתם צריכים", "ממליצים על החבילה המתאימה"], color: "#5B8CFF" },
  { step: "02", icon: CreditCard, title: "שומרים מקום", time: "באותו היום", desc: "אחרי שסיכמנו יחד את ההיקף ואת המסגרת התקציבית, משלימים את התשלום ויוצאים לדרך. פשוט, שקוף וללא הפתעות.", details: ["מחיר ברור ללא עלויות נסתרות", "תשלום חד פעמי ובעלות מלאה", "העבודה מתחילה מיד", "אפשרויות תשלום מאובטחות"], color: "#6FE3FF" },
  { step: "03", icon: Palette, title: "עיצוב ובנייה", time: "3 עד 7 ימים", desc: "אנחנו מעצבים ומפתחים את האתר. תראו התקדמות לאורך הדרך ותוכלו לתת משוב בתחנות חשובות.", details: ["עיצוב מותאם למותג", "פיתוח בגישת מובייל תחילה", "עדכוני התקדמות שוטפים", "המשוב שלכם מעצב את התוצאה"], color: "#8B5CFF" },
  { step: "04", icon: Code, title: "סקירה ותיקונים", time: "1 עד 2 ימים", desc: "אתם בודקים את האתר ומבקשים שינויים. אנחנו מלטשים את הכול עד שתהיו מרוצים מהתוצאה.", details: ["תצוגה מלאה של האתר", "2 סבבים ב-Launch, 3 ב-Growth ו-4 ב-Pro", "מתאימים עד שאתם מרוצים", "ללא חיוב נוסף על תיקונים כלולים"], color: "#5B8CFF" },
  { step: "05", icon: Rocket, title: "השקה", time: "כיום אחד", desc: "האתר עולה לאוויר. אנחנו מטפלים בדומיין, באירוח ובבדיקות האחרונות כדי שהכול יעבוד בדיוק כמו שצריך.", details: ["חיבור דומיין", "הגדרת תעודת SSL", "שיפור מהירות האתר", "האתר שלכם באוויר"], color: "#6FE3FF" },
] as const;

export default function ProcessHe() {
  useSEO({ title: "תהליך בניית אתר | DM-Labs.io", description: "משיחת היכרות ועד לאתר באוויר בתוך 5 עד 14 ימים. כך DM-Labs.io מעצבת ובונה את האתר שלכם, שלב אחר שלב.", ogLocale: "he_IL", noindex: true });
  return <main className="hebrew-home process-editorial" dir="rtl">
    <section className="process-editorial-hero relative overflow-hidden"><div className="absolute top-10 right-10 w-[300px] h-[300px] opacity-[0.04] pointer-events-none"><img src={TRIANGLE_GEO} alt="" className="w-full h-full object-contain" /></div><div className="container relative z-10"><AnimateIn><p className="process-editorial-label">איך זה עובד</p><h1 className="text-5xl sm:text-6xl font-bold text-[#111315] leading-tight">מרעיון <em className="not-italic brand-gradient-text">לאתר באוויר</em></h1><p className="process-editorial-lead">תהליך ברור ושקוף שמתקדם בקצב נוח, כדי שתדעו בדיוק מה קורה בכל שלב.</p></AnimateIn></div></section>
    <section className="process-editorial-track section-spacing bg-white"><div className="container max-w-5xl"><AnimateIn className="process-editorial-track-intro"><p className="process-editorial-label">המסע</p><h2 className="process-editorial-section-heading">חמישה שלבים ברורים. <em>תוצאה ממוקדת אחת.</em></h2></AnimateIn><div className="relative"><div className="process-editorial-rail absolute right-[35px] sm:right-[39px] top-[96px] sm:top-[104px] bottom-[96px] sm:bottom-[104px] w-[2px] pointer-events-none" style={{ zIndex: 0 }} /><div className="process-editorial-step-list space-y-0">{steps.map((step, index) => <AnimateIn key={step.step} delay={index * 0.1}><article className="process-editorial-step relative flex gap-8 sm:gap-10" style={{ "--process-accent": step.color, paddingBottom: index < steps.length - 1 ? "clamp(3.5rem, 7vh, 6rem)" : 0 } as CSSProperties}><div className="shrink-0 flex flex-col items-center" style={{ position: "relative", zIndex: 10 }}><div className="process-editorial-icon w-[72px] h-[72px] sm:w-[80px] sm:h-[80px] rounded-2xl flex items-center justify-center" style={{ boxShadow: "0 0 0 4px white" }}><step.icon size={34} className="process-editorial-icon-svg" strokeWidth={1.5} /></div></div><div className="process-editorial-step-content flex-1 pt-3"><div className="process-editorial-step-meta flex items-center gap-3 mb-3"><span className="process-editorial-step-index" dir="ltr">{step.step}</span><span className="process-editorial-step-time">{step.time}</span></div><h3 className="process-editorial-step-title">{step.title}</h3><p className="process-editorial-step-desc">{step.desc}</p><ul className="process-editorial-step-details grid grid-cols-1 sm:grid-cols-2 gap-3">{step.details.map(detail => <li key={detail} className="flex items-start gap-2.5"><CheckCircle2 size={16} className="process-editorial-detail-check shrink-0 mt-0.5" />{detail}</li>)}</ul></div></article></AnimateIn>)}</div></div></div></section>
    <section className="process-editorial-timeline section-spacing"><div className="container"><AnimateIn className="text-center mb-12"><p className="process-editorial-label">קצב עם מטרה</p><h2 className="process-editorial-section-heading process-editorial-section-heading-centered">לוח זמנים <em>טיפוסי</em></h2><p className="process-editorial-timeline-lead">רוב הפרויקטים עוברים מהודעה ראשונה לאתר באוויר בתוך פחות משבועיים.</p></AnimateIn><AnimateIn delay={0.2}><div className="process-editorial-timeline-grid grid grid-cols-1 sm:grid-cols-3 gap-6 max-w-4xl mx-auto">{[{ label: "Launch Website", time: "5 עד 7 ימים", price: "from €299" }, { label: "Growth Website", time: "7 עד 10 ימים", price: "from €749" }, { label: "Pro Website", time: "10 עד 14 ימים", price: "from €1,499" }].map(item => <article key={item.label} className="process-editorial-timeline-card dm-card !p-8 text-right"><p className="process-editorial-timeline-time">{item.time}</p><p className="process-editorial-timeline-label" dir="ltr">{item.label}</p><p className="process-editorial-timeline-price" dir="ltr">{item.price}</p></article>)}</div></AnimateIn></div></section>
    <section className="process-editorial-cta section-spacing dark-section text-center"><div className="container"><AnimateIn><p className="process-editorial-label process-editorial-label-light">הצעד הבא</p><h2 className="process-editorial-cta-heading">מוכנים <em>להתחיל</em> את התהליך?</h2><p className="text-lg text-[#94A3B8] mb-8 max-w-xl mx-auto">הצעד הראשון הוא שיחת WhatsApp קצרה וללא לחץ. בואו נדבר על העסק שלכם.</p><div className="flex flex-wrap justify-center gap-4"><a href={WHATSAPP_HEBREW} target="_blank" rel="noopener noreferrer" className="btn-primary"><MessageCircle size={18} />מתחילים שיחה</a><a href="/he/services/" className="btn-secondary !border-white/20 !text-white">שירותים וחבילות <ArrowLeft size={16} /></a></div></AnimateIn></div></section>
  </main>;
}
