import { Link } from "wouter";
import { useSEO } from "@/hooks/useSEO";
const sections=[
["למה עמוד Facebook לא מספיק למסעדה",<>בעלי מסעדות רבים מסתמכים על Facebook, Instagram והמלצות מפה לאוזן. אלה כלים טובים, אך אינם נכס בבעלות המסעדה. האלגוריתם קובע מי רואה את התוכן, חיפוש של ״מסעדה לידי״ אינו מציג את הפוסטים שלכם, וחשבון יכול להיחסם ללא התראה.<br/><br/>אתר הוא הבית הקבוע של המסעדה. הוא מאפשר להציג את התפריט, הסיפור, המיקום והזמנה ברגע שבו הסועד כבר מחפש מקום לשבת בו.</>],
["איך נראים חיפושי מסעדות ב-Google",<>כאשר מישהו מחפש ״מסעדה בניקוסיה״, ״דגים בלימסול״ או ״ארוחת בוקר בפאפוס״, Google מציג את המפה המקומית ותוצאות אורגניות. שתיהן נשענות על אתר מסודר ועל Google Business Profile שמתוחזק היטב.<br/><br/>מסעדה עם אתר מהיר שמציג בבירור מטבח, אזור ושעות פעילות יכולה להופיע לפני עסק שמסתמך רק על עוקבים ב-Facebook.</>],
["מה אתר מסעדה באמת צריך",<ul><li><strong>תפריט ברור למובייל:</strong> לא PDF איטי שצריך להגדיל, אלא תפריט קריא בטלפון תוך שניות.</li><li><strong>הזמנה קלה:</strong> טופס, WhatsApp או מערכת הזמנות שמקצרת את הדרך בין ״בא לי להזמין״ ל״הזמנתי״.</li><li><strong>מיקום, שעות ופרטי קשר:</strong> בכל עמוד, בצורה שאי אפשר לפספס.</li><li><strong>צילומים אמיתיים ומעוררי תיאבון:</strong> תמונות שמציגות את האוכל והאווירה בכנות.</li><li><strong>Google Maps ונתונים מובנים:</strong> כדי ש-Google יבין היכן אתם, איזה סוג מסעדה אתם ומתי פתוח.</li></ul>],
["לא לבנות הכול על Tripadvisor",<>Tripadvisor יכול להיות נכס חשוב, אך הוא עדיין פלטפורמה של מישהו אחר. אתר חזק יכול להופיע מעל דף Tripadvisor בחיפושים ממותגים וגם בחיפושים שבהם Tripadvisor כלל לא מופיע. המטרה היא להשתמש בשניהם, לא לבחור רק באחד.</>],
["כמה עולה אתר למסעדה בקפריסין?",<>אתר מסעדה מקצועי לא חייב לעלות אלפי אירו. החבילות של DM-Labs.io מתחילות ב-€299 עבור Launch, עם עיצוב מותאם, תפריט, תמונות, טופס יצירת קשר, Google Maps ו-SEO בסיסי. ברוב המקרים האתר מוכן בתוך 5 עד 7 ימים.<br/><br/>Growth ב-€749 כולל יותר תוכן, WhatsApp להזמנות ו-SEO מתקדם יותר. Pro ב-€1,499 מתאים למסעדות שזקוקות לפונקציונליות מורחבת, כגון הזמנות או הזמנה אונליין.</>],
["העיקר",<>אתר למסעדה צריך לעבוד במובייל, לעלות מהר ולעזור לאנשים למצוא את המסעדה ב-Google. אתם מביאים תפריט, תמונות ושעות פעילות, ואנחנו מטפלים בצד הטכני.</>]
];
export default function RestaurantHe(){useSEO({title:"למה מסעדות בקפריסין צריכות אתר | DM-Labs.io",description:"למה עמוד Facebook לא מספיק למסעדה בקפריסין, ומה אתר טוב צריך כדי למשוך סועדים והזמנות.",canonicalPath:"/he/blog/restaurant-website-design-cyprus/",ogType:"article",noindex:true,ogLocale:"he_IL"});return <main className="hebrew-home bg-[#F6F6F4]" dir="rtl"><article className="container max-w-3xl py-16"><Link href="/he/blog/" className="text-[#5B8CFF] text-sm">חזרה לבלוג</Link><header className="my-10"><p className="text-xs text-[#9CA3AF]">6 באפריל 2026 · 6 דקות קריאה</p><h1 className="text-3xl sm:text-4xl font-extrabold my-4">למה כל מסעדה בקפריסין צריכה אתר, ולא רק עמוד Facebook</h1><p className="text-lg text-[#5B6472]">איך אתר מסעדה מסודר מביא יותר סועדים, הזמנות ונראות ב-Google.</p></header><div className="prose prose-slate max-w-none space-y-10 text-[#374151]">{sections.map(([h,c])=><section key={String(h)}><h2 className="text-2xl font-bold text-[#111315] mb-3">{h}</h2><div className="leading-relaxed">{c}</div></section>)}<section className="bg-gradient-to-br from-[#EEF3FF] to-[#F0EAFF] rounded-2xl p-8"><h2 className="text-xl font-bold mb-3">מוכנים להעלות את המסעדה לאונליין?</h2><p className="mb-5">נבדוק את הנוכחות הקיימת ונציע מה האתר של המסעדה באמת צריך, ללא ז׳רגון וללא לחץ.</p><Link href="/he/contact/" className="btn-primary">ייעוץ ללא עלות</Link></section></div></article></main>}
