import { Link } from "wouter";
import { useEffect } from "react";
import { useSEO } from "@/hooks/useSEO";
import AnimateIn, { StaggerContainer, StaggerItem } from "@/components/AnimateIn";
import { ArrowLeft, CheckCircle2, ChevronLeft, MessageCircle, Search } from "lucide-react";

const GRADIENT_BG = "/media/cloudfront/gradient-mesh-bg-nrkTNmAHHWeVJB3ubHRGDu.webp";
const TRIANGLE_GEO = "/media/cloudfront/triangle-geometry-Rf9Cpg8ynqtbpdNzPsSccU.webp";
const DARK_CTA_BG = "/media/cloudfront/dark-cta-bg-LgZ8epcpi9XDGLof5Q9KgS.webp";
const ACCENT = "#5B8CFF";
const WHY = [
  ["תנועה אורגנית מגיעה בלי לשלם על כל קליק", "בניגוד לפרסום ממומן, אתר שמותאם היטב ממשיך למשוך מבקרים גם זמן רב אחרי ההשקה. הופעה בעמוד הראשון של Google עבור השירותים המרכזיים שלכם מביאה זרם יציב של לקוחות פוטנציאליים בלי הוצאה על מודעות."],
  ["SEO מקומי לעסקים מקומיים", "אם אתם פועלים בעיר או באזור מסוים, SEO מקומי הוא חיוני. אנחנו מתאימים את האתר לחיפושים מבוססי מיקום, למשל מספרה בתל אביב או פיזיותרפיסט בברצלונה, כדי שתופיעו כשלקוחות קרובים מחפשים."],
  ["SEO טכני מהיסוד", "אתרים רבים נבנים בלי מחשבה על SEO. אנחנו עושים את ההפך: לכל עמוד יש כותרת נכונה, תיאור מטא, היררכיית כותרות, סימון schema ומבנה כתובות נקי כבר מרגע העלייה לאוויר."],
] as const;
const DELIVERABLES = ["מבנה כתובות וכותרות עמודים ידידותיים ל-SEO", "תיאורי מטא לכל עמוד", "היררכיית כותרות נכונה: H1, H2 ו-H3", "סימון schema עבור LocalBusiness, שירותים ושאלות נפוצות", "טקסט חלופי לתמונות ושמות קבצים נכונים", "מפת אתר XML וקובץ robots.txt", "הגדרת Google Search Console", "אופטימיזציית Core Web Vitals", "הגדרת SEO מקומי לעסקים מבוססי מיקום"] as const;
const PROCESS = [["01", "מחקר מילות מפתח", "אנחנו מזהים את ביטויי החיפוש שהלקוחות המתאימים משתמשים בהם ובונים סביבם את אסטרטגיית התוכן."], ["02", "אופטימיזציה בעמוד", "כל עמוד נבנה לפי שיטות העבודה של SEO: כותרות, תוכן, קישורים פנימיים ומבנה נכון."], ["03", "SEO טכני", "אנחנו מוודאים שהאתר מהיר, ניתן לסריקה ומאונדקס כראוי על ידי Google."], ["04", "הגדרת Search Console", "אנחנו מחברים את האתר ל-Google Search Console כדי שתוכלו לעקוב אחרי ביצועים ולטפל בבעיות לאורך זמן."]] as const;
const FAQS = [["כמה זמן לוקח לראות תוצאות מ-SEO?", "SEO הוא השקעה ארוכת טווח. רוב האתרים מתחילים לראות שיפור בתוך 3 עד 6 חודשים, ותוצאות משמעותיות לאחר 6 עד 12 חודשים. אנחנו מניחים את התשתית, ותוכן ובניית קישורים לאורך זמן מאיצים את התוצאות."], ["האם אתם מציעים שירותי SEO שוטפים?", "תוכנית Complete Care כוללת ניטור SEO חודשי ואופטימיזציות קטנות. קמפיינים מלאים של שיווק תוכן ובניית קישורים זמינים כשירות נפרד."], ["האם האתר ידורג ב-Google מיד אחרי ההשקה?", "Google צריכה זמן כדי לסרוק ולאנדקס את האתר. בהשקה נשלח את מפת האתר ל-Google Search Console כדי לזרז את התהליך, אבל הדירוג דורש זמן ותלוי ברמת התחרות בענף."]] as const;

export default function SeoHe() {
  useSEO({ title: "אופטימיזציית SEO לעסקים | DM-Labs.io", description: "SEO טכני ומקומי לעסקים, עם תשתית חיפוש נכונה, ביצועים מהירים והגדרת Google Search Console.", canonicalPath: "/he/services/seo/", ogLocale: "he_IL", noindex: true });
  useEffect(() => { const id = "service-jsonld-schema", url = "https://dm-labs.io/he/services/seo/"; const value = { "@context": "https://schema.org", "@graph": [{ "@type": "Service", "@id": `${url}#service`, name: "אופטימיזציית SEO", description: "אופטימיזציית SEO טכנית ומקומית לעסקים.", serviceType: "אופטימיזציית SEO", url, provider: { "@id": "https://dm-labs.io/#professionalservice" }, areaServed: [{ "@type": "Country", name: "Cyprus" }, { "@type": "Country", name: "Greece" }] }, { "@type": "FAQPage", mainEntity: FAQS.map(([name, text]) => ({ "@type": "Question", name, acceptedAnswer: { "@type": "Answer", text } })) }] }; const existing = document.getElementById(id); const script = existing instanceof HTMLScriptElement ? existing : document.createElement("script"); script.id = id; script.type = "application/ld+json"; script.textContent = JSON.stringify(value); if (!existing) document.head.appendChild(script); return () => document.getElementById(id)?.remove(); }, []);
  return <main className="hebrew-home" dir="rtl">
    <section className="relative overflow-hidden" style={{ paddingTop: "clamp(4rem, 8vh, 7rem)", paddingBottom: "clamp(3rem, 6vh, 5rem)" }}><div className="absolute inset-0"><img src={GRADIENT_BG} alt="" className="h-full w-full object-cover opacity-10" /><img src={TRIANGLE_GEO} alt="" className="absolute top-0 left-0 h-96 w-96 object-contain opacity-[0.05]" /></div><div className="container relative z-10"><AnimateIn><Link href="/he/services/" className="inline-flex items-center gap-1.5 text-sm text-[#5B6472] hover:text-[#5B8CFF] mb-8"><ChevronLeft size={16} />חזרה לשירותים</Link></AnimateIn><div className="max-w-3xl"><AnimateIn delay={0.1}><div className="inline-flex items-center justify-center w-16 h-16 rounded-2xl mb-6" style={{ background: `${ACCENT}15` }}><Search size={32} style={{ color: ACCENT }} /></div><h1 className="text-4xl sm:text-5xl font-bold text-[#111315] mb-4 leading-tight">אופטימיזציית SEO</h1><p className="text-xl text-[#5B6472] mb-6">להימצא ב-Google ולמשוך לקוחות שכבר מחפשים את מה שאתם מציעים.</p><p className="text-base text-[#5B6472] leading-relaxed max-w-2xl">SEO הוא התהליך שמאפשר לאתר שלכם להופיע בתוצאות החיפוש של Google. אנחנו בונים SEO בכל אתר מהיום הראשון, לא כתוספת מאוחרת. מקוד נקי ועד תוכן עשיר במילות מפתח ומהירות טעינה, כל החלטה טכנית מתקבלת עם חיפוש אורגני בראש.</p></AnimateIn></div></div></section>
    <section className="section-spacing bg-white"><div className="container"><AnimateIn className="mb-12"><p className="text-sm font-medium text-[#8B7355] mb-3">למה זה חשוב</p><h2 className="text-3xl font-bold text-[#111315]">כך עושים את זה נכון</h2></AnimateIn><StaggerContainer className="grid grid-cols-1 md:grid-cols-3 gap-8">{WHY.map(([title, body], i) => <StaggerItem key={title}><article className="dm-card h-full"><span className="inline-flex w-8 h-8 rounded-lg items-center justify-center mb-4 text-sm font-bold" style={{ color: ACCENT, background: `${ACCENT}15` }} dir="ltr">0{i + 1}</span><h3 className="text-lg font-semibold text-[#111315] mb-3">{title}</h3><p className="text-sm text-[#5B6472] leading-relaxed">{body}</p></article></StaggerItem>)}</StaggerContainer></div></section>
    <section className="section-spacing"><div className="container grid grid-cols-1 lg:grid-cols-2 gap-16 items-center"><AnimateIn><p className="text-sm font-medium text-[#8B7355] mb-3">מה מקבלים</p><h2 className="text-3xl font-bold text-[#111315] mb-6">כל מה שנכלל, בלי תוספות נסתרות</h2><p className="text-base text-[#5B6472] leading-relaxed mb-8">כל הפריטים הבאים כלולים בפרויקט האתר שלכם. אין עלויות נסתרות ואין תוספות שאמורות להיות הסטנדרט.</p><Link href="/he/contact/" className="btn-primary"><ArrowLeft size={16} />מתחילים את הפרויקט</Link></AnimateIn><AnimateIn delay={0.2}><ul className="space-y-3">{DELIVERABLES.map(item => <li key={item} className="flex items-start gap-3"><CheckCircle2 size={18} className="shrink-0 mt-0.5" style={{ color: ACCENT }} /><span className="text-sm text-[#111315]">{item}</span></li>)}</ul></AnimateIn></div></section>
    <section className="section-spacing bg-white"><div className="container"><AnimateIn className="text-center mb-12"><p className="text-sm font-medium text-[#8B7355] mb-3">התהליך</p><h2 className="text-3xl font-bold text-[#111315]">כך אנחנו מספקים את השירות</h2></AnimateIn><StaggerContainer className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-8">{PROCESS.map(([step,title,desc]) => <StaggerItem key={step}><div className="text-center"><span className="inline-flex w-14 h-14 rounded-2xl items-center justify-center mb-5 text-sm font-bold" style={{ color: ACCENT, background: `${ACCENT}12` }} dir="ltr">{step}</span><h3 className="text-base font-semibold text-[#111315] mb-2">{title}</h3><p className="text-sm text-[#5B6472] leading-relaxed">{desc}</p></div></StaggerItem>)}</StaggerContainer></div></section>
    <section className="section-spacing"><div className="container max-w-3xl mx-auto"><AnimateIn className="text-center mb-12"><p className="text-sm font-medium text-[#8B7355] mb-3">שאלות נפוצות</p><h2 className="text-3xl font-bold text-[#111315]">מה כדאי לדעת</h2></AnimateIn><StaggerContainer className="space-y-4">{FAQS.map(([q,a]) => <StaggerItem key={q}><article className="dm-card"><h3 className="text-base font-semibold text-[#111315] mb-3">{q}</h3><p className="text-sm text-[#5B6472] leading-relaxed">{a}</p></article></StaggerItem>)}</StaggerContainer></div></section>
    <section className="relative overflow-hidden"><div className="absolute inset-0 bg-[#0F172A]"><img src={DARK_CTA_BG} alt="" className="h-full w-full object-cover opacity-40" /></div><div className="container relative z-10 section-spacing text-center"><AnimateIn><p className="text-sm font-medium text-[#6FE3FF] mb-4">מוכנים להתחיל?</p><h2 className="text-3xl sm:text-4xl font-bold text-white mb-6">נבנה את האתר שלכם עם תשתית חיפוש נכונה מהיום הראשון.</h2><p className="text-base text-[#94A3B8] mb-10">שלחו הודעה ונכיר את הפרויקט שלכם בתוך כמה שעות.</p><div className="flex flex-wrap justify-center gap-4"><Link href="/he/contact/" className="btn-primary !h-14 !text-base !px-8"><MessageCircle size={20} />יצירת קשר</Link><Link href="/he/pricing/" className="inline-flex items-center gap-2 px-8 h-14 rounded-xl border-2 border-white/20 text-white font-semibold">לתמחור <ArrowLeft size={18} /></Link></div></AnimateIn></div></section>
  </main>;
}
