import { ArrowLeft, CalendarCheck, CheckCircle2, FileText, Globe, Headphones, Image, Languages, MapPin, MessageCircle, Rocket, Search, Share2, Shield, Smartphone, Users, Zap } from "lucide-react";
import { useSEO } from "@/hooks/useSEO";
import AnimateIn, { StaggerContainer, StaggerItem } from "@/components/AnimateIn";

const SERVICES_BG = "/media/cloudfront/services-hero-bg-bfPgb525LqzgdU7JVYn89M.webp";
const TRIANGLE_GEO = "/media/cloudfront/triangle-geometry-Rf9Cpg8ynqtbpdNzPsSccU.webp";
const WHATSAPP_HEBREW = "https://wa.me/35797472847?text=%D7%A9%D7%9C%D7%95%D7%9D%20DM-Labs.io%2C%20%D7%90%D7%A9%D7%9E%D7%97%20%D7%9C%D7%A7%D7%91%D7%9C%20%D7%99%D7%99%D7%A2%D7%95%D7%A5%20%D7%9C%D7%92%D7%91%D7%99%20%D7%90%D7%AA%D7%A8%20%D7%9C%D7%A2%D7%A1%D7%A7%20%D7%A9%D7%9C%D7%99.";

const packages = [
  { name: "Launch Website", price: "€299", color: "#5B8CFF", intro: "נקודת פתיחה מקצועית, ברורה ומזמינה לעסק שמוכן לצאת לדרך.", features: ["אתר של עמוד אחד או שני עמודים קלים", "מותאם למובייל", "יסודות SEO", "WhatsApp וקישורים לרשתות חברתיות", "2 סבבי תיקונים"] },
  { name: "Growth Website", price: "€749", color: "#8B5CFF", intro: "אתר שעוזר לאנשים הנכונים למצוא אתכם, להכיר אתכם וליצור קשר בביטחון.", features: ["עד 4 עמודים", "טופס יצירת קשר", "Google Maps ועדויות או ביקורות", "SEO בסיסי", "הגדרת Search Console ו-Analytics", "3 סבבי תיקונים"] },
  { name: "Pro Website", price: "€1,499", color: "#6FE3FF", intro: "נוכחות דיגיטלית רחבה יותר, עם תוכן עשיר ותשתית יציבה שמוכנה לצמוח איתכם.", features: ["עד 7 עמודים", "גלריה או תיק עבודות", "אנימציות Popup וגלילה", "מבנה SEO מלא", "הקמת בלוג או חבילת נכסים ויזואליים", "4 סבבי תיקונים"] },
] as const;

const included = [
  [Smartphone, "מותאם למובייל", "נראה מצוין בכל מכשיר, בטלפון, בטאבלט ובמחשב."], [Search, "SEO מובנה", "תשתית חיפוש נכונה כדי שלקוחות יוכלו למצוא אתכם בגוגל."], [Zap, "טעינה מהירה", "קוד ונכסים מותאמים למהירות טעינה גבוהה."], [Shield, "אבטחת SSL", "תעודת SSL ללא עלות לשמירה על האתר והמבקרים."], [Image, "עיצוב מותאם אישית", "ללא תבניות מדף, כל אתר מותאם לזהות המותג."], [MapPin, "Google Maps", "מפה מוטמעת שמאפשרת ללקוחות למצוא את המיקום שלכם."], [FileText, "טפסי יצירת קשר", "טפסים מקצועיים ששולחים פניות ישירות למייל שלכם."], [Share2, "חיבור לרשתות חברתיות", "כל הקישורים לפרופילים החברתיים במקום אחד."], [Headphones, "תמיכה אחרי ההשקה", "אנחנו נשארים זמינים גם אחרי שהאתר עולה לאוויר."],
] as const;

export default function ServicesHe() {
  useSEO({ title: "שירותי עיצוב אתרים לעסקים | DM-Labs.io", description: "עיצוב אתרים בהתאמה אישית לעסקים. חבילות Launch, Growth ו-Pro החל מ-€299, לצד תוכניות תחזוקה שוטפות.", ogLocale: "he_IL", noindex: true });
  return <main className="hebrew-home services-editorial" dir="rtl">
    <section className="relative overflow-hidden" style={{ paddingTop: "clamp(4rem, 8vh, 6rem)", paddingBottom: "clamp(4rem, 8vh, 6rem)" }}><div className="absolute inset-0 opacity-10 pointer-events-none"><img src={SERVICES_BG} alt="" className="w-full h-full object-cover" /></div><div className="absolute top-10 left-10 w-[300px] h-[300px] opacity-[0.04] animate-float-slower pointer-events-none"><img src={TRIANGLE_GEO} alt="" className="w-full h-full object-contain" /></div><div className="container relative z-10 text-center"><AnimateIn><p className="text-sm font-medium text-[#5B8CFF] mb-3 tracking-wide">מה אנחנו מציעים</p><h1 className="text-4xl sm:text-5xl font-bold text-[#111315] mb-5">שירותים שעוזרים לכם <em className="brand-gradient-text not-italic">להתקדם</em></h1><p className="text-lg text-[#5B6472] max-w-2xl mx-auto">אנחנו סטודיו קטן לעיצוב אתרים שמלווה עסקים בדרך לנוכחות דיגיטלית מדויקת. מעיצוב מותאם אישית ועד SEO, אנחנו דואגים לכל הפרטים החשובים כדי שתוכלו להתמקד בעסק שלכם.</p></AnimateIn></div></section>
    <section className="section-spacing bg-white"><div className="container"><AnimateIn className="mb-12"><p className="text-sm font-medium text-[#5B8CFF] mb-3">שירותי הליבה</p><h2 className="text-3xl sm:text-4xl font-bold text-[#111315]">חבילות <em className="not-italic brand-gradient-text">אתר</em></h2></AnimateIn><div className="w-full flex flex-col sm:flex-row items-center justify-center gap-3 py-4 px-6 mb-10 rounded-xl brand-gradient text-center"><span className="text-base sm:text-lg font-bold text-white tracking-wide" dir="ltr">Packages from €299</span><span className="hidden sm:block w-px h-5 bg-white/40" /><span className="text-sm sm:text-base text-white/90 font-medium">היקף ברור, מחירים שקופים ושיחת ייעוץ ללא עלות לפני שמתחילים.</span></div><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6 sm:gap-8">{packages.map((item, index) => <AnimateIn key={item.name} delay={(index + 1) * 0.1}><article className={index === 1 ? "brand-gradient-border h-full" : "h-full"}><div className="dm-card h-full flex flex-col"><div className="flex items-center gap-4 mb-4"><div className="icon-container-gradient">{index === 1 ? <Rocket size={24} style={{ color: item.color }} /> : <Globe size={24} style={{ color: item.color }} />}</div><div><p className="text-xs font-semibold tracking-wide" style={{ color: item.color }} dir="ltr">{item.name}</p><p className="text-2xl font-bold text-[#111315]" dir="ltr">{item.price} <span className="text-sm font-normal text-[#5B6472]">one-time</span></p></div></div>{index === 1 && <span className="self-start -mt-1 mb-3 rounded-full brand-gradient px-3 py-1 text-xs text-white">מומלץ</span>}<p className="text-sm text-[#5B6472] mb-5 leading-relaxed">{item.intro}</p><ul className="space-y-3 mb-6 flex-1">{item.features.map(feature => <li key={feature} className="flex items-start gap-2.5 text-sm text-[#111315]"><CheckCircle2 size={16} style={{ color: item.color }} className="shrink-0 mt-0.5" />{feature}</li>)}</ul><a href={WHATSAPP_HEBREW} target="_blank" rel="noopener noreferrer" className={index === 1 ? "btn-primary w-full justify-center" : "btn-secondary w-full justify-center"}>שיחת ייעוץ ללא עלות</a></div></article></AnimateIn>)}</div>
    <AnimateIn className="mt-8"><div className="rounded-2xl overflow-hidden bg-[#0F172A] text-white p-8 flex flex-col lg:flex-row gap-8"><div className="lg:w-72"><span className="inline-block px-3 py-1 rounded-full text-xs bg-[#5B8CFF]">נבנה במיוחד בשבילכם</span><p className="mt-4 text-sm font-semibold text-[#6FE3FF]" dir="ltr">Enterprise / Custom</p><p className="text-4xl font-bold mt-1" dir="ltr">from €1,499</p><p className="text-xs text-[#5B8CFF] mt-2">הצעת מחיר לפי היקף</p><p className="text-sm text-white/60 mt-4">לאינטגרציות, אתרים רב לשוניים, CMS, AI, צ׳אטבוטים, CRM, הזמנות או היקף תוכן חריג.</p><a href={WHATSAPP_HEBREW} target="_blank" rel="noopener noreferrer" className="mt-6 inline-flex items-center gap-2 rounded-xl brand-gradient px-6 py-3 text-sm font-semibold"><MessageCircle size={16} />דברו איתנו</a></div><div className="grid grid-cols-2 sm:grid-cols-4 gap-4 flex-1">{[[Globe,"עיצוב מלא מהיסוד"],[Zap,"היקף מותאם לפרויקט"],[CalendarCheck,"CRM והזמנות"],[Languages,"תמיכה רב לשונית"],[Users,"מנהל פרויקט"],[Headphones,"תמיכה בעדיפות"],[ArrowLeft,"אפשרות לליווי שוטף"],[CheckCircle2,"SEO ותוכן מותאמים"]].map(([Icon,label]) => { const ItemIcon = Icon as typeof Globe; const itemLabel = label as string; return <span key={itemLabel} className="flex gap-2 text-sm text-white/80"><ItemIcon size={15} className="text-[#6FE3FF] shrink-0" />{itemLabel}</span>})}</div></div></AnimateIn></div></section>
    <section className="section-spacing"><div className="container"><AnimateIn className="text-center mb-12"><p className="text-sm font-medium text-[#5B8CFF] mb-3">בכל אתר</p><h2 className="text-3xl sm:text-4xl font-bold text-[#111315]">כל מה שצריך, <em className="not-italic brand-gradient-text">בלי מה שלא צריך</em></h2></AnimateIn><StaggerContainer className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-5 sm:gap-6">{included.map(([Icon,title,description]) => <StaggerItem key={title}><article className="dm-card h-full !p-6"><div className="flex items-start gap-4"><div className="icon-container-gradient !w-12 !h-12 !rounded-xl"><Icon size={20} className="text-[#5B8CFF]" /></div><div><h3 className="text-base font-semibold text-[#111315] mb-1">{title}</h3><p className="text-sm text-[#5B6472] leading-relaxed">{description}</p></div></div></article></StaggerItem>)}</StaggerContainer></div></section>
    <section className="section-spacing bg-white"><div className="container max-w-5xl"><AnimateIn><p className="text-sm font-medium text-[#5B8CFF] mb-3">תוספת אופציונלית</p><h2 className="text-3xl sm:text-4xl font-bold text-[#111315] mb-5">תוכניות <em className="not-italic brand-gradient-text">תחזוקת אתר</em></h2><p className="text-lg text-[#5B6472] mb-6">שומרים על האתר רענן, מאובטח ומהיר לאורך זמן. בחרו את התוכנית שמתאימה לכם.</p><div className="grid grid-cols-1 md:grid-cols-2 gap-5 mb-8"><article className="dm-card !p-5"><p className="text-sm font-semibold text-[#5B8CFF] mb-2" dir="ltr">Basic Care</p><p className="text-3xl font-bold text-[#111315] mb-4" dir="ltr">€69 <span className="text-base font-normal">per month</span></p><ul className="space-y-2 text-sm">{["ניטור רציף של האתר והאירוח", "גיבויים ותיקוני תקלות", "תמיכה ב-WhatsApp", "עד 3 עדכוני תוכן קטנים בחודש"].map(x => <li key={x} className="flex gap-2"><CheckCircle2 size={15} className="text-[#5B8CFF] shrink-0" />{x}</li>)}</ul></article><article className="dm-card !p-5 border-[#8B5CFF]/30"><p className="text-sm font-semibold text-[#8B5CFF] mb-2" dir="ltr">Complete Care</p><p className="text-3xl font-bold text-[#111315] mb-4" dir="ltr">€129 <span className="text-base font-normal">per month</span></p><ul className="space-y-2 text-sm">{["כל מה שבתוכנית Basic Care", "עדכונים סבירים ללא הגבלה", "תמיכת WhatsApp בעדיפות", "בדיקת ביצועים חודשית", "עדכון באנר או אזור פשוט פעם בחודש"].map(x => <li key={x} className="flex gap-2"><CheckCircle2 size={15} className="text-[#8B5CFF] shrink-0" />{x}</li>)}</ul></article></div><a href={WHATSAPP_HEBREW} target="_blank" rel="noopener noreferrer" className="btn-primary"><MessageCircle size={18} />שאלו על תחזוקה</a></AnimateIn></div></section>
    <section className="section-spacing dark-section text-center"><div className="container"><AnimateIn><h2 className="text-3xl sm:text-4xl font-bold text-white mb-5">מוכנים <em className="not-italic text-[#6FE3FF]">להתחיל?</em></h2><p className="text-lg text-[#94A3B8] mb-8 max-w-xl mx-auto">שלחו לנו הודעה ונבדוק איזו חבילה מתאימה לעסק שלכם.</p><div className="flex flex-wrap justify-center gap-4"><a href={WHATSAPP_HEBREW} target="_blank" rel="noopener noreferrer" className="btn-primary"><MessageCircle size={18} />דברו ב-WhatsApp</a><a href="/he/" className="btn-secondary !border-white/20 !text-white">חזרה לעמוד הראשי <ArrowLeft size={16} /></a></div></AnimateIn></div></section>
  </main>;
}
