import {
  FAQ_CONTENT,
  FAQ_TOPICS,
  faqRoute,
  type QuestionId,
} from "@/components/faq/faqContent";
import type { SiteLanguage } from "@/lib/routeLanguage";
import { CHAT_COPY } from "./chatCopy";
import { z } from "zod";

export type ChatSource = { title: string; path: string };
export type GuideAnswer = { text: string; sources: ChatSource[] };
type Passage = ChatSource & {
  text: string;
  keywords?: string;
  faq?: QuestionId;
};
export type PageContext = {
  title: string;
  path: string;
  passages: Passage[];
  article: boolean;
};

const clean = (value: string) => value.replace(/\s+/g, " ").trim();
const MARKS = new RegExp("\\p{M}", "gu");
const WORDS = new RegExp("[\\p{L}\\p{N}]+", "gu");
const normalize = (value: string) =>
  value.toLowerCase().normalize("NFD").replace(MARKS, "").replace(/ς/g, "σ");
const STOP = new Set(
  normalize(
    "a an the is are be i we you my our your to for of in on and or about what how can do does have has it this that with website websites site business tell me need want more get please us will would could should which some help μου μας σας μια ενα την τον της και για στο στην πως τι να με το σε ειναι εχω θελω ιστοσελιδα επιχειρηση את של על איך מה אני אתם שלי שלנו אתר אפשר לי זה עם האם"
  ).split(" ")
);
const words = (value: string) =>
  Array.from(new Set(normalize(value).match(WORDS) ?? [])).filter(
    word => word.length > 1 && !STOP.has(word)
  );

// Intent aliases select existing FAQ answers; none of these strings supplies an answer.
const INTENTS: Partial<Record<QuestionId, RegExp>> = {
  start: /get started|new website|start a|νεα ιστοσελ|ξεκινα|אתר חדש|מתחיל/,
  price:
    /\b(costs?|prices?|pricing|budget|expensive|afford)\b|κοστι|κοστο|τιμ[εη]|תקציב|מחיר|עולה/,
  timeline:
    /how long|timeline|deadline|ποσο καιρο|χρονοδιαγ|ποτε.*ετοιμ|כמה זמן/,
  seo: /\bseo\b|search engine|καταταξ|קידום|\bgoogle\b/,
  hosting: /\b(hosting|domain)\b|φιλοξεν|דומיין|אחסון/,
  ownership: /\b(own|ownership|belong|handover)\b|ανηκει|ιδιοκτη|בעלות|שייך/,
  payment: /\b(pay|payment|deposit|installment)\b|πληρω|תשלום|משלמ/,
  "care-plans": /\b(care|maintenance|support)\b|συντηρη|υποστηρ|תחזוק|תמיכה/,
  cancel: /\b(cancel|cancellation)\b|ακυρω|ביטול|לבטל/,
  mobile: /\b(mobile|phone|responsive|tablet)\b|κινητ|טלפון|נייד/,
  examples:
    /\b(example|examples|portfolio)\b|your work|δειγμα|δουλεια|דוגמא|עבודות/,
  integrations:
    /\b(booking|bookings|crm|chatbot|integration|languages)\b|κρατησ|γλωσσ|שפות|הזמנות/,
  remote: /\b(remote|worldwide|abroad)\b|αποσταση|εξωτερικ|מרחוק/,
};

function excerpt(text: string, max = 900) {
  if (text.length <= max) return text;
  const sentences = text.match(/[^.!?;]+[.!?;]+(?:\s|$)/g) ?? [];
  let result = "";
  for (const sentence of sentences) {
    if ((result + sentence).length > max) break;
    result += sentence;
  }
  return result.trim() || `${text.slice(0, max).replace(/\s+\S*$/, "")}…`;
}

function passagesFrom(root: ParentNode, source: ChatSource): Passage[] {
  let heading = source.title;
  const passages: Passage[] = [];
  root.querySelectorAll("h2, h3, p, li").forEach(element => {
    if (element.closest("nav, footer, pre, code, .blog-cta-box, .dm-chat"))
      return;
    const text = clean(element.textContent ?? "");
    if (/^H/.test(element.tagName)) {
      heading = text || source.title;
      return;
    }
    if (text.length < 65 || element.querySelector("p, li")) return;
    passages.push({
      ...source,
      title:
        heading === source.title
          ? source.title
          : `${source.title} · ${heading}`,
      text: excerpt(text),
    });
  });
  return passages;
}

/** Only reads the visible marketing article; chat, forms and visitor input are excluded. */
export function readPageContext(path: string): PageContext {
  const title = clean(
    document.querySelector("main h1, article h1, h1")?.textContent ?? "DM Labs"
  );
  const root = document.querySelector(
    ".blog-content, .blog-article-page .prose"
  );
  return {
    path: path.split(/[?#]/)[0],
    title,
    article: path.includes("/blog/") && Boolean(root),
    passages: root ? passagesFrom(root, { title, path }) : [],
  };
}

const corpusCache = new Map<SiteLanguage, Promise<Passage[]>>();
const PublishedPassages = z
  .array(
    z.object({
      title: z.string().max(500),
      path: z
        .string()
        .max(600)
        .regex(/^\/(?!\/|\\)/),
      text: z.string().max(2000),
    })
  )
  .max(15000);
async function publishedCorpus(locale: SiteLanguage): Promise<Passage[]> {
  // Same-origin static artifact generated by prerender; never fetch user-provided URLs.
  if (import.meta.env.DEV) return [];
  const controller = new AbortController();
  const timeout = window.setTimeout(() => controller.abort(), 5000);
  try {
    const response = await fetch(`/site-guide/${locale}.json`, {
      signal: controller.signal,
    });
    if (!response.ok || !response.headers.get("content-type")?.includes("json"))
      return [];
    return PublishedPassages.parse(await response.json());
  } catch {
    return [];
  } finally {
    window.clearTimeout(timeout);
  }
}
function corpus(locale: SiteLanguage): Promise<Passage[]> {
  const cached = corpusCache.get(locale);
  if (cached) return cached;
  const promise = (async () => {
    const published = publishedCorpus(locale);
    const faq: Passage[] = FAQ_TOPICS.flatMap(topic =>
      topic.questions.map(id => ({
        title: FAQ_CONTENT[locale][id].q,
        path: `${faqRoute(locale, "faq")}#${topic.id}`,
        text: FAQ_CONTENT[locale][id].a,
        faq: id,
      }))
    );
    // Reuse published content, loaded only when a visitor asks. No API key or external model.
    const posts =
      locale === "en"
        ? (await import("@/data/blogPosts")).POSTS
        : locale === "el"
          ? [
              (await import("@/data/getMoreCustomersCyprusEl"))
                .GET_MORE_CUSTOMERS_CYPRUS_EL,
              (await import("@/data/drGeorgeCaseStudyLocales"))
                .DR_GEORGE_CASE_STUDY_EL,
            ]
          : [
              (await import("@/data/drGeorgeCaseStudyLocales"))
                .DR_GEORGE_CASE_STUDY_HE,
            ];
    const articles = posts.flatMap(post => {
      const path = `${locale === "en" ? "" : `/${locale}`}/blog/${post.slug}/`;
      const template = document.createElement("template");
      template.innerHTML = post.content; // Inert local source, never mounted or executed.
      const source = { title: post.title, path };
      return [
        ...(post.faq ?? []).map(item => ({
          ...source,
          title: `${post.title} · ${item.question}`,
          text: item.answer,
        })),
        ...passagesFrom(template.content, source),
      ];
    });
    return [...faq, ...articles, ...(await published)];
  })();
  corpusCache.set(locale, promise);
  promise.catch(() => corpusCache.delete(locale));
  return promise;
}

/** Extractive retrieval: the reply is always a published passage, never an invented claim. */
export async function answerFromWebsite(
  question: string,
  locale: SiteLanguage,
  page: PageContext
): Promise<GuideAnswer> {
  const items = await corpus(locale);
  const query = normalize(question);
  const exactFaq = items.find(
    item => item.faq && normalize(item.title) === query
  );
  // Commercial answers always use the current FAQ rather than older article prices.
  const matches = Object.entries(INTENTS)
    .filter(([, pattern]) => pattern.test(query))
    .map(([id]) => id);
  const priority = [
    "cancel",
    "ownership",
    "hosting",
    "care-plans",
    "payment",
    "timeline",
    "price",
  ];
  const commercial = priority.find(id => matches.includes(id));
  const intent = exactFaq ?? items.find(item => item.faq === commercial);
  if (intent)
    return {
      text: intent.text,
      sources: [{ title: intent.title, path: intent.path }],
    };

  const tokens = words(question);
  if (!tokens.length && !matches.length)
    return { text: CHAT_COPY[locale].fallback, sources: [] };
  const scored = [...page.passages, ...items]
    .map(item => {
      const titleWords = new Set(words(item.title));
      const bodyWords = new Set(words(item.text));
      const matched = tokens.filter(
        token => titleWords.has(token) || bodyWords.has(token)
      );
      const exact = tokens.filter(token => titleWords.has(token)).length;
      const intentMatch = item.faq && matches.includes(item.faq);
      const coverage = matched.length / Math.max(tokens.length, 1);
      const score =
        matched.length * 2 +
        exact * 2 +
        (intentMatch ? 5 : 0) +
        (item.path === page.path && matched.length ? 1 : 0);
      return {
        item,
        score,
        coverage,
        eligible:
          Boolean(intentMatch) ||
          (matched.length >= Math.min(2, tokens.length) && coverage >= 0.4),
      };
    })
    .filter(result => result.eligible && result.score >= 4)
    .sort((a, b) => b.score - a.score);
  const best = scored[0]?.item;
  if (!best) return { text: CHAT_COPY[locale].fallback, sources: [] };
  return { text: best.text, sources: [{ title: best.title, path: best.path }] };
}
