export type WorkLocale = "en" | "el" | "he";
export const workProjects = [
  { id: "sunday-boat", name: "Sunday Boat", category: "restaurant" },
  { id: "away", name: "AWAY", category: "hospitality" },
  { id: "hartley", name: "Hartley", category: "cafe" },
  { id: "luxe-realty", name: "Luxe Realty", category: "property" },
  { id: "bella-salon", name: "Bella Salon", category: "beauty" },
  { id: "pulse-gym", name: "Pulse", category: "fitness" },
  { id: "dr-elara-dental", name: "Dr. Elara", category: "health" },
  { id: "nomad-coffee", name: "Nomad Coffee", category: "cafe" },
  { id: "arcos-architecture", name: "Arcos", category: "architecture" },
] as const;
export const workCopy = {
  en: {
    title: "Our Work",
    intro: "Different brands. Different worlds. Made to be explored.",
    web: "Web Design",
    demos: "Website Demos",
    hint: "Drag to explore. Choose a website to step inside.",
    touchHint: "Swipe to explore. Tap to choose, then tap to open.",
    open: "View website",
    previous: "Previous",
    next: "Next",
    cta: "Your brand. Its own world.",
    ctaCopy: "Let’s make something that feels like you.",
    contact: "Let’s talk",
    categories: {
      restaurant: "Restaurant",
      hospitality: "Hospitality",
      cafe: "Café",
      property: "Real estate",
      beauty: "Beauty",
      fitness: "Fitness",
      health: "Healthcare",
      architecture: "Architecture",
    },
  },
  el: {
    title: "Η δουλειά μας",
    intro: "Διαφορετικά brands. Ξεχωριστοί κόσμοι. Εξερευνήστε τους.",
    web: "Σχεδιασμός ιστοσελίδων",
    demos: "Δείγματα ιστοσελίδων",
    hint: "Σύρετε για εξερεύνηση. Επιλέξτε μια ιστοσελίδα για να μπείτε.",
    touchHint:
      "Σύρετε για εξερεύνηση. Πατήστε για επιλογή και ξανά για άνοιγμα.",
    open: "Δείτε την ιστοσελίδα",
    previous: "Προηγούμενο",
    next: "Επόμενο",
    cta: "Το brand σας. Ο δικός του κόσμος.",
    ctaCopy: "Ας δημιουργήσουμε κάτι που σας εκφράζει.",
    contact: "Ας μιλήσουμε",
    categories: {
      restaurant: "Εστιατόριο",
      hospitality: "Φιλοξενία",
      cafe: "Καφέ",
      property: "Ακίνητα",
      beauty: "Ομορφιά",
      fitness: "Άθληση",
      health: "Υγεία",
      architecture: "Αρχιτεκτονική",
    },
  },
  he: {
    title: "העבודות שלנו",
    intro: "מותגים שונים. עולמות שונים. מוזמנים לגלות.",
    web: "עיצוב אתרים",
    demos: "אתרי הדגמה",
    hint: "גררו כדי לגלות. בחרו אתר כדי להיכנס אליו.",
    touchHint: "החליקו כדי לגלות. הקישו לבחירה ושוב לפתיחת האתר.",
    open: "לצפייה באתר",
    previous: "הקודם",
    next: "הבא",
    cta: "המותג שלכם. העולם שלו.",
    ctaCopy: "בואו ניצור משהו שמרגיש בדיוק כמוכם.",
    contact: "בואו נדבר",
    categories: {
      restaurant: "מסעדה",
      hospitality: "אירוח",
      cafe: "בית קפה",
      property: "נדל״ן",
      beauty: "ביוטי",
      fitness: "כושר",
      health: "בריאות",
      architecture: "אדריכלות",
    },
  },
};
