import type { SiteLanguage } from "@/lib/routeLanguage";

export const CONTACT_COPY = {
  en: {
    title: "Contact DM Labs | Free website consultation",
    description: "Have a website idea or a digital question? Talk directly with Tom and Anastacia. Request a free consultation by form, WhatsApp or email.",
    label: "A good place to start", opening: "Good things start", payoff: "with a conversation.",
    intro: "A new website, a better one, or a question you can’t quite put into words. Tell us what’s on your mind. We’ll work out the next step together.",
    cta: "Get a free consultation", whatsapp: "Ask us on WhatsApp", reassurance: "Free. No obligation.",
    asideTitle: "Your idea.\nOur full attention.", asideCopy: "You’ll speak directly with Tom and Anastacia. We’ll listen to what your business needs and help you find a useful starting point.",
    nextLabel: "What happens next", next: ["Tell us a little about your business or just ask a question.", "We’ll reply to understand what you need and discuss the next step.", "If we’re a good fit, we’ll agree the scope before any work begins."],
    directLabel: "Prefer to talk directly?", email: "Email", instagram: "Follow our work", hours: "Monday–Friday · 09:00–18:00 EET / EEST", location: "Based in Europe. Working worldwide.",
    formLabel: "Your next step", formTitle: "Ask us anything.", formIntro: "Only your name and email are required. Add as much or as little detail as you like.",
    name: "Your name", emailField: "Email address", business: "Business name", message: "Your question or idea", optional: "optional",
    messageHint: "What would you like your website to do? It’s fine if you’re still figuring it out.",
    submit: "Request a consultation", sending: "Sending your request…", privacy: "Read our privacy policy", privacyNote: "We’ll use these details to reply to your enquiry.",
    nameError: "Please enter your name.", emailError: "Please enter a valid email address.", longError: "Please shorten this field.",
    failureTitle: "We couldn’t confirm your request.", failure: "Your details are still here. Try again, or reach us directly by WhatsApp or email.",
    successTitle: "Request received.", success: "Thank you for getting in touch. We’ll reply to the email address you provided to discuss the next step.",
    successNote: "This is an enquiry, not a confirmed appointment.", another: "Send another question", defaultMessage: "I would like a free website consultation.",
    subject: "New consultation request", waText: "Hello DM-Labs team! I’d like to ask about a website for my business.",
  },
  el: {
    title: "Επικοινωνία DM Labs | Δωρεάν συμβουλευτική για την ιστοσελίδα σας",
    description: "Έχετε μια ιδέα για ιστοσελίδα ή μια ψηφιακή απορία; Μιλήστε απευθείας με τον Tom και την Anastacia. Δωρεάν συμβουλευτική μέσω φόρμας, WhatsApp ή email.",
    label: "Ας κάνουμε την αρχή", opening: "Ας τα πούμε", payoff: "για την ιδέα σας.",
    intro: "Θέλετε καινούργια ιστοσελίδα, να ανανεώσετε αυτή που έχετε, ή απλώς έχετε μια απορία που δεν έχει ξεκαθαρίσει ακόμα; Πείτε μας τι σκέφτεστε και θα βρούμε μαζί το επόμενο βήμα.",
    cta: "Δωρεάν συμβουλευτική", whatsapp: "Ρωτήστε μας στο WhatsApp", reassurance: "Δωρεάν και χωρίς καμία δέσμευση.",
    asideTitle: "Εσείς μιλάτε,\nεμείς ακούμε.", asideCopy: "Μιλάτε απευθείας με τον Tom και την Anastacia, όχι με κάποιο τηλεφωνικό κέντρο. Ακούμε τι χρειάζεται η επιχείρησή σας και σας βοηθάμε να βρείτε από πού να ξεκινήσετε.",
    nextLabel: "Τι ακολουθεί", next: ["Πείτε μας λίγα λόγια για την επιχείρησή σας ή κάντε απλώς μια ερώτηση.", "Σας απαντάμε, για να καταλάβουμε τι χρειάζεστε και να δούμε μαζί το επόμενο βήμα.", "Αν ταιριάξουμε, συμφωνούμε τι ακριβώς θα φτιάξουμε πριν πιάσουμε δουλειά."],
    directLabel: "Προτιμάτε να μας μιλήσετε κατευθείαν;", email: "Email", instagram: "Δείτε τη δουλειά μας", hours: "Δευτέρα–Παρασκευή · 09:00–18:00 EET / EEST", location: "Είμαστε στην Ευρώπη και δουλεύουμε με επιχειρήσεις σε όλο τον κόσμο.",
    formLabel: "Το επόμενο βήμα σας", formTitle: "Ρωτήστε μας ό,τι θέλετε.", formIntro: "Χρειαζόμαστε μόνο το όνομα και το email σας. Τα υπόλοιπα, όσα θέλετε.",
    name: "Το όνομά σας", emailField: "Διεύθυνση email", business: "Όνομα επιχείρησης", message: "Η ερώτηση ή η ιδέα σας", optional: "προαιρετικό",
    messageHint: "Τι θα θέλατε να κάνει η ιστοσελίδα για εσάς; Δεν χρειάζεται να τα έχετε όλα αποφασισμένα.",
    submit: "Στείλτε το μήνυμα", sending: "Αποστολή…", privacy: "Πολιτική απορρήτου", privacyNote: "Θα χρησιμοποιήσουμε αυτά τα στοιχεία για να απαντήσουμε στο αίτημά σας.",
    nameError: "Συμπληρώστε το όνομά σας.", emailError: "Συμπληρώστε μια έγκυρη διεύθυνση email.", longError: "Το κείμενο είναι πολύ μεγάλο. Συντομέψτε το λίγο.",
    failureTitle: "Κάτι πήγε στραβά με την αποστολή.", failure: "Μην ανησυχείτε, τα στοιχεία σας είναι ακόμα στη φόρμα. Δοκιμάστε ξανά ή στείλτε μας μήνυμα στο WhatsApp ή με email.",
    successTitle: "Λάβαμε το μήνυμά σας!", success: "Ευχαριστούμε! Θα σας απαντήσουμε στο email που μας δώσατε, για να δούμε μαζί το επόμενο βήμα.",
    successNote: "Πρόκειται για αίτημα επικοινωνίας, όχι για επιβεβαιωμένο ραντεβού.", another: "Στείλτε άλλη ερώτηση", defaultMessage: "Θα ήθελα μια δωρεάν συζήτηση για την ιστοσελίδα μου.",
    subject: "Νέο αίτημα επικοινωνίας", waText: "Γεια σας ομάδα DM-Labs! Θα ήθελα να ρωτήσω για μια ιστοσελίδα για την επιχείρησή μου.",
  },
  he: {
    title: "צרו קשר עם DM Labs | שיחת ייעוץ לאתר ללא עלות",
    description: "יש לכם רעיון לאתר או שאלה על דיגיטל? דברו ישירות עם טום ואנסטסיה. פנו לשיחת ייעוץ ללא עלות בטופס, בוואטסאפ או באימייל.",
    label: "מכאן מתחילים", opening: "בואו נדבר", payoff: "על הרעיון שלכם.",
    intro: "רוצים אתר חדש, לשדרג את האתר הקיים, או שיש לכם שאלה שעוד לא לגמרי התגבשה? ספרו לנו מה אתם חושבים, ונמצא יחד את הצעד הבא.",
    cta: "לשיחת ייעוץ בחינם", whatsapp: "שאלו אותנו ב-WhatsApp", reassurance: "בחינם וללא התחייבות.",
    asideTitle: "אתם מדברים,\nאנחנו מקשיבים.", asideCopy: "אתם מדברים ישירות עם טום ואנסטסיה, לא עם מוקד שירות. נקשיב למה שהעסק שלכם צריך ונעזור לכם להבין מאיפה הכי נכון להתחיל.",
    nextLabel: "מה קורה עכשיו", next: ["ספרו לנו קצת על העסק שלכם, או פשוט שאלו שאלה.", "נחזור אליכם כדי להבין מה אתם צריכים ולדבר על הצעד הבא.", "אם יש התאמה, נסגור יחד בדיוק מה בונים לפני שמתחילים לעבוד."],
    directLabel: "מעדיפים לדבר ישירות?", email: "אימייל", instagram: "הכירו את העבודה שלנו", hours: "שני–שישי · 09:00–18:00 EET / EEST", location: "אנחנו באירופה, ועובדים עם עסקים מכל העולם.",
    formLabel: "הצעד הבא שלכם", formTitle: "שאלו אותנו כל דבר.", formIntro: "צריך רק שם ואימייל. כל השאר, כמה שבא לכם.",
    name: "השם שלכם", emailField: "כתובת אימייל", business: "שם העסק", message: "השאלה או הרעיון שלכם", optional: "לא חובה",
    messageHint: "מה הייתם רוצים שהאתר שלכם יעשה? זה בסדר אם אתם עדיין בודקים את האפשרויות.",
    submit: "שליחת הודעה", sending: "שולחים…", privacy: "מדיניות הפרטיות", privacyNote: "נשתמש בפרטים האלה כדי לחזור אליכם לגבי הפנייה.",
    nameError: "נא להזין את השם שלכם.", emailError: "נא להזין כתובת אימייל תקינה.", longError: "נא לקצר את התוכן בשדה הזה.",
    failureTitle: "משהו השתבש בשליחה.", failure: "אל דאגה, הפרטים שלכם עדיין בטופס. אפשר לנסות שוב, או לכתוב לנו ישירות ב-WhatsApp או במייל.",
    successTitle: "ההודעה התקבלה!", success: "תודה שפניתם! נחזור אליכם למייל שהשארתם, ונדבר על הצעד הבא.",
    successNote: "זו פנייה לשיחה, ולא אישור לפגישה שנקבעה.", another: "שליחת שאלה נוספת", defaultMessage: "אשמח לשיחת ייעוץ בחינם לגבי אתר לעסק שלי.",
    subject: "בקשה חדשה לשיחת ייעוץ", waText: "שלום לצוות DM-Labs! אשמח לשאול על אתר לעסק שלי.",
  },
} satisfies Record<SiteLanguage, object>;

export const contactWhatsApp = (locale: SiteLanguage) => `https://wa.me/35797472847?text=${encodeURIComponent(CONTACT_COPY[locale].waText)}`;
export const contactPrivacy = (locale: SiteLanguage) => `${locale === "en" ? "" : `/${locale}`}/privacy/`;
