import type { SiteLanguage } from "@/lib/routeLanguage";

export const CONTACT_COPY = {
  en: {
    title: "Contact DM Labs | Free website consultation",
    description: "Have a website idea or a digital question? Talk directly with Tom and Anastacia. Request a free consultation by form, WhatsApp or email.",
    label: "A good place to start", opening: "Good things start", payoff: "with a conversation.",
    intro: "A new website, a better one, or a question you can’t quite put into words. Tell us what’s on your mind. We’ll work out the next step together.",
    cta: "Get a free consultation", whatsapp: "Ask us on WhatsApp", reassurance: "Free. No obligation.",
    asideTitle: "Your idea.\nOur full attention.", asideCopy: "You’ll speak directly with Tom and Anastacia. We’ll listen to what your business needs and help you find a useful starting point.",
    nextLabel: "What happens next", next: ["Tell us a little about your business or just ask a question.", "We’ll reply to understand what you need and discuss the next step.", "If we’re a good fit, we’ll agree the scope before any work begins."],
    directLabel: "Prefer to talk directly?", email: "Email", instagram: "Follow our work", hours: "Monday–Friday · 09:00–18:00 EET / EEST", location: "Based in Europe. Working worldwide.",
    formLabel: "Your next step", formTitle: "Ask us anything.", formIntro: "Only your name and email are required. Add as much or as little detail as you like.",
    name: "Your name", emailField: "Email address", business: "Business name", message: "Your question or idea", optional: "optional",
    messageHint: "What would you like your website to do? It’s fine if you’re still figuring it out.",
    submit: "Request a consultation", sending: "Sending your request…", privacy: "Read our privacy policy", privacyNote: "We’ll use these details to reply to your enquiry.",
    nameError: "Please enter your name.", emailError: "Please enter a valid email address.", longError: "Please shorten this field.",
    failureTitle: "We couldn’t confirm your request.", failure: "Your details are still here. Try again, or reach us directly by WhatsApp or email.",
    successTitle: "Request received.", success: "Thank you for getting in touch. We’ll reply to the email address you provided to discuss the next step.",
    successNote: "This is an enquiry, not a confirmed appointment.", another: "Send another question", defaultMessage: "I would like a free website consultation.",
    subject: "New consultation request", waText: "Hello DM-Labs team! I’d like to ask about a website for my business.",
  },
  el: {
    title: "Επικοινωνία DM Labs | Δωρεάν συμβουλευτική για την ιστοσελίδα σας",
    description: "Έχετε μια ιδέα για ιστοσελίδα ή μια ψηφιακή απορία; Μιλήστε απευθείας με τον Tom και την Anastacia. Δωρεάν συμβουλευτική μέσω φόρμας, WhatsApp ή email.",
    label: "Ας κάνουμε την αρχή", opening: "Ας μιλήσουμε", payoff: "για την ιδέα σας.",
    intro: "Μια νέα ιστοσελίδα, μια καλύτερη εκδοχή της υπάρχουσας ή μια απορία που δεν έχετε ακόμη ξεκαθαρίσει. Πείτε μας τι σκέφτεστε. Θα βρούμε μαζί το επόμενο βήμα.",
    cta: "Δωρεάν συμβουλευτική", whatsapp: "Ρωτήστε μας στο WhatsApp", reassurance: "Δωρεάν. Χωρίς καμία δέσμευση.",
    asideTitle: "Η ιδέα σας.\nΗ προσοχή μας.", asideCopy: "Θα μιλήσετε απευθείας με τον Tom και την Anastacia. Θα ακούσουμε τις ανάγκες της επιχείρησής σας και θα σας βοηθήσουμε να βρείτε από πού να ξεκινήσετε.",
    nextLabel: "Τι ακολουθεί", next: ["Πείτε μας λίγα λόγια για την επιχείρησή σας ή κάντε απλώς μια ερώτηση.", "Θα απαντήσουμε για να καταλάβουμε τι χρειάζεστε και να συζητήσουμε το επόμενο βήμα.", "Αν ταιριάζουμε, θα συμφωνήσουμε το εύρος του έργου πριν ξεκινήσει η δουλειά."],
    directLabel: "Προτιμάτε άμεση επικοινωνία;", email: "Email", instagram: "Δείτε τη δουλειά μας", hours: "Δευτέρα–Παρασκευή · 09:00–18:00 EET / EEST", location: "Με βάση την Ευρώπη. Για επιχειρήσεις παντού.",
    formLabel: "Το επόμενο βήμα σας", formTitle: "Ρωτήστε μας.", formIntro: "Χρειαζόμαστε μόνο το όνομα και το email σας. Προσθέστε όσες λεπτομέρειες θέλετε.",
    name: "Το όνομά σας", emailField: "Διεύθυνση email", business: "Όνομα επιχείρησης", message: "Η ερώτηση ή η ιδέα σας", optional: "προαιρετικό",
    messageHint: "Τι θα θέλατε να πετυχαίνει η ιστοσελίδα σας; Δεν χρειάζεται να τα έχετε αποφασίσει όλα.",
    submit: "Ζητήστε μια συζήτηση", sending: "Αποστολή αιτήματος…", privacy: "Πολιτική απορρήτου", privacyNote: "Θα χρησιμοποιήσουμε αυτά τα στοιχεία για να απαντήσουμε στο αίτημά σας.",
    nameError: "Συμπληρώστε το όνομά σας.", emailError: "Συμπληρώστε μια έγκυρη διεύθυνση email.", longError: "Μειώστε το μήκος αυτού του πεδίου.",
    failureTitle: "Δεν μπορέσαμε να επιβεβαιώσουμε την αποστολή.", failure: "Τα στοιχεία σας παραμένουν στη φόρμα. Δοκιμάστε ξανά ή επικοινωνήστε μαζί μας μέσω WhatsApp ή email.",
    successTitle: "Λάβαμε το αίτημά σας.", success: "Ευχαριστούμε για την επικοινωνία. Θα απαντήσουμε στο email που δηλώσατε για να συζητήσουμε το επόμενο βήμα.",
    successNote: "Πρόκειται για αίτημα επικοινωνίας, όχι για επιβεβαιωμένο ραντεβού.", another: "Στείλτε άλλη ερώτηση", defaultMessage: "Θα ήθελα μια δωρεάν συζήτηση για την ιστοσελίδα μου.",
    subject: "Νέο αίτημα επικοινωνίας", waText: "Γεια σας ομάδα DM-Labs! Θα ήθελα να ρωτήσω για μια ιστοσελίδα για την επιχείρησή μου.",
  },
  he: {
    title: "צרו קשר עם DM Labs | שיחת ייעוץ לאתר ללא עלות",
    description: "יש לכם רעיון לאתר או שאלה על דיגיטל? דברו ישירות עם טום ואנסטסיה. פנו לשיחת ייעוץ ללא עלות בטופס, בוואטסאפ או באימייל.",
    label: "מכאן מתחילים", opening: "בואו נדבר", payoff: "על הרעיון שלכם.",
    intro: "אתר חדש, שיפור לאתר קיים או שאלה שעדיין לא לגמרי התגבשה. ספרו לנו מה מעסיק אתכם. נמצא יחד את הצעד הבא.",
    cta: "לשיחת ייעוץ ללא עלות", whatsapp: "שאלו אותנו בוואטסאפ", reassurance: "ללא עלות וללא התחייבות.",
    asideTitle: "הרעיון שלכם.\nתשומת הלב שלנו.", asideCopy: "תדברו ישירות עם טום ואנסטסיה. נקשיב למה שהעסק שלכם צריך ונעזור לכם למצוא נקודת פתיחה מתאימה.",
    nextLabel: "מה קורה עכשיו", next: ["ספרו לנו קצת על העסק שלכם, או פשוט שאלו שאלה.", "נחזור אליכם כדי להבין מה אתם צריכים ולדבר על הצעד הבא.", "אם נתאים זה לזה, נסכם את היקף העבודה לפני שמתחילים."],
    directLabel: "מעדיפים לדבר ישירות?", email: "אימייל", instagram: "הכירו את העבודה שלנו", hours: "שני–שישי · 09:00–18:00 EET / EEST", location: "פועלים מאירופה. עובדים עם עסקים בכל העולם.",
    formLabel: "הצעד הבא שלכם", formTitle: "שאלו אותנו כל דבר.", formIntro: "צריך רק שם ואימייל. אפשר להוסיף כמה פרטים שתרצו.",
    name: "השם שלכם", emailField: "כתובת אימייל", business: "שם העסק", message: "השאלה או הרעיון שלכם", optional: "לא חובה",
    messageHint: "מה הייתם רוצים שהאתר שלכם יעשה? זה בסדר אם אתם עדיין בודקים את האפשרויות.",
    submit: "שליחת בקשה לשיחת ייעוץ", sending: "הבקשה נשלחת…", privacy: "מדיניות הפרטיות", privacyNote: "נשתמש בפרטים האלה כדי לחזור אליכם לגבי הפנייה.",
    nameError: "נא להזין את השם שלכם.", emailError: "נא להזין כתובת אימייל תקינה.", longError: "נא לקצר את התוכן בשדה הזה.",
    failureTitle: "לא הצלחנו לאשר את קבלת הבקשה.", failure: "הפרטים שלכם נשמרו בטופס. אפשר לנסות שוב או לפנות אלינו ישירות בוואטסאפ או באימייל.",
    successTitle: "הבקשה התקבלה.", success: "תודה שפניתם אלינו. נחזור לכתובת האימייל שמסרתם כדי לדבר על הצעד הבא.",
    successNote: "זו פנייה לשיחה, ולא אישור לפגישה שנקבעה.", another: "שליחת שאלה נוספת", defaultMessage: "אשמח לשיחת ייעוץ ללא עלות לגבי אתר לעסק שלי.",
    subject: "בקשה חדשה לשיחת ייעוץ", waText: "שלום לצוות DM-Labs! אשמח לשאול על אתר לעסק שלי.",
  },
} satisfies Record<SiteLanguage, object>;

export const contactWhatsApp = (locale: SiteLanguage) => `https://wa.me/35797472847?text=${encodeURIComponent(CONTACT_COPY[locale].waText)}`;
export const contactPrivacy = (locale: SiteLanguage) => `${locale === "en" ? "" : `/${locale}`}/privacy/`;
